import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const source = readFileSync(resolve(process.cwd(), "src/lib/agent-runtime/observability/postgres-repository.ts"), "utf8");

describe("Postgres Observability repository contract", () => {
  it("serializes aggregate deltas and preserves exact replay receipts", () => { const method = source.slice(source.indexOf("applyMetricDelta("), source.indexOf("async listMetrics(")); expect(method).toContain("pg_advisory_xact_lock"); expect(method).toContain("runtimeOperationalMetricDeltaReceipts"); expect(method).toContain('kind: "replayed"'); expect(method).toContain("count: metric(row.value).count + input.countDelta"); });
  it("bounds metric and trace expiry before deletion", () => { const method = source.slice(source.indexOf("expire(at:")); expect(method).toContain(".limit(limit).for(\"update\", { skipLocked: true })"); expect(method).toContain("inArray(runtimeDiagnosticTraces.operatorTraceRef"); expect(method).toContain("inArray(runtimeOperationalMetrics.id"); });
  it("persists expiry audits and retains bundle locators until durable cleanup acknowledgement", () => { const method = source.slice(source.indexOf("expire(at:")); expect(method).toContain('eventType: "grant.expired"'); expect(method).toContain('eventType: "bundle.expired"'); expect(source).toContain("listSupportBundleCleanup"); expect(source).toContain("acknowledgeSupportBundleCleanup"); expect(source).toContain("not exists (select 1 from runtime_support_bundles active"); const acknowledge = source.slice(source.indexOf("acknowledgeSupportBundleCleanup("), source.indexOf("expire(at:")); expect(acknowledge).toContain("storageKey: null"); expect(acknowledge).toContain("contentDigest: null"); });
  it("does not collapse admin transaction outages into conflicts", () => { expect(source.match(/catch\(\(\) => "unavailable" as const\)/g)?.length).toBeGreaterThanOrEqual(3); });
  it("persists bundle probes independently of bundle lifecycle foreign keys", () => { const append = source.slice(source.indexOf("appendSupportBundleAccessAudit("), source.indexOf("listSupportBundleCleanup(")); expect(append).toContain("runtimeSupportBundleAccessAudits"); expect(append).not.toContain("runtimeSupportBundleAuditEvents).values"); const list = source.slice(source.indexOf("listSupportBundleAudit("), source.indexOf("appendSupportBundleAccessAudit(")); expect(list).toContain("runtimeSupportBundleAccessAudits"); expect(list).toContain('outcome === "granted" ? "bundle.read" : "bundle.read_denied"'); });
  it("atomically validates frozen intent metadata before binding and clearing payload", () => { const method = source.slice(source.indexOf("createSupportBundle("), source.indexOf("async getSupportBundle(")); expect(method).toContain("supportBundleIntentMatchesRecord"); expect(method).toContain("bindIntentRequestDigest"); expect(method).toContain('state: "bound"'); expect(method).toContain("payloadJson: null"); expect(method).toContain("returning({ id: runtimeSupportBundleBindIntents.id })"); });
});
