import { describe, expect, it } from "vitest";
import { InMemoryObservabilityRepository } from "../memory";
import { ObservabilityService, supportBundleSelectionDigest } from "../service";
import type { ContractEvidenceReference, ObservabilityCursorCodec, SupportBundleSelection } from "../types";

const now = new Date("2026-08-01T12:00:00.000Z");
const later = (seconds: number) => new Date(now.getTime() + seconds * 1_000);
const codec: ObservabilityCursorCodec = { encode: async (value) => `signed:${JSON.stringify(value)}`, decode: async (value) => value.startsWith("signed:") ? JSON.parse(value.slice(7)) : null };
const reference: ContractEvidenceReference = { schema: "contract-evidence-reference/v1", workspaceId: "workspace_1", resourceKind: "run", resourceId: "run_1", version: 1, digest: `sha256:${"a".repeat(64)}` };
const selection: SupportBundleSelection = { reference, projectionKind: "run_summary", projectedContentDigest: `sha256:${"b".repeat(64)}`, projectedSizeBytes: 42 };

function setup() { const repository = new InMemoryObservabilityRepository(); return { repository, service: new ObservabilityService(repository, codec) }; }
async function configure(service: ObservabilityService) { return service.setRetention({ workspaceId: "workspace_1", metricTtlSeconds: 3600, traceTtlSeconds: 600, supportBundleTtlSeconds: 1800, actorUserId: "owner_1", idempotencyKey: "retention_v1", recordedAt: now }); }
async function grant(service: ObservabilityService) { return service.issueOperatorGrant({ workspaceId: "workspace_1", operatorId: "operator_1", scopes: ["trace.read", "support_bundle.read"], expiresAt: later(900), issuedByUserId: "owner_1", actorRole: "owner", idempotencyKey: "grant_1", recordedAt: now }); }
function bundleInput() { const selections = [selection]; return { workspaceId: "workspace_1", selections, consent: { schema: "support-bundle-consent/v1" as const, grantedByUserId: "user_1", purpose: "incident_diagnosis" as const, selectionDigest: supportBundleSelectionDigest(selections), grantedAt: now, expiresAt: later(1200) }, contentDigest: `sha256:${"c".repeat(64)}` as const, sizeBytes: 100, idempotencyKey: "bundle_1", storedAt: now, recordedAt: now }; }

describe("ObservabilityService", () => {
  it("bootstraps an administrator-visible durable safe default on first read", async () => { const { service, repository } = setup(); await expect(service.getRetention({ workspaceId: "workspace_1" })).resolves.toMatchObject({ revision: { revision: 1, metricTtlSeconds: 2_592_000, traceTtlSeconds: 86_400, supportBundleTtlSeconds: 604_800, createdByUserId: null } }); expect(repository.revisions.size).toBe(1); await service.getRetention({ workspaceId: "workspace_1" }); expect(repository.revisions.size).toBe(1); });
  it("persists canonical narrowing retention across concurrent replay and restart", async () => { const { service, repository } = setup(); const [a, b] = await Promise.all([configure(service), configure(service)]); expect(b).toEqual(a); expect(repository.revisions.size).toBe(1); const restarted = new ObservabilityService(repository, codec); await expect(restarted.setRetention({ workspaceId: "workspace_1", metricTtlSeconds: 1800, traceTtlSeconds: 300, supportBundleTtlSeconds: 900, actorUserId: "owner_1", idempotencyKey: "retention_v2", recordedAt: later(1) })).resolves.toMatchObject({ revision: { revision: 2 } }); });

  it("rejects stale metric/trace TTLs after a concurrent retention narrowing", async () => { const { service, repository } = setup(); await configure(service); await service.setRetention({ workspaceId: "workspace_1", metricTtlSeconds: 60, traceTtlSeconds: 60, supportBundleTtlSeconds: 60, actorUserId: "owner_1", idempotencyKey: "narrow", recordedAt: later(1) }); const staleTrace = { schema: "diagnostic-trace/v1" as const, operatorTraceRef: `otr_${"a".repeat(32)}`, workspaceId: "workspace_1", category: "runtime" as const, severity: "error" as const, code: "FAILED", stage: "execution" as const, outcome: "failed" as const, providerFamily: "internal" as const, httpStatus: null, retryable: null, durationMs: null, attempt: null, createdAt: later(2), expiresAt: later(602) }; await expect(repository.appendTrace(staleTrace)).resolves.toBe("conflict"); const staleMetric = { schema: "operational-metric-aggregate/v1" as const, id: "oma_stale", workspaceId: "workspace_1", name: "runtime.run.count" as const, dimensions: [], windowStartsAt: now, windowEndsAt: later(60), count: 1, sum: 1, recordedAt: later(2), expiresAt: later(602) }; await expect(repository.applyMetricDelta({ aggregate: staleMetric, eventId: "stale", requestDigest: `sha256:${"d".repeat(64)}`, countDelta: 1, sumDelta: 1 })).resolves.toMatchObject({ kind: "conflict" }); });

  it("caps operator grants at 30 days", async () => { const { service } = setup(); await expect(service.issueOperatorGrant({ workspaceId: "workspace_1", operatorId: "operator_1", scopes: ["trace.read"], expiresAt: later(2_592_001), issuedByUserId: "owner_1", actorRole: "owner", idempotencyKey: "too_long", recordedAt: now })).rejects.toMatchObject({ code: "OBSERVABILITY_INVALID_INPUT" }); });

  it("atomically aggregates concurrent metric deltas and replays exact events once", async () => { const { service } = setup(); await configure(service); const delta = (eventId: string) => service.recordMetricDelta({ workspaceId: "workspace_1", eventId, name: "runtime.run.count", dimensions: [{ key: "status", value: "completed" }], windowStartsAt: now, windowEndsAt: later(60), countDelta: 1, sumDelta: 1, recordedAt: later(60) }); const rows = await Promise.all(Array.from({ length: 20 }, (_, index) => delta(`event_${index}`))); expect(rows.at(-1)?.count).toBe(20); await delta("event_0"); await expect(service.listMetrics({ workspaceId: "workspace_1", cursor: null, limit: 10, at: later(61) })).resolves.toMatchObject({ metrics: [{ count: 20, sum: 20 }] }); });

  it("rejects high-cardinality metric labels and strips adversarial extras", async () => { const { service, repository } = setup(); await configure(service); const aggregate = await service.recordMetricDelta({ workspaceId: "workspace_1", eventId: "event_safe", name: "runtime.run.count", dimensions: [{ key: "status", value: "completed" }], windowStartsAt: now, windowEndsAt: later(60), countDelta: 1, sumDelta: 1, recordedAt: later(60), prompt: "LEAK_CANARY" } as never); expect(JSON.stringify(repository.metrics.get(aggregate.id))).not.toContain("LEAK_CANARY"); await expect(service.recordMetricDelta({ workspaceId: "workspace_1", eventId: "event_bad", name: "runtime.run.count", dimensions: [{ key: "runId", value: "run_1" }], windowStartsAt: now, windowEndsAt: later(60), countDelta: 1, sumDelta: 1, recordedAt: later(60) } as never)).rejects.toMatchObject({ code: "OBSERVABILITY_INVALID_INPUT" }); });

  it("requires workspace-bound opaque cursors", async () => { const { service } = setup(); await configure(service); await service.recordMetricDelta({ workspaceId: "workspace_1", eventId: "e1", name: "runtime.run.count", dimensions: [], windowStartsAt: now, windowEndsAt: later(60), countDelta: 1, sumDelta: 1, recordedAt: later(1) }); await service.recordMetricDelta({ workspaceId: "workspace_1", eventId: "e2", name: "runtime.queue.wait_ms", dimensions: [], windowStartsAt: now, windowEndsAt: later(60), countDelta: 1, sumDelta: 2, recordedAt: later(2) }); const first = await service.listMetrics({ workspaceId: "workspace_1", cursor: null, limit: 1, at: later(3) }); expect(first.nextCursor).toMatch(/^signed:/); await expect(service.listMetrics({ workspaceId: "workspace_other", cursor: first.nextCursor, limit: 1, at: later(3) })).rejects.toMatchObject({ code: "OBSERVABILITY_INVALID_INPUT" }); });

  it("stores only fixed trace fields and audits denied and granted reads", async () => { const { service, repository } = setup(); await configure(service); const ref = await service.recordTrace({ workspaceId: "workspace_1", category: "provider", severity: "error", code: "PROVIDER_TIMEOUT", stage: "execution", outcome: "unknown", providerFamily: "openai", httpStatus: 504, retryable: true, durationMs: 1, attempt: 1, createdAt: later(1), prompt: "LEAK_CANARY" } as never); expect(JSON.stringify(repository.traces.get(ref))).not.toContain("LEAK_CANARY"); await expect(service.readTrace({ workspaceId: "workspace_1", operatorTraceRef: ref, operatorGrantId: "missing", operatorId: "operator_1", at: later(2) })).rejects.toMatchObject({ code: "OBSERVABILITY_FORBIDDEN" }); const issued = await grant(service); await expect(service.readTrace({ workspaceId: "workspace_1", operatorTraceRef: ref, operatorGrantId: issued.id, operatorId: "operator_1", at: later(2) })).resolves.toMatchObject({ code: "PROVIDER_TIMEOUT" }); expect([...repository.traceAccessAudits.values()].map((item) => item.outcome)).toEqual(["denied", "granted"]); });

  it("rejects invalid read/expiry dates and fails closed when granted-read audit persistence fails", async () => { class BrokenAuditRepository extends InMemoryObservabilityRepository { override async appendTraceAccessAudit() { throw new Error("down"); } override async appendSupportBundleAccessAudit() { throw new Error("down"); } } const repository = new BrokenAuditRepository(); const service = new ObservabilityService(repository, codec); await configure(service); const issued = await grant(service); const ref = await service.recordTrace({ workspaceId: "workspace_1", category: "runtime", severity: "error", code: "FAILED", stage: "execution", outcome: "failed", providerFamily: "internal", httpStatus: null, retryable: null, durationMs: null, attempt: null, createdAt: now }); await expect(service.readTrace({ workspaceId: "workspace_1", operatorTraceRef: ref, operatorGrantId: issued.id, operatorId: "operator_1", at: new Date("invalid") })).rejects.toMatchObject({ code: "OBSERVABILITY_INVALID_INPUT" }); await expect(service.readTrace({ workspaceId: "workspace_1", operatorTraceRef: ref, operatorGrantId: issued.id, operatorId: "operator_1", at: later(1) })).rejects.toMatchObject({ code: "OBSERVABILITY_UNAVAILABLE" }); const bundle = await service.createStoredSupportBundle(bundleInput()); await expect(service.readSupportBundle({ workspaceId: "workspace_1", bundleId: bundle.id, operatorGrantId: issued.id, operatorId: "operator_1", at: later(1) })).rejects.toMatchObject({ code: "OBSERVABILITY_UNAVAILABLE" }); expect(() => service.expire(new Date("invalid"))).toThrow(expect.objectContaining({ code: "OBSERVABILITY_INVALID_INPUT" })); expect(() => service.expire(now, Number.NaN)).toThrow(expect.objectContaining({ code: "OBSERVABILITY_INVALID_INPUT" })); expect(() => service.expire(now, 1.5)).toThrow(expect.objectContaining({ code: "OBSERVABILITY_INVALID_INPUT" })); });

  it("durably audits denied and not-found Support Bundle probes without a bundle row", async () => { const { service, repository } = setup(); await configure(service); await expect(service.readSupportBundle({ workspaceId: "workspace_1", bundleId: "osb_missing", operatorGrantId: "grant_missing", operatorId: "operator_1", at: later(1) })).rejects.toMatchObject({ code: "OBSERVABILITY_FORBIDDEN" }); const issued = await grant(service); await expect(service.readSupportBundle({ workspaceId: "workspace_1", bundleId: "osb_missing", operatorGrantId: issued.id, operatorId: "operator_1", at: later(2) })).resolves.toBeNull(); expect([...repository.bundleAccessAudits.values()].map((event) => event.outcome)).toEqual(["denied", "not_found"]); expect(repository.audits.size).toBe(0); });

  it("uses bundle-local object keys and durably retries cleanup until acknowledgement", async () => { const { service, repository } = setup(); await configure(service); const [a, replay] = await Promise.all([service.createStoredSupportBundle(bundleInput()), service.createStoredSupportBundle(bundleInput())]); expect(replay).toEqual(a); const b = await service.createStoredSupportBundle({ ...bundleInput(), idempotencyKey: "bundle_2" }); const issued = await grant(service); const firstPayload = await service.readSupportBundlePayload({ workspaceId: "workspace_1", bundleId: a.id, operatorGrantId: issued.id, operatorId: "operator_1", at: later(1) }); const secondPayload = await service.readSupportBundlePayload({ workspaceId: "workspace_1", bundleId: b.id, operatorGrantId: issued.id, operatorId: "operator_1", at: later(1) }); expect(firstPayload?.storageKey).not.toBe(secondPayload?.storageKey); await service.revokeSupportBundle({ workspaceId: "workspace_1", bundleId: a.id, actorUserId: "owner_1", actorRole: "owner", recordedAt: later(2) }); await expect(service.createStoredSupportBundle(bundleInput())).resolves.toMatchObject({ id: a.id, state: "revoked" }); const targets = await service.listSupportBundleCleanup({ at: later(2), limit: 10 }); expect(targets).toHaveLength(1); expect(await service.listSupportBundleCleanup({ at: later(2), limit: 10 })).toEqual(targets); await service.acknowledgeSupportBundleCleanup(targets[0]!); expect(repository.bundles.get(a.id)).toMatchObject({ storageKey: null, contentDigest: null }); expect(await service.listSupportBundleCleanup({ at: later(2), limit: 10 })).toEqual([]); expect((await service.listSupportBundleAudit({ workspaceId: "workspace_1", bundleId: a.id, limit: 100 })).map((item) => item.eventType)).toEqual(["bundle.stored", "bundle.read", "bundle.revoked"]); });

  it("rejects forged selection digests and live/cross-resource projection kinds", async () => { const { service } = setup(); await configure(service); await expect(service.createStoredSupportBundle({ ...bundleInput(), selections: [{ ...selection, projectionKind: "artifact_metadata" }], idempotencyKey: "forged" })).rejects.toMatchObject({ code: "OBSERVABILITY_INVALID_INPUT" }); await expect(service.createStoredSupportBundle({ ...bundleInput(), consent: { ...bundleInput().consent, selectionDigest: `sha256:${"0".repeat(64)}` }, idempotencyKey: "forged_digest" })).rejects.toMatchObject({ code: "OBSERVABILITY_INVALID_INPUT" }); });
});
