"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { Clock, FileClock, LoaderCircle, Save, WandSparkles } from "lucide-react";
import { ARABIC_VARIETIES, CONTENT_FORMATS, CONTENT_FORMAT_DEFINITIONS, type ContentFormat } from "@/lib/product-surfaces/definitions";
import { productRequest } from "@/components/product-surfaces/ProductApi";

type Piece = { id: string; title: string; revision: number; payload: Record<string, unknown> };
export function ContentBuilder({ selectedFormat, selectedPiece, pieces }: { selectedFormat: ContentFormat; selectedPiece: Piece | null; pieces: Piece[] }) {
  const t = useTranslations("product.content") as (key: string, values?: Record<string, string | number>) => string; const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const definition = CONTENT_FORMAT_DEFINITIONS[selectedFormat]; const payload = selectedPiece?.payload;
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); const language = String(data.get("language")); const nextPayload = { format: selectedFormat, contentLanguage: language, arabicVariety: language === "ar" ? String(data.get("arabicVariety")) : null, prompt: String(data.get("prompt")), script: String(data.get("script")), aspectRatio: String(data.get("aspectRatio")), durationSeconds: Number(data.get("duration")), captionStyle: String(data.get("captionStyle")), sourceAssetIds: String(data.get("assets")).split(",").map((v) => v.trim()).filter(Boolean), candidateArtifactIds: (payload?.candidateArtifactIds as string[]) ?? [], renderProofStatus: String(payload?.renderProofStatus ?? "not_requested") };
    try { if (selectedPiece) await productRequest("/api/product-records", { id: selectedPiece.id, expectedRevision: selectedPiece.revision, title: String(data.get("title")), payload: nextPayload, idempotencyKey: crypto.randomUUID() }, "PATCH"); else await productRequest("/api/product-records", { kind: "content_piece", title: String(data.get("title")), state: "active", payload: nextPayload, idempotencyKey: crypto.randomUUID() }); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("error")); } finally { setBusy(false); } }
  return <div className="grid gap-6 xl:grid-cols-[260px_1fr_340px]"><aside className="rounded-3xl border bg-card p-4"><h2 className="px-2 text-sm font-semibold">{t("formatsTitle")}</h2><nav className="mt-3 space-y-1">{CONTENT_FORMATS.map((format) => <Link key={format} href={`/content?format=${format}`} className={`block rounded-xl px-3 py-2.5 text-sm ${format === selectedFormat ? "bg-amber-100 font-semibold text-amber-950" : "hover:bg-muted"}`}>{t(`formats.${format}`)}</Link>)}</nav></aside>
    <form onSubmit={save} className="space-y-5 rounded-3xl border bg-card p-6"><div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs text-amber-950">{t(`formats.${selectedFormat}`)}</span><h2 className="mt-4 text-2xl font-semibold">{selectedPiece ? t("editTitle", { revision: selectedPiece.revision }) : t("newTitle")}</h2><p className="mt-2 text-sm text-muted-foreground">{t("autosaveHelp")}</p></div><Field name="title" label={t("fields.title")} value={selectedPiece?.title ?? ""} /><label className="grid gap-2 text-sm font-medium">{t("fields.script")}<textarea dir="auto" name="script" defaultValue={String(payload?.script ?? "")} required={definition.requiredInputs.includes("script")} className="min-h-44 rounded-xl border bg-background p-3 font-normal" /></label><label className="grid gap-2 text-sm font-medium">{t("fields.prompt")}<textarea dir="auto" name="prompt" defaultValue={String(payload?.prompt ?? "")} className="min-h-24 rounded-xl border bg-background p-3 font-normal" /></label><div className="grid gap-4 sm:grid-cols-2"><Select name="language" label={t("fields.language")} value={String(payload?.contentLanguage ?? "ar")} options={["ar", "en"]} optionLabel={(v) => t(`languages.${v}`)} /><Select name="arabicVariety" label={t("fields.variety")} value={String(payload?.arabicVariety ?? "msa")} options={[...ARABIC_VARIETIES]} optionLabel={(v) => t(`varieties.${v}`)} /><Select name="aspectRatio" label={t("fields.aspect")} value={String(payload?.aspectRatio ?? definition.aspectRatio)} options={["9:16", "1:1", "16:9"]} optionLabel={(v) => v} /><label className="grid gap-2 text-sm font-medium">{t("fields.duration")}<input name="duration" type="number" min={definition.duration[0]} max={definition.duration[1]} defaultValue={Number(payload?.durationSeconds ?? 15)} className="min-h-11 rounded-xl border bg-background px-3" /></label></div><Field name="captionStyle" label={t("fields.captions")} value={String(payload?.captionStyle ?? "brand")} /><Field name="assets" label={t("fields.assets")} value={((payload?.sourceAssetIds as string[]) ?? []).join(", ")} required={definition.requiredInputs.some((input) => ["images", "video", "app_capture"].includes(input))} /><div className="rounded-xl bg-muted p-4 text-sm"><p className="font-semibold">{t("requirements")}</p><p className="mt-2 text-muted-foreground">{definition.requiredInputs.map((input) => t(`inputs.${input}`)).join(" · ")} · {t("renderProof")}</p></div><button disabled={busy} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-amber-300 font-semibold text-stone-950 disabled:opacity-50">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}{t("save")}</button>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</form>
    <aside className="space-y-5"><div className="rounded-3xl bg-stone-950 p-5 text-white"><div className="mx-auto aspect-[9/16] max-h-[430px] rounded-[1.6rem] border border-white/10 bg-[linear-gradient(160deg,#44403c,#0c0a09)] p-5"><span className="text-xs text-amber-300">{t("preview")}</span><p dir="auto" className="mt-12 text-2xl font-semibold">{String(payload?.script || t("previewEmpty"))}</p></div><Link href="/ai-studio" className="mt-4 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-white text-sm font-semibold text-stone-950"><WandSparkles className="size-4" />{t("generate")}</Link></div><div className="rounded-3xl border bg-card p-5"><h2 className="flex items-center gap-2 font-semibold"><FileClock className="size-4" />{t("pieces")}</h2><div className="mt-3 space-y-2">{pieces.slice(0, 8).map((piece) => <Link key={piece.id} href={`/content?format=${String(piece.payload.format)}&piece=${piece.id}`} className="flex items-center justify-between rounded-xl bg-muted p-3 text-sm"><span className="truncate">{piece.title}</span><span className="ms-2 flex shrink-0 items-center gap-1 text-xs text-muted-foreground"><Clock className="size-3" />v{piece.revision}</span></Link>)}</div></div></aside></div>;
}
function Field({ name, label, value, required = true }: { name: string; label: string; value: string; required?: boolean }) { return <label className="grid gap-2 text-sm font-medium">{label}<input dir="auto" name={name} defaultValue={value} required={required} className="min-h-11 rounded-xl border bg-background px-3 font-normal" /></label>; }
function Select({ name, label, value, options, optionLabel }: { name: string; label: string; value: string; options: string[]; optionLabel: (value: string) => string }) { return <label className="grid gap-2 text-sm font-medium">{label}<select name={name} defaultValue={value} className="min-h-11 rounded-xl border bg-background px-3">{options.map((option) => <option key={option} value={option}>{optionLabel(option)}</option>)}</select></label>; }
