"use client";
import { useRef, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { Clock, FileClock, Film, LoaderCircle, Save, Send, WandSparkles } from "lucide-react";
import { ARABIC_VARIETIES, CONTENT_FORMATS, CONTENT_FORMAT_DEFINITIONS, type ContentFormat } from "@/lib/product-surfaces/definitions";
import { productRequest } from "@/components/product-surfaces/ProductApi";
import { ModelSelect } from "@/components/simple-studio-shell/forms/ModelSelect";
import { runAdmittedStudioGeneration } from "@/lib/model-routing/studio-generation-client";
import { useSimpleStudioStore } from "@/store/simpleStudioStore";
import { contentExecutionPlan, contentProviderSourceIds } from "@/lib/product-surfaces/content-execution-plan";

type Piece = { id: string; title: string; revision: number; payload: Record<string, unknown> };
export function ContentBuilder({ selectedFormat, selectedPiece, pieces }: { selectedFormat: ContentFormat; selectedPiece: Piece | null; pieces: Piece[] }) {
  const t = useTranslations("product.content") as (key: string, values?: Record<string, string | number>) => string; const router = useRouter(); const formRef = useRef<HTMLFormElement>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [generationMode, setGenerationMode] = useState<"copy" | "media">("copy"); const definition = CONTENT_FORMAT_DEFINITIONS[selectedFormat]; const executionPlan = contentExecutionPlan(selectedFormat); const payload = selectedPiece?.payload;
  const modelId = useSimpleStudioStore((state) => state.selectedModelId); const modelProvider = useSimpleStudioStore((state) => state.selectedModelProvider); const modelVersion = useSimpleStudioStore((state) => state.selectedModelVersion); const modelSchema = useSimpleStudioStore((state) => state.selectedModelSchemaDigest); const fundingMode = useSimpleStudioStore((state) => state.fundingMode);
  function formPayload(data: FormData) { const language = String(data.get("language")); return { format: selectedFormat, contentLanguage: language, arabicVariety: language === "ar" ? String(data.get("arabicVariety")).trim() || null : null, prompt: String(data.get("prompt")), script: String(data.get("script")), aspectRatio: "9:16", durationSeconds: Number(data.get("duration")), captionStyle: String(data.get("captionStyle")), sourceAssetIds: String(data.get("assets")).split(",").map((v) => v.trim()).filter(Boolean), personaId: String(data.get("personaId") || "").trim() || null, candidateArtifactIds: (payload?.candidateArtifactIds as string[]) ?? [], candidates: (payload?.candidates as unknown[]) ?? [], renderProofStatus: String(payload?.renderProofStatus ?? "not_requested") }; }
  async function persist(data: FormData) { const result = await productRequest("/api/product-content", { ...(selectedPiece ? { id: selectedPiece.id, expectedRevision: selectedPiece.revision } : {}), title: String(data.get("title")), payload: formPayload(data), idempotencyKey: crypto.randomUUID() }); const record = result.record; if (!record || typeof record !== "object" || typeof (record as Piece).id !== "string" || typeof (record as Piece).revision !== "number") throw new Error("CONTENT_RESPONSE_INVALID"); return record as Piece; }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { await persist(new FormData(event.currentTarget)); router.refresh(); } catch { setError(t("error")); } finally { setBusy(false); } }
  async function generateScript() { const form = formRef.current; if (!form || !modelId || modelProvider !== "replicate" || !modelVersion || !modelSchema) { setError(t("modelRequired")); return; } setBusy(true); setError(""); const controller = new AbortController(); try { const data = new FormData(form); const saved = await persist(data); const language = String(data.get("language")) as "ar" | "en"; const prompt = String(data.get("prompt") || data.get("script")); const generated = await runAdmittedStudioGeneration({ prompt, contentLanguage: language, model: { provider: "replicate", model: modelId, version: modelVersion, inputSchemaDigest: modelSchema }, mode: "copy", sourceMediaType: null, sourceAssetIds: [], quantity: 1, fundingMode, arabicVariety: language === "ar" ? String(data.get("arabicVariety")) as (typeof ARABIC_VARIETIES)[number] : null, rightsBasis: "owned", permittedRemix: "reference_only", rightsEvidenceIds: [], remixBrief: { preserve: ["accepted Brand Profile identity", "requested content format"], transform: [], avoid: ["unverified claims"] }, idempotencyKey: crypto.randomUUID(), signal: controller.signal }); if (!generated.textOutputId) throw new Error("CANONICAL_TEXT_OUTPUT_RECEIPT_MISSING"); await productRequest("/api/product-content/generation", { kind: "text", id: saved.id, expectedRevision: saved.revision, textOutputId: generated.textOutputId, idempotencyKey: crypto.randomUUID() }); router.refresh(); } catch { setError(t("error")); } finally { setBusy(false); } }
  async function generateMedia() { const form = formRef.current; if (!form) return; if (executionPlan.strategy === "admitted_generation" && (!modelId || modelProvider !== "replicate" || !modelVersion || !modelSchema)) { setError(t("modelRequired")); return; } setBusy(true); setError(""); try { const data = new FormData(form); const saved = await persist(data); if (executionPlan.strategy === "canonical_upload") { await productRequest("/api/product-content/generation", { kind: "upload", id: saved.id, expectedRevision: saved.revision, idempotencyKey: crypto.randomUUID() }); router.refresh(); return; } const sourceAssetIds = String(data.get("assets")).split(",").map((value) => value.trim()).filter(Boolean); const providerSourceIds = contentProviderSourceIds(selectedFormat, sourceAssetIds); const language = String(data.get("language")) as "ar" | "en"; const prompt = [String(data.get("prompt")), String(data.get("script")), t(`formats.${selectedFormat}`)].filter(Boolean).join("\n\n"); const generated = await runAdmittedStudioGeneration({ prompt, contentLanguage: language, model: { provider: "replicate", model: modelId!, version: modelVersion!, inputSchemaDigest: modelSchema! }, mode: "video", sourceMediaType: executionPlan.capability === "video_to_video" ? "video" : executionPlan.capability === "image_to_video" ? "image" : null, sourceAssetIds: providerSourceIds, quantity: Number(data.get("duration")), fundingMode, arabicVariety: language === "ar" ? String(data.get("arabicVariety")) as (typeof ARABIC_VARIETIES)[number] : null, rightsBasis: "owned", permittedRemix: "transform", rightsEvidenceIds: [], remixBrief: { preserve: ["accepted Brand Profile identity", "content format", "source attribution"], transform: ["composition", "motion", "wording"], avoid: ["unverified claims", "unlicensed marks"] }, idempotencyKey: crypto.randomUUID(), signal: new AbortController().signal }); if (!generated.assetId) throw new Error("CANONICAL_MEDIA_RECEIPT_MISSING"); await productRequest("/api/product-content/generation", { kind: "media", id: saved.id, expectedRevision: saved.revision, generation: { assetId: generated.assetId, intentId: generated.intentId, operationId: generated.operationId }, idempotencyKey: crypto.randomUUID() }); router.refresh(); } catch { setError(t("error")); } finally { setBusy(false); } }
  return <div className="grid gap-6 xl:grid-cols-[260px_1fr_340px]"><aside className="rounded-3xl border bg-card p-4"><h2 className="px-2 text-sm font-semibold">{t("formatsTitle")}</h2><nav className="mt-3 space-y-1">{CONTENT_FORMATS.map((format) => <Link key={format} href={`/content?format=${format}`} className={`block rounded-xl px-3 py-2.5 text-sm ${format === selectedFormat ? "bg-amber-100 font-semibold text-amber-950" : "hover:bg-muted"}`}>{t(`formats.${format}`)}</Link>)}</nav></aside>
    <form ref={formRef} onSubmit={save} className="space-y-5 rounded-3xl border bg-card p-6"><div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs text-amber-950">{t(`formats.${selectedFormat}`)}</span><h2 className="mt-4 text-2xl font-semibold">{selectedPiece ? t("editTitle", { revision: selectedPiece.revision }) : t("newTitle")}</h2><p className="mt-2 text-sm text-muted-foreground">{t("autosaveHelp")}</p></div><Field name="title" label={t("fields.title")} value={selectedPiece?.title ?? ""} /><label className="grid gap-2 text-sm font-medium">{t("fields.script")}<textarea dir="auto" name="script" defaultValue={String(payload?.script ?? "")} required={definition.requiredInputs.includes("script")} className="min-h-44 rounded-xl border bg-background p-3 font-normal" /></label><label className="grid gap-2 text-sm font-medium">{t("fields.prompt")}<textarea dir="auto" name="prompt" defaultValue={String(payload?.prompt ?? "")} className="min-h-24 rounded-xl border bg-background p-3 font-normal" /></label><div className="grid gap-4 sm:grid-cols-2"><Select name="language" label={t("fields.language")} value={String(payload?.contentLanguage ?? "ar")} options={["ar", "en"]} optionLabel={(v) => t(`languages.${v}`)} /><Select name="arabicVariety" label={t("fields.variety")} value={String(payload?.arabicVariety ?? "")} options={["", ...ARABIC_VARIETIES]} optionLabel={(v) => v ? t(`varieties.${v}`) : t("varieties.unavailable")} /><input type="hidden" name="aspectRatio" value="9:16" /><label className="grid gap-2 text-sm font-medium">{t("fields.duration")}<input name="duration" type="number" min={definition.duration[0]} max={definition.duration[1]} defaultValue={Number(payload?.durationSeconds ?? 15)} className="min-h-11 rounded-xl border bg-background px-3" /></label></div><Field name="captionStyle" label={t("fields.captions")} value={String(payload?.captionStyle ?? "brand")} /><Field name="assets" label={t("fields.assets")} value={((payload?.sourceAssetIds as string[]) ?? []).join(", ")} required={executionPlan.sourceTypes.length > 0} /><Field name="personaId" label={t("inputs.persona")} value={String(payload?.personaId ?? "")} required={executionPlan.requiresPersona} /><div className="rounded-xl bg-muted p-4 text-sm"><p className="font-semibold">{t("requirements")}</p><p className="mt-2 text-muted-foreground">{definition.requiredInputs.map((input) => t(`inputs.${input}`)).join(" · ")} · {t("renderProof")}</p></div><button disabled={busy} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-amber-300 font-semibold text-stone-950 disabled:opacity-50">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}{t("save")}</button>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</form>
    <aside className="space-y-5"><div className="rounded-3xl bg-stone-950 p-5 text-white"><div className="mx-auto aspect-[9/16] max-h-[430px] rounded-[1.6rem] border border-white/10 bg-[linear-gradient(160deg,#44403c,#0c0a09)] p-5"><span className="text-xs text-amber-300">{t("preview")}</span><p dir="auto" className="mt-12 text-2xl font-semibold">{String(payload?.script || t("previewEmpty"))}</p></div><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={() => setGenerationMode("copy")} className={`min-h-9 rounded-lg text-xs ${generationMode === "copy" ? "bg-white text-stone-950" : "border border-white/20"}`}>{t("generate")}</button><button type="button" onClick={() => setGenerationMode("media")} className={`min-h-9 rounded-lg text-xs ${generationMode === "media" ? "bg-amber-300 text-stone-950" : "border border-white/20"}`}>{t("renderProof")}</button></div><div className="mt-3">{generationMode === "copy" ? <ModelSelect mode="copy" id="content-copy-model" /> : <ModelSelect mode="video" id="content-media-model" requiredCapability={executionPlan.capability ?? undefined} />}</div><button type="button" disabled={busy} onClick={generationMode === "copy" ? generateScript : generateMedia} className="mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-white text-sm font-semibold text-stone-950 disabled:opacity-50">{generationMode === "copy" ? <WandSparkles className="size-4" /> : <Film className="size-4" />}{generationMode === "copy" ? t("generate") : t("renderProof")}</button>{selectedPiece && ((payload?.candidateArtifactIds as string[]) ?? []).map((assetId) => <div key={assetId} className="mt-3 grid grid-cols-2 gap-2"><Link href={`/editor/${encodeURIComponent(assetId)}`} className="inline-flex min-h-10 items-center justify-center rounded-lg border border-white/20 text-xs"><Film className="me-2 size-3" />{t("preview")}</Link><Link href="/social/compose" className="inline-flex min-h-10 items-center justify-center rounded-lg border border-white/20 text-xs"><Send className="me-2 size-3" />{t("save")}</Link></div>)}</div><div className="rounded-3xl border bg-card p-5"><h2 className="flex items-center gap-2 font-semibold"><FileClock className="size-4" />{t("pieces")}</h2><div className="mt-3 space-y-2">{pieces.slice(0, 8).map((piece) => <Link key={piece.id} href={`/content?format=${String(piece.payload.format)}&piece=${piece.id}`} className="flex items-center justify-between rounded-xl bg-muted p-3 text-sm"><span className="truncate">{piece.title}</span><span className="ms-2 flex shrink-0 items-center gap-1 text-xs text-muted-foreground"><Clock className="size-3" />v{piece.revision}</span></Link>)}</div></div></aside></div>;
}
function Field({ name, label, value, required = true }: { name: string; label: string; value: string; required?: boolean }) { return <label className="grid gap-2 text-sm font-medium">{label}<input dir="auto" name={name} defaultValue={value} required={required} className="min-h-11 rounded-xl border bg-background px-3 font-normal" /></label>; }
function Select({ name, label, value, options, optionLabel }: { name: string; label: string; value: string; options: string[]; optionLabel: (value: string) => string }) { return <label className="grid gap-2 text-sm font-medium">{label}<select name={name} defaultValue={value} className="min-h-11 rounded-xl border bg-background px-3">{options.map((option) => <option key={option} value={option}>{optionLabel(option)}</option>)}</select></label>; }
