CREATE TABLE "generation_rights_erasure_preflights" (
  "workspace_id" text NOT NULL, "closure_id" text NOT NULL, "lease_id" text NOT NULL, "lease_fence" integer NOT NULL,
  "evidence_row_count" bigint NOT NULL, "snapshot_row_count" bigint NOT NULL, "retention_policy_revision" integer NOT NULL,
  "retention_rule_digest" text NOT NULL, "rights_set_mac" text NOT NULL, "signing_key_id" text NOT NULL,
  "audit_sequence" integer NOT NULL, "audit_event_id" text NOT NULL, "evaluated_at" timestamptz NOT NULL,
  "preflight_digest" text NOT NULL, "preflight_mac" text NOT NULL,
  CONSTRAINT "generation_rights_erasure_preflights_pk" PRIMARY KEY ("workspace_id","closure_id","lease_id","lease_fence"),
  CONSTRAINT "generation_rights_erasure_preflights_values_check" CHECK (
    "lease_id" ~ '^lease_[A-Za-z0-9]+$' AND "lease_fence">0 AND "evidence_row_count">=0 AND "snapshot_row_count">=0
    AND "retention_policy_revision">0 AND "retention_rule_digest" ~ '^sha256:[a-f0-9]{64}$'
    AND "rights_set_mac" ~ '^hmac-sha256:[a-f0-9]{64}$' AND "signing_key_id" ~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}$'
    AND "audit_sequence">0 AND "audit_event_id" ~ '^rights_preflight_[a-f0-9]{32}$'
    AND "preflight_digest" ~ '^sha256:[a-f0-9]{64}$' AND "preflight_mac" ~ '^hmac-sha256:[a-f0-9]{64}$')
);
CREATE TABLE "generation_rights_erasure_v2_bindings" (
  "workspace_id" text PRIMARY KEY, "closure_id" text NOT NULL, "preflight_digest" text NOT NULL,
  "tombstone_digest" text NOT NULL, "signing_key_id" text NOT NULL, "binding_mac" text NOT NULL,
  CONSTRAINT "generation_rights_erasure_v2_bindings_values_check" CHECK (
    "preflight_digest" ~ '^sha256:[a-f0-9]{64}$' AND "tombstone_digest" ~ '^sha256:[a-f0-9]{64}$'
    AND "signing_key_id" ~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}$' AND "binding_mac" ~ '^hmac-sha256:[a-f0-9]{64}$')
);
CREATE TABLE "generation_rights_retention_decisions" (
  "workspace_id" text NOT NULL, "closure_id" text NOT NULL, "lease_id" text NOT NULL, "lease_fence" integer NOT NULL,
  "attempt_digest" text NOT NULL, "retention_policy_revision" integer NOT NULL, "retention_revision_digest" text NOT NULL,
  "blocking_hold_ids" text[] NOT NULL, "signing_key_id" text NOT NULL, "decided_at" timestamptz NOT NULL,
  "decision_digest" text NOT NULL, "decision_mac" text NOT NULL,
  CONSTRAINT "generation_rights_retention_decisions_pk" PRIMARY KEY ("workspace_id","closure_id","lease_id","lease_fence"),
  CONSTRAINT "generation_rights_retention_decisions_values_check" CHECK (
    "lease_id" ~ '^lease_[A-Za-z0-9]+$' AND "lease_fence">0 AND "attempt_digest" ~ '^sha256:[a-f0-9]{64}$'
    AND "retention_policy_revision">0 AND "retention_revision_digest" ~ '^sha256:[a-f0-9]{64}$'
    AND pg_catalog.cardinality("blocking_hold_ids")>0 AND pg_catalog.array_position("blocking_hold_ids",NULL) IS NULL
    AND "signing_key_id" ~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}$'
    AND "decision_digest" ~ '^sha256:[a-f0-9]{64}$' AND "decision_mac" ~ '^hmac-sha256:[a-f0-9]{64}$')
);
CREATE TRIGGER "generation_rights_erasure_preflights_append_only" BEFORE UPDATE OR DELETE ON "generation_rights_erasure_preflights"
FOR EACH ROW EXECUTE FUNCTION public.prevent_generation_rights_erasure_proof_mutation();
CREATE TRIGGER "generation_rights_erasure_v2_bindings_append_only" BEFORE UPDATE OR DELETE ON "generation_rights_erasure_v2_bindings"
FOR EACH ROW EXECUTE FUNCTION public.prevent_generation_rights_erasure_proof_mutation();
CREATE TRIGGER "generation_rights_retention_decisions_append_only" BEFORE UPDATE OR DELETE ON "generation_rights_retention_decisions"
FOR EACH ROW EXECUTE FUNCTION public.prevent_generation_rights_erasure_proof_mutation();
-- An eligible preflight is the irreversible legal cutover for this evidence
-- set. Governance mutations use the same advisory lock, and direct SQL is
-- guarded here, so no later hold/policy change can race dependent deletion.
CREATE FUNCTION public.guard_generation_rights_cutover_governance_mutation() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $guard$
DECLARE v_workspace_id text:=CASE WHEN TG_OP='DELETE' THEN OLD."workspace_id" ELSE NEW."workspace_id" END; v_kind text:=CASE WHEN TG_OP='DELETE' THEN OLD."kind" ELSE NEW."kind" END;
BEGIN
  IF TG_OP='UPDATE' AND (OLD."workspace_id" IS DISTINCT FROM NEW."workspace_id" OR OLD."kind" IS DISTINCT FROM NEW."kind") THEN RAISE EXCEPTION 'governance resource Workspace and kind are immutable'; END IF;
  IF v_kind NOT IN ('retention_policy','retention_hold') THEN IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('workspace-governance:'||v_workspace_id,0));
  IF EXISTS (SELECT 1 FROM public."generation_rights_erasure_preflights" WHERE "workspace_id"=v_workspace_id)
    AND NOT EXISTS (SELECT 1 FROM public."generation_rights_erasure_tombstones" WHERE "workspace_id"=v_workspace_id) THEN
    RAISE EXCEPTION 'generation rights erasure legal cutover blocks retention mutation';
  END IF;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END; $guard$;
CREATE TRIGGER "workspace_governance_generation_rights_cutover_guard" BEFORE INSERT OR UPDATE OR DELETE ON "workspace_governance_resources"
FOR EACH ROW EXECUTE FUNCTION public.guard_generation_rights_cutover_governance_mutation();
--> statement-breakpoint
CREATE FUNCTION public.tasmeemai_try_canonical_timestamptz(value text) RETURNS timestamptz
LANGUAGE plpgsql STABLE STRICT SET search_path=pg_catalog,pg_temp AS $canonical_timestamp$
DECLARE parsed timestamptz;
BEGIN
  IF value !~ '^[0-9]{4}-(0[1-9]|1[0-2])-([0-2][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9][.][0-9]{3}Z$' THEN RETURN NULL; END IF;
  parsed:=value::timestamptz;
  IF NOT pg_catalog.isfinite(parsed) OR pg_catalog.to_char(parsed AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') IS DISTINCT FROM value THEN RETURN NULL; END IF;
  RETURN parsed;
EXCEPTION WHEN OTHERS THEN RETURN NULL;
END; $canonical_timestamp$;
--> statement-breakpoint
CREATE FUNCTION public.preflight_closed_workspace_generation_rights(p_workspace_id text,p_closure_id text,p_lease_id text,p_lease_fence integer)
RETURNS TABLE (outcome text,preflight_digest text,evidence_row_count bigint,snapshot_row_count bigint,retention_policy_revision integer,retention_revision jsonb,signing_key_id text,audit_sequence integer,audit_event_id text,blocking_hold_ids text[],eligible_at timestamptz,evaluated_at timestamptz)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $preflight$
DECLARE
  v_now timestamptz; v_key text:=pg_catalog.current_setting('app.generation_rights_erasure_hmac_key',true); v_key_id text:=pg_catalog.current_setting('app.generation_rights_erasure_hmac_key_id',true);
  v_closure record; v_policy record; v_revision jsonb; v_rule jsonb; v_count integer; v_duration integer; v_recoverable integer; v_floor integer; v_latest timestamptz; v_eligible timestamptz; v_blocking_hold_ids text[];
  v_evidence bigint; v_snapshots bigint; v_rights_mac text; v_rule_digest text; v_revision_digest text; v_sequence integer; v_event_id text; v_receipt_key text; v_unsigned jsonb; v_digest text; v_mac text; v_expected_audit jsonb; v_expected_result jsonb; v_attempt public."generation_rights_erasure_attempts"%ROWTYPE; v_existing public."generation_rights_erasure_preflights"%ROWTYPE; v_binding public."generation_rights_erasure_v2_bindings"%ROWTYPE; v_decision public."generation_rights_retention_decisions"%ROWTYPE; v_tombstone public."generation_rights_erasure_tombstones"%ROWTYPE; v_erasure record;
BEGIN
  IF p_workspace_id IS NULL OR p_workspace_id !~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}$' OR p_closure_id IS NULL OR p_closure_id !~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}$' OR p_lease_id IS NULL OR p_lease_id !~ '^lease_[A-Za-z0-9]+$' OR p_lease_fence IS NULL OR p_lease_fence<1 THEN RAISE EXCEPTION 'invalid generation rights preflight identity'; END IF;
  IF v_key IS NULL OR pg_catalog.octet_length(v_key)<32 OR v_key_id IS NULL OR v_key_id !~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}$' THEN RAISE EXCEPTION 'generation rights erasure signing authority unavailable'; END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('workspace-governance:'||p_workspace_id,0));
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('workspace-audit:'||p_workspace_id,0));
  v_now:=pg_catalog.clock_timestamp();
  SELECT "status","body" INTO v_closure FROM public."workspace_governance_resources" WHERE "workspace_id"=p_workspace_id AND "kind"='workspace_closure' AND "id"=p_closure_id FOR UPDATE;
  IF NOT FOUND OR v_closure."status" IS DISTINCT FROM 'erasure_running' OR v_closure."body"->>'erasureScheduled' IS DISTINCT FROM 'true' OR v_closure."body"->'lease'->>'id' IS DISTINCT FROM p_lease_id OR public.tasmeemai_try_positive_integer(v_closure."body"->'lease'->>'fence') IS DISTINCT FROM p_lease_fence OR public.tasmeemai_try_canonical_timestamptz(v_closure."body"->'lease'->>'expiresAt') IS NULL OR public.tasmeemai_try_canonical_timestamptz(v_closure."body"->'lease'->>'expiresAt')<=v_now THEN RAISE EXCEPTION 'current fenced workspace closure lease required'; END IF;
  SELECT * INTO v_binding FROM public."generation_rights_erasure_v2_bindings" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id;
  IF FOUND THEN
    SELECT * INTO v_existing FROM public."generation_rights_erasure_preflights" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "preflight_digest"=v_binding."preflight_digest";
    IF NOT FOUND OR v_binding."signing_key_id"<>v_key_id OR v_existing."signing_key_id"<>v_key_id OR v_binding."binding_mac" IS DISTINCT FROM 'hmac-sha256:'||pg_catalog.encode(public.tasmeemai_pgcrypto_hmac_sha256(pg_catalog.convert_to('generation-rights-erasure-v2-binding/v1:'||pg_catalog.jsonb_build_object('workspaceId',p_workspace_id,'closureId',p_closure_id,'preflightDigest',v_binding."preflight_digest",'tombstoneDigest',v_binding."tombstone_digest",'signingKeyId',v_binding."signing_key_id")::text,'UTF8'),pg_catalog.convert_to(v_key,'UTF8')),'hex') OR NOT EXISTS (SELECT 1 FROM public."generation_rights_erasure_tombstones" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "tombstone_digest"=v_binding."tombstone_digest") THEN RAISE EXCEPTION 'generation rights completed preflight binding invalid'; END IF;
    v_unsigned:=pg_catalog.jsonb_build_object('schema','generation-rights-erasure-preflight/v1','workspaceId',p_workspace_id,'closureId',p_closure_id,'leaseId',v_existing."lease_id",'leaseFence',v_existing."lease_fence",'evidenceRowCount',v_existing."evidence_row_count",'snapshotRowCount',v_existing."snapshot_row_count",'retentionPolicyRevision',v_existing."retention_policy_revision",'retentionRuleDigest',v_existing."retention_rule_digest",'rightsSetMac',v_existing."rights_set_mac",'signingKeyId',v_existing."signing_key_id",'auditSequence',v_existing."audit_sequence",'auditEventId',v_existing."audit_event_id",'evaluatedAt',pg_catalog.to_char(v_existing."evaluated_at" AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
    v_digest:='sha256:'||pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(v_unsigned::text,'UTF8')),'hex'); v_mac:='hmac-sha256:'||pg_catalog.encode(public.tasmeemai_pgcrypto_hmac_sha256(pg_catalog.convert_to('generation-rights-erasure-preflight-mac/v1:'||v_digest,'UTF8'),pg_catalog.convert_to(v_key,'UTF8')),'hex');
    v_receipt_key:='rights-preflight-'||pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(v_existing."closure_id"||':'||v_existing."lease_id",'UTF8')),'hex'),1,24)||'-'||v_existing."lease_fence"::text;
    v_expected_result:=pg_catalog.jsonb_build_object('schema','generation-rights-erasure-preflight-result/v1','closureId',p_closure_id,'preflightDigest',v_digest,'outcome','eligible');
    v_expected_audit:=pg_catalog.jsonb_build_object('schema','workspace-audit-event/v1','id',v_existing."audit_event_id",'workspaceId',p_workspace_id,'sequence',v_existing."audit_sequence",'actor',pg_catalog.jsonb_build_object('kind','system','id','tasmeemai:workspace-closure-worker@1'),'capability','workspace_closures.preflight_generation_rights@1','action','preflight_generation_rights_erasure','resource',pg_catalog.jsonb_build_object('kind','workspace_closure','id',p_closure_id),'outcome','accepted','redactedDetails',pg_catalog.jsonb_build_object('preflightDigest',v_digest,'signingKeyId',v_existing."signing_key_id"),'occurredAt',pg_catalog.to_char(v_existing."evaluated_at" AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
    IF v_existing."preflight_digest"<>v_digest OR v_existing."preflight_mac"<>v_mac OR NOT EXISTS (SELECT 1 FROM public."workspace_audit_trail_events" WHERE "workspace_id"=p_workspace_id AND "sequence"=v_existing."audit_sequence" AND "id"=v_existing."audit_event_id" AND "event"=v_expected_audit AND "occurred_at"=v_existing."evaluated_at") OR NOT EXISTS (SELECT 1 FROM public."workspace_governance_mutation_receipts" WHERE "workspace_id"=p_workspace_id AND "capability"='workspace_closures.preflight_generation_rights@1' AND "idempotency_key"=v_receipt_key AND "request_digest"=v_digest AND "actor_identity" IS NULL AND "auth_context_digest" IS NULL AND "result"=v_expected_result AND "created_at"=v_existing."evaluated_at") THEN RAISE EXCEPTION 'generation rights completed preflight proof invalid'; END IF;
    RETURN QUERY SELECT 'eligible',v_existing."preflight_digest",v_existing."evidence_row_count",v_existing."snapshot_row_count",v_existing."retention_policy_revision",NULL::jsonb,v_existing."signing_key_id",v_existing."audit_sequence",v_existing."audit_event_id",ARRAY[]::text[],NULL::timestamptz,v_existing."evaluated_at"; RETURN;
  END IF;
  -- Upgrade/lost-response recovery: validate the complete 0114 proof through
  -- its own replay path, then adopt its original nonzero counts and manifest
  -- into a new lease-bound v2 preflight. Never infer an empty erased set.
  SELECT * INTO v_tombstone FROM public."generation_rights_erasure_tombstones" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id;
  IF FOUND THEN
    SELECT * INTO v_erasure FROM public.erase_closed_workspace_generation_rights(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence);
    IF v_erasure.outcome IS DISTINCT FROM 'replayed' OR v_erasure.tombstone_digest IS DISTINCT FROM v_tombstone."tombstone_digest" THEN RAISE EXCEPTION 'legacy generation rights tombstone adoption failed'; END IF;
    v_evidence:=v_tombstone."evidence_row_count"; v_snapshots:=v_tombstone."snapshot_row_count"; v_rule_digest:=v_tombstone."retention_rule_digest"; v_rights_mac:=v_tombstone."erasure_manifest_mac";
    SELECT * INTO v_existing FROM public."generation_rights_erasure_preflights" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence;
    IF FOUND THEN
      v_unsigned:=pg_catalog.jsonb_build_object('schema','generation-rights-erasure-preflight/v1','workspaceId',p_workspace_id,'closureId',p_closure_id,'leaseId',p_lease_id,'leaseFence',p_lease_fence,'evidenceRowCount',v_existing."evidence_row_count",'snapshotRowCount',v_existing."snapshot_row_count",'retentionPolicyRevision',v_existing."retention_policy_revision",'retentionRuleDigest',v_existing."retention_rule_digest",'rightsSetMac',v_existing."rights_set_mac",'signingKeyId',v_existing."signing_key_id",'auditSequence',v_existing."audit_sequence",'auditEventId',v_existing."audit_event_id",'evaluatedAt',pg_catalog.to_char(v_existing."evaluated_at" AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
      v_digest:='sha256:'||pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(v_unsigned::text,'UTF8')),'hex'); v_mac:='hmac-sha256:'||pg_catalog.encode(public.tasmeemai_pgcrypto_hmac_sha256(pg_catalog.convert_to('generation-rights-erasure-preflight-mac/v1:'||v_digest,'UTF8'),pg_catalog.convert_to(v_key,'UTF8')),'hex');
      v_receipt_key:='rights-preflight-'||pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(p_closure_id||':'||p_lease_id,'UTF8')),'hex'),1,24)||'-'||p_lease_fence::text;
      v_expected_result:=pg_catalog.jsonb_build_object('schema','generation-rights-erasure-preflight-result/v1','closureId',p_closure_id,'preflightDigest',v_digest,'outcome','eligible');
      v_expected_audit:=pg_catalog.jsonb_build_object('schema','workspace-audit-event/v1','id',v_existing."audit_event_id",'workspaceId',p_workspace_id,'sequence',v_existing."audit_sequence",'actor',pg_catalog.jsonb_build_object('kind','system','id','tasmeemai:workspace-closure-worker@1'),'capability','workspace_closures.preflight_generation_rights@1','action','preflight_generation_rights_erasure','resource',pg_catalog.jsonb_build_object('kind','workspace_closure','id',p_closure_id),'outcome','accepted','redactedDetails',pg_catalog.jsonb_build_object('preflightDigest',v_digest,'signingKeyId',v_existing."signing_key_id"),'occurredAt',pg_catalog.to_char(v_existing."evaluated_at" AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
      IF v_existing."evidence_row_count"<>v_evidence OR v_existing."snapshot_row_count"<>v_snapshots OR v_existing."retention_policy_revision"<>v_tombstone."retention_policy_revision" OR v_existing."retention_rule_digest"<>v_rule_digest OR v_existing."rights_set_mac"<>v_rights_mac OR v_existing."signing_key_id"<>v_tombstone."signing_key_id" OR v_existing."preflight_digest"<>v_digest OR v_existing."preflight_mac"<>v_mac OR NOT EXISTS (SELECT 1 FROM public."workspace_audit_trail_events" WHERE "workspace_id"=p_workspace_id AND "sequence"=v_existing."audit_sequence" AND "id"=v_existing."audit_event_id" AND "event"=v_expected_audit AND "occurred_at"=v_existing."evaluated_at") OR NOT EXISTS (SELECT 1 FROM public."workspace_governance_mutation_receipts" WHERE "workspace_id"=p_workspace_id AND "capability"='workspace_closures.preflight_generation_rights@1' AND "idempotency_key"=v_receipt_key AND "request_digest"=v_digest AND "actor_identity" IS NULL AND "auth_context_digest" IS NULL AND "result"=v_expected_result AND "created_at"=v_existing."evaluated_at") THEN RAISE EXCEPTION 'legacy generation rights preflight replay invalid'; END IF;
      RETURN QUERY SELECT 'eligible',v_existing."preflight_digest",v_existing."evidence_row_count",v_existing."snapshot_row_count",v_existing."retention_policy_revision",NULL::jsonb,v_existing."signing_key_id",v_existing."audit_sequence",v_existing."audit_event_id",ARRAY[]::text[],NULL::timestamptz,v_existing."evaluated_at"; RETURN;
    END IF;
    SELECT coalesce(pg_catalog.max("sequence"),0)+1 INTO v_sequence FROM public."workspace_audit_trail_events" WHERE "workspace_id"=p_workspace_id;
    v_event_id:='rights_preflight_'||pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(p_workspace_id||':'||p_closure_id||':'||p_lease_id||':'||p_lease_fence::text,'UTF8')),'hex'),1,32);
    v_unsigned:=pg_catalog.jsonb_build_object('schema','generation-rights-erasure-preflight/v1','workspaceId',p_workspace_id,'closureId',p_closure_id,'leaseId',p_lease_id,'leaseFence',p_lease_fence,'evidenceRowCount',v_evidence,'snapshotRowCount',v_snapshots,'retentionPolicyRevision',v_tombstone."retention_policy_revision",'retentionRuleDigest',v_rule_digest,'rightsSetMac',v_rights_mac,'signingKeyId',v_tombstone."signing_key_id",'auditSequence',v_sequence,'auditEventId',v_event_id,'evaluatedAt',pg_catalog.to_char(v_now AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
    v_digest:='sha256:'||pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(v_unsigned::text,'UTF8')),'hex'); v_mac:='hmac-sha256:'||pg_catalog.encode(public.tasmeemai_pgcrypto_hmac_sha256(pg_catalog.convert_to('generation-rights-erasure-preflight-mac/v1:'||v_digest,'UTF8'),pg_catalog.convert_to(v_key,'UTF8')),'hex');
    INSERT INTO public."generation_rights_erasure_preflights" VALUES (p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,v_evidence,v_snapshots,v_tombstone."retention_policy_revision",v_rule_digest,v_rights_mac,v_tombstone."signing_key_id",v_sequence,v_event_id,v_now,v_digest,v_mac);
    INSERT INTO public."workspace_governance_mutation_receipts" ("workspace_id","capability","idempotency_key","request_digest","actor_identity","auth_context_digest","result","created_at") VALUES (p_workspace_id,'workspace_closures.preflight_generation_rights@1','rights-preflight-'||pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(p_closure_id||':'||p_lease_id,'UTF8')),'hex'),1,24)||'-'||p_lease_fence::text,v_digest,NULL,NULL,pg_catalog.jsonb_build_object('schema','generation-rights-erasure-preflight-result/v1','closureId',p_closure_id,'preflightDigest',v_digest,'outcome','eligible'),v_now);
    INSERT INTO public."workspace_audit_trail_events" ("workspace_id","sequence","id","event","occurred_at") VALUES (p_workspace_id,v_sequence,v_event_id,pg_catalog.jsonb_build_object('schema','workspace-audit-event/v1','id',v_event_id,'workspaceId',p_workspace_id,'sequence',v_sequence,'actor',pg_catalog.jsonb_build_object('kind','system','id','tasmeemai:workspace-closure-worker@1'),'capability','workspace_closures.preflight_generation_rights@1','action','preflight_generation_rights_erasure','resource',pg_catalog.jsonb_build_object('kind','workspace_closure','id',p_closure_id),'outcome','accepted','redactedDetails',pg_catalog.jsonb_build_object('preflightDigest',v_digest,'signingKeyId',v_tombstone."signing_key_id"),'occurredAt',pg_catalog.to_char(v_now AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')),v_now);
    RETURN QUERY SELECT 'eligible',v_digest,v_evidence,v_snapshots,v_tombstone."retention_policy_revision",NULL::jsonb,v_tombstone."signing_key_id",v_sequence,v_event_id,ARRAY[]::text[],NULL::timestamptz,v_now; RETURN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public."workspaces" WHERE "id"=p_workspace_id AND "deleted_at" IS NULL FOR SHARE) THEN RAISE EXCEPTION 'open canonical workspace required during closure erasure'; END IF;
  IF pg_catalog.jsonb_typeof(v_closure."body"->'accessRevocationEvidence') IS DISTINCT FROM 'object' OR v_closure."body"->'accessRevocationEvidence'->>'schema' IS DISTINCT FROM 'workspace-access-revocation-evidence/v1' OR pg_catalog.jsonb_typeof(v_closure."body"->'accessRevocationEvidence'->'externalEffects') IS DISTINCT FROM 'array' OR EXISTS (SELECT 1 FROM pg_catalog.jsonb_array_elements(v_closure."body"->'accessRevocationEvidence'->'externalEffects') effect WHERE pg_catalog.jsonb_typeof(effect) IS DISTINCT FROM 'object' OR coalesce(effect->>'state','') NOT IN ('deleted','not_found') OR coalesce(effect->>'evidenceRef','')='') THEN
    PERFORM public.record_generation_rights_erasure_attempt(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,'blocked_access_revocation',NULL); SELECT * INTO v_attempt FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"='blocked_access_revocation'; RETURN QUERY SELECT 'blocked_access_revocation',v_attempt."attempt_digest",0::bigint,0::bigint,NULL::integer,NULL::jsonb,v_attempt."signing_key_id",v_attempt."audit_sequence",v_attempt."audit_event_id",ARRAY[]::text[],v_attempt."eligible_at",v_attempt."occurred_at"; RETURN; END IF;
  IF NOT EXISTS (SELECT 1 FROM public."workspace_governance_resources" WHERE "workspace_id"=p_workspace_id AND "kind"='workspace_export' AND "id"=v_closure."body"->>'exportId' AND "status"='succeeded' FOR SHARE) THEN
    PERFORM public.record_generation_rights_erasure_attempt(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,'blocked_export',NULL); SELECT * INTO v_attempt FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"='blocked_export'; RETURN QUERY SELECT 'blocked_export',v_attempt."attempt_digest",0::bigint,0::bigint,NULL::integer,NULL::jsonb,v_attempt."signing_key_id",v_attempt."audit_sequence",v_attempt."audit_event_id",ARRAY[]::text[],v_attempt."eligible_at",v_attempt."occurred_at"; RETURN; END IF;
  IF EXISTS (SELECT 1 FROM public."workspace_governance_resources" WHERE "workspace_id"=p_workspace_id AND "kind"='deletion_receipt' AND "body"->>'closureId'=p_closure_id AND "status" NOT IN ('completed','completed_hold') FOR SHARE) THEN
    PERFORM public.record_generation_rights_erasure_attempt(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,'blocked_deletion_receipts',NULL); SELECT * INTO v_attempt FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"='blocked_deletion_receipts'; RETURN QUERY SELECT 'blocked_deletion_receipts',v_attempt."attempt_digest",0::bigint,0::bigint,NULL::integer,NULL::jsonb,v_attempt."signing_key_id",v_attempt."audit_sequence",v_attempt."audit_event_id",ARRAY[]::text[],v_attempt."eligible_at",v_attempt."occurred_at"; RETURN; END IF;
  SELECT "body","status" INTO v_policy FROM public."workspace_governance_resources" WHERE "workspace_id"=p_workspace_id AND "kind"='retention_policy' AND "id"='active' FOR SHARE;
  IF NOT FOUND OR v_policy."status" IS DISTINCT FROM 'active' OR pg_catalog.jsonb_typeof(v_policy."body"->'revisions') IS DISTINCT FROM 'array' OR pg_catalog.jsonb_typeof(v_policy."body"->'activeRevision') IS DISTINCT FROM 'number' OR public.tasmeemai_try_positive_integer(v_policy."body"->>'activeRevision') IS NULL THEN
    PERFORM public.record_generation_rights_erasure_attempt(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,'blocked_retention_policy',NULL); SELECT * INTO v_attempt FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"='blocked_retention_policy'; RETURN QUERY SELECT 'blocked_retention_policy',v_attempt."attempt_digest",0::bigint,0::bigint,NULL::integer,NULL::jsonb,v_attempt."signing_key_id",v_attempt."audit_sequence",v_attempt."audit_event_id",ARRAY[]::text[],v_attempt."eligible_at",v_attempt."occurred_at"; RETURN; END IF;
  SELECT pg_catalog.count(*) INTO v_count FROM pg_catalog.jsonb_array_elements(v_policy."body"->'revisions') revision WHERE revision->>'revision'=v_policy."body"->>'activeRevision';
  SELECT revision INTO v_revision FROM pg_catalog.jsonb_array_elements(v_policy."body"->'revisions') revision WHERE revision->>'revision'=v_policy."body"->>'activeRevision' LIMIT 1;
  IF v_count<>1 OR pg_catalog.jsonb_typeof(v_revision->'revision') IS DISTINCT FROM 'number' OR v_revision->>'schema' IS DISTINCT FROM 'retention-policy-revision/v2' OR v_revision->>'legalFloorSource' IS DISTINCT FROM 'deployment_trusted/v2' OR pg_catalog.jsonb_typeof(v_revision->'rules') IS DISTINCT FROM 'array' OR public.tasmeemai_try_canonical_timestamptz(v_revision->>'createdAt') IS NULL THEN
    PERFORM public.record_generation_rights_erasure_attempt(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,'blocked_retention_policy',NULL); SELECT * INTO v_attempt FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"='blocked_retention_policy'; RETURN QUERY SELECT 'blocked_retention_policy',v_attempt."attempt_digest",0::bigint,0::bigint,NULL::integer,NULL::jsonb,v_attempt."signing_key_id",v_attempt."audit_sequence",v_attempt."audit_event_id",ARRAY[]::text[],v_attempt."eligible_at",v_attempt."occurred_at"; RETURN; END IF;
  SELECT pg_catalog.count(*) INTO v_count FROM pg_catalog.jsonb_array_elements(v_revision->'rules') rule WHERE rule->>'retentionClass'='generation_rights_evidence';
  SELECT rule INTO v_rule FROM pg_catalog.jsonb_array_elements(v_revision->'rules') rule WHERE rule->>'retentionClass'='generation_rights_evidence' LIMIT 1;
  IF v_count<>1 OR pg_catalog.jsonb_typeof(v_rule->'durationDays') IS DISTINCT FROM 'number' OR pg_catalog.jsonb_typeof(v_rule->'recoverableDays') IS DISTINCT FROM 'number' OR pg_catalog.jsonb_typeof(v_rule->'legalFloorDays') IS DISTINCT FROM 'number' OR public.tasmeemai_try_nonnegative_integer(v_rule->>'durationDays') IS NULL OR public.tasmeemai_try_nonnegative_integer(v_rule->>'recoverableDays') IS NULL OR public.tasmeemai_try_nonnegative_integer(v_rule->>'legalFloorDays') IS NULL THEN
    PERFORM public.record_generation_rights_erasure_attempt(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,'blocked_retention_policy',NULL); SELECT * INTO v_attempt FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"='blocked_retention_policy'; RETURN QUERY SELECT 'blocked_retention_policy',v_attempt."attempt_digest",0::bigint,0::bigint,NULL::integer,NULL::jsonb,v_attempt."signing_key_id",v_attempt."audit_sequence",v_attempt."audit_event_id",ARRAY[]::text[],v_attempt."eligible_at",v_attempt."occurred_at"; RETURN; END IF;
  v_duration:=public.tasmeemai_try_nonnegative_integer(v_rule->>'durationDays'); v_recoverable:=public.tasmeemai_try_nonnegative_integer(v_rule->>'recoverableDays'); v_floor:=public.tasmeemai_try_nonnegative_integer(v_rule->>'legalFloorDays');
  IF v_floor<>365 OR v_duration<v_floor OR v_duration>36500 OR v_recoverable>v_duration THEN
    PERFORM public.record_generation_rights_erasure_attempt(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,'blocked_retention_policy',NULL); SELECT * INTO v_attempt FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"='blocked_retention_policy'; RETURN QUERY SELECT 'blocked_retention_policy',v_attempt."attempt_digest",0::bigint,0::bigint,NULL::integer,NULL::jsonb,v_attempt."signing_key_id",v_attempt."audit_sequence",v_attempt."audit_event_id",ARRAY[]::text[],v_attempt."eligible_at",v_attempt."occurred_at"; RETURN; END IF;
  v_rule_digest:='sha256:'||pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(v_rule::text,'UTF8')),'hex');
  v_revision_digest:='sha256:'||pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(v_revision::text,'UTF8')),'hex');
  SELECT coalesce(pg_catalog.array_agg(locked_hold."id" ORDER BY locked_hold."id"),ARRAY[]::text[]) INTO v_blocking_hold_ids FROM (SELECT hold."id" FROM public."workspace_governance_resources" hold WHERE hold."workspace_id"=p_workspace_id AND hold."kind"='retention_hold' AND hold."status"='active' AND (((hold."body" ? 'expiresAt') AND hold."body"->'expiresAt' IS DISTINCT FROM 'null'::jsonb AND pg_catalog.jsonb_typeof(hold."body"->'expiresAt') IS DISTINCT FROM 'string') OR (pg_catalog.jsonb_typeof(hold."body"->'expiresAt')='string' AND public.tasmeemai_try_canonical_timestamptz(hold."body"->>'expiresAt') IS NULL) OR ((hold."body"->>'expiresAt' IS NULL OR public.tasmeemai_try_canonical_timestamptz(hold."body"->>'expiresAt')>v_now) AND (pg_catalog.jsonb_typeof(hold."body"->'retentionClasses') IS DISTINCT FROM 'array' OR hold."body"->'retentionClasses' @> '["generation_rights_evidence"]'::jsonb OR pg_catalog.jsonb_typeof(hold."body"->'scopeReview') IS DISTINCT FROM 'object' OR hold."body"->'scopeReview'->>'schema' IS DISTINCT FROM 'retention-hold-scope-review/v2' OR pg_catalog.jsonb_typeof(hold."body"->'scopeReview'->'reviewedAgainstPolicyRevision') IS DISTINCT FROM 'number' OR public.tasmeemai_try_positive_integer(hold."body"->'scopeReview'->>'reviewedAgainstPolicyRevision') IS DISTINCT FROM (v_policy."body"->>'activeRevision')::integer OR hold."body"->'scopeReview'->>'generationRightsEvidence' IS DISTINCT FROM 'not_applicable'))) FOR SHARE) locked_hold;
  IF pg_catalog.cardinality(v_blocking_hold_ids)>0 THEN
    SELECT CASE
      WHEN pg_catalog.count(*)=pg_catalog.count(public.tasmeemai_try_canonical_timestamptz(hold."body"->>'expiresAt'))
        THEN pg_catalog.max(public.tasmeemai_try_canonical_timestamptz(hold."body"->>'expiresAt'))
      ELSE NULL
    END INTO v_eligible
    FROM public."workspace_governance_resources" hold
    WHERE hold."workspace_id"=p_workspace_id AND hold."kind"='retention_hold' AND hold."id"=ANY(v_blocking_hold_ids);
    PERFORM public.record_generation_rights_erasure_attempt(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,'blocked_retention_hold',v_eligible);
    SELECT * INTO v_attempt FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"='blocked_retention_hold';
    v_unsigned:=pg_catalog.jsonb_build_object('schema','generation-rights-retention-decision/v1','workspaceId',p_workspace_id,'closureId',p_closure_id,'leaseId',p_lease_id,'leaseFence',p_lease_fence,'attemptDigest',v_attempt."attempt_digest",'retentionPolicyRevision',(v_policy."body"->>'activeRevision')::integer,'retentionRevisionDigest',v_revision_digest,'blockingHoldIds',pg_catalog.to_jsonb(v_blocking_hold_ids),'signingKeyId',v_attempt."signing_key_id",'decidedAt',pg_catalog.to_char(v_attempt."occurred_at" AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
    v_digest:='sha256:'||pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(v_unsigned::text,'UTF8')),'hex');
    v_mac:='hmac-sha256:'||pg_catalog.encode(public.tasmeemai_pgcrypto_hmac_sha256(pg_catalog.convert_to('generation-rights-retention-decision-mac/v1:'||v_digest,'UTF8'),pg_catalog.convert_to(v_key,'UTF8')),'hex');
    SELECT * INTO v_decision FROM public."generation_rights_retention_decisions" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence;
    IF FOUND THEN
      IF v_decision."attempt_digest"<>v_attempt."attempt_digest" OR v_decision."retention_policy_revision"<>(v_policy."body"->>'activeRevision')::integer OR v_decision."retention_revision_digest"<>v_revision_digest OR v_decision."blocking_hold_ids"<>v_blocking_hold_ids OR v_decision."signing_key_id"<>v_attempt."signing_key_id" OR v_decision."decided_at"<>v_attempt."occurred_at" OR v_decision."decision_digest"<>v_digest OR v_decision."decision_mac"<>v_mac THEN RAISE EXCEPTION 'generation rights retention decision replay invalid'; END IF;
    ELSE
      INSERT INTO public."generation_rights_retention_decisions" VALUES (p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,v_attempt."attempt_digest",(v_policy."body"->>'activeRevision')::integer,v_revision_digest,v_blocking_hold_ids,v_attempt."signing_key_id",v_attempt."occurred_at",v_digest,v_mac);
    END IF;
    v_receipt_key:='rights-retention-'||pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(p_closure_id||':'||p_lease_id,'UTF8')),'hex'),1,24)||'-'||p_lease_fence::text;
    v_expected_result:=pg_catalog.jsonb_build_object('schema','generation-rights-retention-decision-result/v1','closureId',p_closure_id,'leaseId',p_lease_id,'leaseFence',p_lease_fence,'decisionDigest',v_digest,'blockingHoldIds',pg_catalog.to_jsonb(v_blocking_hold_ids),'retentionPolicyRevision',(v_policy."body"->>'activeRevision')::integer,'retentionRevisionDigest',v_revision_digest);
    INSERT INTO public."workspace_governance_mutation_receipts" ("workspace_id","capability","idempotency_key","request_digest","actor_identity","auth_context_digest","result","created_at") VALUES (p_workspace_id,'workspace_closures.erase_generation_rights_attempt@1',v_receipt_key,v_digest,NULL,NULL,v_expected_result,v_attempt."occurred_at") ON CONFLICT DO NOTHING;
    IF NOT EXISTS (SELECT 1 FROM public."workspace_governance_mutation_receipts" WHERE "workspace_id"=p_workspace_id AND "capability"='workspace_closures.erase_generation_rights_attempt@1' AND "idempotency_key"=v_receipt_key AND "request_digest"=v_digest AND "actor_identity" IS NULL AND "auth_context_digest" IS NULL AND "result"=v_expected_result AND "created_at"=v_attempt."occurred_at") THEN RAISE EXCEPTION 'generation rights retention decision receipt invalid'; END IF;
    RETURN QUERY SELECT 'blocked_retention_hold',v_digest,0::bigint,0::bigint,(v_policy."body"->>'activeRevision')::integer,pg_catalog.jsonb_build_object('revision',v_revision,'digest',v_revision_digest),v_attempt."signing_key_id",v_attempt."audit_sequence",v_attempt."audit_event_id",v_blocking_hold_ids,v_attempt."eligible_at",v_attempt."occurred_at"; RETURN;
  END IF;
  IF EXISTS (SELECT 1 FROM (SELECT "created_at" FROM public."inspiration_rights_evidence" WHERE "workspace_id"=p_workspace_id UNION ALL SELECT "created_at" FROM public."inspiration_rights_snapshots" WHERE "workspace_id"=p_workspace_id) rights_rows WHERE NOT pg_catalog.isfinite(rights_rows."created_at")) THEN
    PERFORM public.record_generation_rights_erasure_attempt(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,'blocked_retention_policy',NULL); SELECT * INTO v_attempt FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"='blocked_retention_policy'; RETURN QUERY SELECT 'blocked_retention_policy',v_attempt."attempt_digest",0::bigint,0::bigint,(v_policy."body"->>'activeRevision')::integer,pg_catalog.jsonb_build_object('revision',v_revision,'digest',v_revision_digest),v_attempt."signing_key_id",v_attempt."audit_sequence",v_attempt."audit_event_id",ARRAY[]::text[],v_attempt."eligible_at",v_attempt."occurred_at"; RETURN;
  END IF;
  SELECT pg_catalog.max("created_at") INTO v_latest FROM (SELECT "created_at" FROM public."inspiration_rights_evidence" WHERE "workspace_id"=p_workspace_id UNION ALL SELECT "created_at" FROM public."inspiration_rights_snapshots" WHERE "workspace_id"=p_workspace_id) rows;
  IF v_latest IS NOT NULL THEN v_eligible:=v_latest+pg_catalog.make_interval(days=>greatest(v_duration,v_recoverable,v_floor)); IF v_eligible>v_now THEN
    PERFORM public.record_generation_rights_erasure_attempt(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,'blocked_retention_period',v_eligible); SELECT * INTO v_attempt FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"='blocked_retention_period'; RETURN QUERY SELECT 'blocked_retention_period',v_attempt."attempt_digest",0::bigint,0::bigint,(v_policy."body"->>'activeRevision')::integer,pg_catalog.jsonb_build_object('revision',v_revision,'digest',v_revision_digest),v_attempt."signing_key_id",v_attempt."audit_sequence",v_attempt."audit_event_id",ARRAY[]::text[],v_attempt."eligible_at",v_attempt."occurred_at"; RETURN; END IF; END IF;
  SELECT pg_catalog.count(*) INTO v_evidence FROM public."inspiration_rights_evidence" WHERE "workspace_id"=p_workspace_id;
  SELECT pg_catalog.count(*) INTO v_snapshots FROM public."inspiration_rights_snapshots" WHERE "workspace_id"=p_workspace_id;
  SELECT 'hmac-sha256:'||pg_catalog.encode(public.tasmeemai_pgcrypto_hmac_sha256(pg_catalog.convert_to(pg_catalog.jsonb_build_object('purpose','generation-rights-preflight-set/v1','workspaceId',p_workspace_id,'closureId',p_closure_id,'leaseId',p_lease_id,'leaseFence',p_lease_fence,'commitments',coalesce(pg_catalog.jsonb_agg(commitment ORDER BY kind,identity),'[]'::jsonb))::text,'UTF8'),pg_catalog.convert_to(v_key,'UTF8')),'hex') INTO v_rights_mac FROM (SELECT 'evidence' kind,"id" identity,pg_catalog.jsonb_build_object('kind','evidence','identity',"id",'recordDigest',"digest") commitment FROM public."inspiration_rights_evidence" WHERE "workspace_id"=p_workspace_id UNION ALL SELECT 'snapshot',"id"||':'||"revision"::text,pg_catalog.jsonb_build_object('kind','snapshot','identity',"id"||':'||"revision"::text,'recordDigest',"digest") FROM public."inspiration_rights_snapshots" WHERE "workspace_id"=p_workspace_id) c;
  SELECT * INTO v_existing FROM public."generation_rights_erasure_preflights" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence;
  IF FOUND THEN
    v_unsigned:=pg_catalog.jsonb_build_object('schema','generation-rights-erasure-preflight/v1','workspaceId',p_workspace_id,'closureId',p_closure_id,'leaseId',p_lease_id,'leaseFence',p_lease_fence,'evidenceRowCount',v_existing."evidence_row_count",'snapshotRowCount',v_existing."snapshot_row_count",'retentionPolicyRevision',v_existing."retention_policy_revision",'retentionRuleDigest',v_existing."retention_rule_digest",'rightsSetMac',v_existing."rights_set_mac",'signingKeyId',v_existing."signing_key_id",'auditSequence',v_existing."audit_sequence",'auditEventId',v_existing."audit_event_id",'evaluatedAt',pg_catalog.to_char(v_existing."evaluated_at" AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
    v_digest:='sha256:'||pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(v_unsigned::text,'UTF8')),'hex'); v_mac:='hmac-sha256:'||pg_catalog.encode(public.tasmeemai_pgcrypto_hmac_sha256(pg_catalog.convert_to('generation-rights-erasure-preflight-mac/v1:'||v_digest,'UTF8'),pg_catalog.convert_to(v_key,'UTF8')),'hex');
    v_receipt_key:='rights-preflight-'||pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(p_closure_id||':'||p_lease_id,'UTF8')),'hex'),1,24)||'-'||p_lease_fence::text;
    v_expected_result:=pg_catalog.jsonb_build_object('schema','generation-rights-erasure-preflight-result/v1','closureId',p_closure_id,'preflightDigest',v_digest,'outcome','eligible');
    v_expected_audit:=pg_catalog.jsonb_build_object('schema','workspace-audit-event/v1','id',v_existing."audit_event_id",'workspaceId',p_workspace_id,'sequence',v_existing."audit_sequence",'actor',pg_catalog.jsonb_build_object('kind','system','id','tasmeemai:workspace-closure-worker@1'),'capability','workspace_closures.preflight_generation_rights@1','action','preflight_generation_rights_erasure','resource',pg_catalog.jsonb_build_object('kind','workspace_closure','id',p_closure_id),'outcome','accepted','redactedDetails',pg_catalog.jsonb_build_object('preflightDigest',v_digest,'signingKeyId',v_existing."signing_key_id"),'occurredAt',pg_catalog.to_char(v_existing."evaluated_at" AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
    IF v_existing."signing_key_id"<>v_key_id OR v_existing."evidence_row_count"<>v_evidence OR v_existing."snapshot_row_count"<>v_snapshots OR v_existing."retention_policy_revision"<>(v_policy."body"->>'activeRevision')::integer OR v_existing."retention_rule_digest"<>v_rule_digest OR v_existing."rights_set_mac"<>v_rights_mac OR v_existing."preflight_digest"<>v_digest OR v_existing."preflight_mac"<>v_mac
      OR NOT EXISTS (SELECT 1 FROM public."workspace_audit_trail_events" WHERE "workspace_id"=p_workspace_id AND "sequence"=v_existing."audit_sequence" AND "id"=v_existing."audit_event_id" AND "event"=v_expected_audit AND "occurred_at"=v_existing."evaluated_at")
      OR NOT EXISTS (SELECT 1 FROM public."workspace_governance_mutation_receipts" WHERE "workspace_id"=p_workspace_id AND "capability"='workspace_closures.preflight_generation_rights@1' AND "idempotency_key"=v_receipt_key AND "request_digest"=v_digest AND "actor_identity" IS NULL AND "auth_context_digest" IS NULL AND "result"=v_expected_result AND "created_at"=v_existing."evaluated_at")
    THEN RAISE EXCEPTION 'generation rights preflight replay proof invalid'; END IF;
    RETURN QUERY SELECT 'eligible',v_existing."preflight_digest",v_existing."evidence_row_count",v_existing."snapshot_row_count",v_existing."retention_policy_revision",pg_catalog.jsonb_build_object('revision',v_revision,'digest',v_revision_digest),v_existing."signing_key_id",v_existing."audit_sequence",v_existing."audit_event_id",ARRAY[]::text[],NULL::timestamptz,v_existing."evaluated_at"; RETURN;
  END IF;
  SELECT coalesce(pg_catalog.max("sequence"),0)+1 INTO v_sequence FROM public."workspace_audit_trail_events" WHERE "workspace_id"=p_workspace_id;
  v_event_id:='rights_preflight_'||pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(p_workspace_id||':'||p_closure_id||':'||p_lease_id||':'||p_lease_fence::text,'UTF8')),'hex'),1,32);
  v_unsigned:=pg_catalog.jsonb_build_object('schema','generation-rights-erasure-preflight/v1','workspaceId',p_workspace_id,'closureId',p_closure_id,'leaseId',p_lease_id,'leaseFence',p_lease_fence,'evidenceRowCount',v_evidence,'snapshotRowCount',v_snapshots,'retentionPolicyRevision',(v_policy."body"->>'activeRevision')::integer,'retentionRuleDigest',v_rule_digest,'rightsSetMac',v_rights_mac,'signingKeyId',v_key_id,'auditSequence',v_sequence,'auditEventId',v_event_id,'evaluatedAt',pg_catalog.to_char(v_now AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
  v_digest:='sha256:'||pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(v_unsigned::text,'UTF8')),'hex'); v_mac:='hmac-sha256:'||pg_catalog.encode(public.tasmeemai_pgcrypto_hmac_sha256(pg_catalog.convert_to('generation-rights-erasure-preflight-mac/v1:'||v_digest,'UTF8'),pg_catalog.convert_to(v_key,'UTF8')),'hex');
  INSERT INTO public."generation_rights_erasure_preflights" VALUES (p_workspace_id,p_closure_id,p_lease_id,p_lease_fence,v_evidence,v_snapshots,(v_policy."body"->>'activeRevision')::integer,v_rule_digest,v_rights_mac,v_key_id,v_sequence,v_event_id,v_now,v_digest,v_mac);
  INSERT INTO public."workspace_governance_mutation_receipts" ("workspace_id","capability","idempotency_key","request_digest","actor_identity","auth_context_digest","result","created_at") VALUES (p_workspace_id,'workspace_closures.preflight_generation_rights@1','rights-preflight-'||pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(p_closure_id||':'||p_lease_id,'UTF8')),'hex'),1,24)||'-'||p_lease_fence::text,v_digest,NULL,NULL,pg_catalog.jsonb_build_object('schema','generation-rights-erasure-preflight-result/v1','closureId',p_closure_id,'preflightDigest',v_digest,'outcome','eligible'),v_now);
  INSERT INTO public."workspace_audit_trail_events" ("workspace_id","sequence","id","event","occurred_at") VALUES (p_workspace_id,v_sequence,v_event_id,pg_catalog.jsonb_build_object('schema','workspace-audit-event/v1','id',v_event_id,'workspaceId',p_workspace_id,'sequence',v_sequence,'actor',pg_catalog.jsonb_build_object('kind','system','id','tasmeemai:workspace-closure-worker@1'),'capability','workspace_closures.preflight_generation_rights@1','action','preflight_generation_rights_erasure','resource',pg_catalog.jsonb_build_object('kind','workspace_closure','id',p_closure_id),'outcome','accepted','redactedDetails',pg_catalog.jsonb_build_object('preflightDigest',v_digest,'signingKeyId',v_key_id),'occurredAt',pg_catalog.to_char(v_now AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')),v_now);
  RETURN QUERY SELECT 'eligible',v_digest,v_evidence,v_snapshots,(v_policy."body"->>'activeRevision')::integer,pg_catalog.jsonb_build_object('revision',v_revision,'digest',v_revision_digest),v_key_id,v_sequence,v_event_id,ARRAY[]::text[],NULL::timestamptz,v_now;
END; $preflight$;
--> statement-breakpoint
CREATE FUNCTION public.erase_closed_workspace_generation_rights_v2(p_workspace_id text,p_closure_id text,p_lease_id text,p_lease_fence integer,p_preflight_digest text)
RETURNS TABLE (schema_version text,outcome text,tombstone_digest text,evidence_row_count bigint,snapshot_row_count bigint,erased_at timestamptz,signing_key_id text,audit_sequence integer,audit_event_id text,preflight_digest text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $erase_v2$
DECLARE v_preflight record; v_erasure record; v_tombstone public."generation_rights_erasure_tombstones"%ROWTYPE; v_binding public."generation_rights_erasure_v2_bindings"%ROWTYPE; v_key text:=pg_catalog.current_setting('app.generation_rights_erasure_hmac_key',true); v_binding_mac text;
BEGIN
  SELECT * INTO v_preflight FROM public.preflight_closed_workspace_generation_rights(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence);
  IF v_preflight.outcome IS DISTINCT FROM 'eligible' OR v_preflight.preflight_digest IS DISTINCT FROM p_preflight_digest THEN
    RETURN QUERY SELECT 'generation-rights-erasure-result/v2',v_preflight.outcome,NULL::text,0::bigint,0::bigint,NULL::timestamptz,v_preflight.signing_key_id,v_preflight.audit_sequence,v_preflight.audit_event_id,v_preflight.preflight_digest; RETURN;
  END IF;
  SELECT * INTO v_erasure FROM public.erase_closed_workspace_generation_rights(p_workspace_id,p_closure_id,p_lease_id,p_lease_fence);
  IF v_erasure.outcome NOT IN ('erased','replayed') THEN RETURN QUERY SELECT 'generation-rights-erasure-result/v2',v_erasure.outcome,NULL::text,0::bigint,0::bigint,v_erasure.erased_at,v_preflight.signing_key_id,v_preflight.audit_sequence,v_preflight.audit_event_id,v_preflight.preflight_digest; RETURN; END IF;
  SELECT * INTO v_tombstone FROM public."generation_rights_erasure_tombstones" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id;
  IF NOT FOUND OR v_tombstone."tombstone_digest" IS DISTINCT FROM v_erasure.tombstone_digest THEN RAISE EXCEPTION 'generation rights v2 result binding unavailable'; END IF;
  v_binding_mac:='hmac-sha256:'||pg_catalog.encode(public.tasmeemai_pgcrypto_hmac_sha256(pg_catalog.convert_to('generation-rights-erasure-v2-binding/v1:'||pg_catalog.jsonb_build_object('workspaceId',p_workspace_id,'closureId',p_closure_id,'preflightDigest',v_preflight.preflight_digest,'tombstoneDigest',v_tombstone."tombstone_digest",'signingKeyId',v_tombstone."signing_key_id")::text,'UTF8'),pg_catalog.convert_to(v_key,'UTF8')),'hex');
  SELECT * INTO v_binding FROM public."generation_rights_erasure_v2_bindings" WHERE "workspace_id"=p_workspace_id;
  IF FOUND THEN
    IF v_binding."closure_id"<>p_closure_id OR v_binding."preflight_digest"<>v_preflight.preflight_digest OR v_binding."tombstone_digest"<>v_tombstone."tombstone_digest" OR v_binding."signing_key_id"<>v_tombstone."signing_key_id" OR v_binding."binding_mac"<>v_binding_mac THEN RAISE EXCEPTION 'generation rights v2 replay binding invalid'; END IF;
  ELSE
    INSERT INTO public."generation_rights_erasure_v2_bindings" VALUES (p_workspace_id,p_closure_id,v_preflight.preflight_digest,v_tombstone."tombstone_digest",v_tombstone."signing_key_id",v_binding_mac);
  END IF;
  RETURN QUERY SELECT 'generation-rights-erasure-result/v2',v_erasure.outcome,v_tombstone."tombstone_digest",v_tombstone."evidence_row_count",v_tombstone."snapshot_row_count",v_tombstone."erased_at",v_tombstone."signing_key_id",v_tombstone."audit_sequence",v_tombstone."audit_event_id",v_preflight.preflight_digest;
END; $erase_v2$;
--> statement-breakpoint
CREATE FUNCTION public.generation_rights_erasure_signing_key_id_v2(p_workspace_id text,p_closure_id text,p_lease_id text,p_lease_fence integer,p_outcome_code text)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $lookup$
DECLARE v_key_id text; v_count integer;
BEGIN
  IF p_workspace_id IS NULL OR p_closure_id IS NULL OR p_lease_id IS NULL OR p_lease_id !~ '^lease_[A-Za-z0-9]+$' OR p_lease_fence IS NULL OR p_lease_fence<1 THEN RAISE EXCEPTION 'invalid generation rights erasure replay identity'; END IF;
  SELECT "signing_key_id" INTO v_key_id FROM public."generation_rights_erasure_tombstones" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id; IF FOUND THEN RETURN v_key_id; END IF;
  SELECT pg_catalog.count(DISTINCT "signing_key_id"),pg_catalog.min("signing_key_id") INTO v_count,v_key_id FROM (
    SELECT "signing_key_id" FROM public."generation_rights_erasure_attempts" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence AND "outcome_code"=p_outcome_code
    UNION ALL SELECT "signing_key_id" FROM public."generation_rights_erasure_preflights" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence
    UNION ALL SELECT "signing_key_id" FROM public."generation_rights_retention_decisions" WHERE "workspace_id"=p_workspace_id AND "closure_id"=p_closure_id AND "lease_id"=p_lease_id AND "lease_fence"=p_lease_fence) keys;
  IF v_count>1 THEN RAISE EXCEPTION 'ambiguous generation rights erasure signing key'; END IF; RETURN v_key_id;
END; $lookup$;
--> statement-breakpoint
REVOKE EXECUTE ON FUNCTION public.erase_closed_workspace_generation_rights(text,text,text,integer) FROM tasmeemai_workspace_closure_worker;
REVOKE ALL ON FUNCTION public.guard_generation_rights_cutover_governance_mutation(), public.tasmeemai_try_canonical_timestamptz(text), public.preflight_closed_workspace_generation_rights(text,text,text,integer), public.erase_closed_workspace_generation_rights_v2(text,text,text,integer,text), public.generation_rights_erasure_signing_key_id_v2(text,text,text,integer,text) FROM PUBLIC;
GRANT SELECT,INSERT ON TABLE "generation_rights_erasure_preflights", "generation_rights_erasure_v2_bindings", "generation_rights_retention_decisions" TO tasmeemai_generation_rights_eraser_owner;
GRANT EXECUTE ON FUNCTION public.preflight_closed_workspace_generation_rights(text,text,text,integer), public.erase_closed_workspace_generation_rights_v2(text,text,text,integer,text), public.generation_rights_erasure_signing_key_id_v2(text,text,text,integer,text) TO tasmeemai_workspace_closure_worker;
REVOKE ALL ON TABLE "generation_rights_erasure_preflights", "generation_rights_erasure_v2_bindings", "generation_rights_retention_decisions" FROM PUBLIC, tasmeemai_workspace_closure_worker;
--> statement-breakpoint
DO $ownership$
DECLARE had_membership boolean:=pg_catalog.pg_has_role(CURRENT_USER,'tasmeemai_generation_rights_eraser_owner','MEMBER');
BEGIN
  IF EXISTS (SELECT 1 FROM pg_catalog.pg_auth_members m JOIN pg_catalog.pg_roles r ON r.oid=m.roleid WHERE r.rolname='tasmeemai_generation_rights_eraser_owner') THEN RAISE EXCEPTION 'generation rights eraser owner role must not have members'; END IF;
  IF NOT had_membership THEN GRANT tasmeemai_generation_rights_eraser_owner TO CURRENT_USER; END IF;
  GRANT CREATE ON SCHEMA public TO tasmeemai_generation_rights_eraser_owner;
  ALTER FUNCTION public.preflight_closed_workspace_generation_rights(text,text,text,integer) OWNER TO tasmeemai_generation_rights_eraser_owner;
  ALTER FUNCTION public.erase_closed_workspace_generation_rights_v2(text,text,text,integer,text) OWNER TO tasmeemai_generation_rights_eraser_owner;
  ALTER FUNCTION public.generation_rights_erasure_signing_key_id_v2(text,text,text,integer,text) OWNER TO tasmeemai_generation_rights_eraser_owner;
  ALTER FUNCTION public.guard_generation_rights_cutover_governance_mutation() OWNER TO tasmeemai_generation_rights_eraser_owner;
  ALTER FUNCTION public.tasmeemai_try_canonical_timestamptz(text) OWNER TO tasmeemai_generation_rights_eraser_owner;
  REVOKE CREATE ON SCHEMA public FROM tasmeemai_generation_rights_eraser_owner;
  IF NOT had_membership THEN REVOKE tasmeemai_generation_rights_eraser_owner FROM CURRENT_USER; END IF;
  IF EXISTS (SELECT 1 FROM pg_catalog.pg_auth_members m JOIN pg_catalog.pg_roles r ON r.oid=m.roleid WHERE r.rolname='tasmeemai_generation_rights_eraser_owner') THEN RAISE EXCEPTION 'generation rights eraser owner role retained an unexpected member'; END IF;
END;
$ownership$;
--> statement-breakpoint
DO $final_role_posture$
BEGIN
  IF pg_catalog.has_schema_privilege('tasmeemai_generation_rights_eraser_owner','public','CREATE') OR pg_catalog.has_schema_privilege('tasmeemai_workspace_closure_worker','public','CREATE') THEN RAISE EXCEPTION 'generation rights erasure roles must not create objects in public'; END IF;
END;
$final_role_posture$;
