import { and, desc, eq, sql } from "drizzle-orm";
import type { getDb } from "@/lib/db";
import { generationIntents, modelFallbackAuthorizations, modelFallbackSpendReservations, modelRoutingMutationReceipts } from "./db-schema";
import type { ModelRoutingRepository } from "./repository";
import type { FallbackAuthorization, GenerationIntent } from "./types";
import { hydrateRightsEvidence } from "./rights-evidence";
type Db = ReturnType<typeof getDb>; const date = (v: Date | string) => v instanceof Date ? v : new Date(v);
function grant(v: FallbackAuthorization): FallbackAuthorization { return { ...structuredClone(v), issuedAt: date(v.issuedAt), expiresAt: date(v.expiresAt), revokedAt: v.revokedAt ? date(v.revokedAt) : null }; }
function intent(v: GenerationIntent): GenerationIntent {
  const legacyRegion = { policyId: "legacy-unverified", policyVersion: 0, evidenceDigest: `sha256:${"0".repeat(64)}` as const, region: "unverified", routeId: "unverified", evidenceExpiresAt: new Date(0) };
  const legacyQualification = { id: "legacy-unverified", revision: 0, digest: `sha256:${"0".repeat(64)}` as const, expiresAt: new Date(0) };
  return { ...structuredClone(v), fundingMode: v.fundingMode ?? "byok", brand: { ...v.brand, acceptedAt: date(v.brand.acceptedAt) }, rights: { ...v.rights, evidence: (v.rights.evidence ?? []).map(hydrateRightsEvidence), sourceAssetIds: v.rights.sourceAssetIds ?? [] }, qualification: v.qualification ? { ...v.qualification, expiresAt: date(v.qualification.expiresAt) } : legacyQualification, regionAdmission: v.regionAdmission ? { ...v.regionAdmission, evidenceExpiresAt: date(v.regionAdmission.evidenceExpiresAt) } : legacyRegion, quote: { ...v.quote, quotedAt: date(v.quote.quotedAt), expiresAt: date(v.quote.expiresAt) }, createdAt: date(v.createdAt) };
}

export class PostgresModelRoutingRepository implements ModelRoutingRepository {
  constructor(private readonly database: () => Db) {}
  private async createReceiptBound(input: { workspaceId: string; idempotencyKey: string; digest: string; resourceKind: "fallback_authorization" | "generation_intent"; resourceId: string; insert(tx: Parameters<Parameters<Db["transaction"]>[0]>[0]): Promise<void> }) {
    try { return await this.database().transaction(async (tx) => { await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`model-routing:${input.workspaceId}:${input.idempotencyKey}`}, 0))`); const [receipt] = await tx.select().from(modelRoutingMutationReceipts).where(and(eq(modelRoutingMutationReceipts.workspaceId, input.workspaceId), eq(modelRoutingMutationReceipts.idempotencyKey, input.idempotencyKey))).limit(1); if (receipt) return receipt.requestDigest === input.digest && receipt.resourceKind === input.resourceKind ? "replayed" as const : "conflict" as const; await input.insert(tx); await tx.insert(modelRoutingMutationReceipts).values({ workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: input.digest, resourceKind: input.resourceKind, resourceId: input.resourceId, createdAt: new Date() }); return "created" as const; }); } catch { return "unavailable" as const; }
  }
  createAuthorization(value: FallbackAuthorization, idempotencyKey: string, digest: string) { return this.createReceiptBound({ workspaceId: value.workspaceId, idempotencyKey, digest, resourceKind: "fallback_authorization", resourceId: value.id, insert: async (tx) => { await tx.insert(modelFallbackAuthorizations).values({ workspaceId: value.workspaceId, id: value.id, revision: value.revision, status: "active", authorization: value, sourceProvider: value.source.provider, sourceModel: value.source.model, capability: value.capability, maxTotalCostUsd: value.maxTotalCostUsd.toFixed(6), issuedByUserId: value.issuedByUserId, issuedAt: value.issuedAt, expiresAt: value.expiresAt, revokedAt: null }); } }); }
  async getAuthorization(workspaceId: string, id: string) { const [row] = await this.database().select({ value: modelFallbackAuthorizations.authorization }).from(modelFallbackAuthorizations).where(and(eq(modelFallbackAuthorizations.workspaceId, workspaceId), eq(modelFallbackAuthorizations.id, id))).limit(1); return row ? grant(row.value) : null; }
  async listAuthorizations(workspaceId: string) { const rows = await this.database().select({ value: modelFallbackAuthorizations.authorization }).from(modelFallbackAuthorizations).where(eq(modelFallbackAuthorizations.workspaceId, workspaceId)).orderBy(desc(modelFallbackAuthorizations.issuedAt)); return rows.map((r) => grant(r.value)); }
  async revokeAuthorization(input: { workspaceId: string; id: string; userId: string; at: Date }) { return this.database().transaction(async (tx) => { const [row] = await tx.select().from(modelFallbackAuthorizations).where(and(eq(modelFallbackAuthorizations.workspaceId, input.workspaceId), eq(modelFallbackAuthorizations.id, input.id))).for("update"); if (!row) return "not_found" as const; const current = grant(row.authorization); if (current.revokedAt) return current.revokedByUserId === input.userId ? "replayed" as const : "conflict" as const; const next = { ...current, revision: current.revision + 1, revokedAt: input.at, revokedByUserId: input.userId }; await tx.update(modelFallbackAuthorizations).set({ revision: next.revision, status: "revoked", authorization: next, revokedAt: input.at }).where(and(eq(modelFallbackAuthorizations.workspaceId, input.workspaceId), eq(modelFallbackAuthorizations.id, input.id))); return "revoked" as const; }); }
  createIntent(value: GenerationIntent, idempotencyKey: string, digest: string) { return this.createReceiptBound({ workspaceId: value.workspaceId, idempotencyKey, digest, resourceKind: "generation_intent", resourceId: value.id, insert: async (tx) => { await tx.insert(generationIntents).values({ workspaceId: value.workspaceId, id: value.id, intent: value, brandProfileId: value.brand.profileId, brandRevision: value.brand.revision, promptDigest: value.promptDigest, selectedProvider: value.selectedModel.provider, selectedModel: value.selectedModel.model, reservationId: value.reservationIds[0]!, rightsSnapshotId: value.rights.snapshotId, rightsSnapshotRevision: value.rights.revision, remixBriefDigest: value.remixBrief.digest, regionAdmission: value.regionAdmission, outputContract: value.outputContract, createdByUserId: value.createdByUserId, createdAt: value.createdAt }); } }); }
  async getIntent(workspaceId: string, id: string) { const [row] = await this.database().select({ value: generationIntents.intent }).from(generationIntents).where(and(eq(generationIntents.workspaceId, workspaceId), eq(generationIntents.id, id))).limit(1); return row ? intent(row.value) : null; }
  async reserveFallbackSpend(input: { workspaceId: string; authorizationId: string; intentId: string; amountUsd: number; at: Date }) {
    try {
      return await this.database().transaction(async (tx) => {
        const [existing] = await tx.select().from(modelFallbackSpendReservations).where(and(eq(modelFallbackSpendReservations.workspaceId, input.workspaceId), eq(modelFallbackSpendReservations.authorizationId, input.authorizationId), eq(modelFallbackSpendReservations.intentId, input.intentId))).for("update");
        if (existing && existing.status !== "released") return Number(existing.quotedAmountUsd) === input.amountUsd ? "replayed" as const : "unavailable" as const;
        const [authorization] = await tx.select().from(modelFallbackAuthorizations).where(and(eq(modelFallbackAuthorizations.workspaceId, input.workspaceId), eq(modelFallbackAuthorizations.id, input.authorizationId))).for("update");
        if (!authorization || authorization.status !== "active" || authorization.expiresAt <= input.at) return "unavailable" as const;
        const [{ total }] = await tx.select({ total: sql<string>`coalesce(sum(case when ${modelFallbackSpendReservations.status} = 'settled' then coalesce(${modelFallbackSpendReservations.actualAmountUsd}, ${modelFallbackSpendReservations.quotedAmountUsd}) when ${modelFallbackSpendReservations.status} in ('held','outcome_unknown') then ${modelFallbackSpendReservations.quotedAmountUsd} else 0 end), 0)` }).from(modelFallbackSpendReservations).where(and(eq(modelFallbackSpendReservations.workspaceId, input.workspaceId), eq(modelFallbackSpendReservations.authorizationId, input.authorizationId)));
        if (Number(total) + input.amountUsd > Number(authorization.maxTotalCostUsd) + Number.EPSILON) return "ceiling_exceeded" as const;
        if (existing) await tx.update(modelFallbackSpendReservations).set({ amountUsd: input.amountUsd.toFixed(6), quotedAmountUsd: input.amountUsd.toFixed(6), actualAmountUsd: null, releasedAmountUsd: "0", status: "held", releasedAt: null }).where(and(eq(modelFallbackSpendReservations.workspaceId, input.workspaceId), eq(modelFallbackSpendReservations.authorizationId, input.authorizationId), eq(modelFallbackSpendReservations.intentId, input.intentId)));
        else await tx.insert(modelFallbackSpendReservations).values({ workspaceId: input.workspaceId, authorizationId: input.authorizationId, intentId: input.intentId, amountUsd: input.amountUsd.toFixed(6), quotedAmountUsd: input.amountUsd.toFixed(6), actualAmountUsd: null, releasedAmountUsd: "0", status: "held", createdAt: input.at, releasedAt: null });
        return "reserved" as const;
      });
    } catch { return "unavailable" as const; }
  }
  async releaseFallbackSpend(input: { workspaceId: string; authorizationId: string; intentId: string; at: Date }) { await this.database().update(modelFallbackSpendReservations).set({ status: "released", actualAmountUsd: "0", releasedAmountUsd: sql`${modelFallbackSpendReservations.quotedAmountUsd}`, releasedAt: input.at }).where(and(eq(modelFallbackSpendReservations.workspaceId, input.workspaceId), eq(modelFallbackSpendReservations.authorizationId, input.authorizationId), eq(modelFallbackSpendReservations.intentId, input.intentId))); }
}
