"use client";
import { useCallback, useEffect, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { LoaderCircle } from "lucide-react";
import { getActiveWorkspaceId } from "@/lib/studio/client";
import { readCommercialSummary, type CommercialSummary } from "@/lib/commercial/summary";
import { getDirection } from "@/i18n/config";

export function BillingSettings({ canManage, canPurchase }: { canManage: boolean; canPurchase: boolean }) {
  const t = useTranslations("product.billing") as (key: string, values?: Record<string, string | number>) => string; const locale = useLocale() as "ar" | "en";
  const [data, setData] = useState<CommercialSummary | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const workspaceId = getActiveWorkspaceId(); if (!workspaceId) return; const response = await fetch("/api/studio/billing", { headers: { "x-workspace-id": workspaceId }, cache: "no-store" }); const body = await response.json() as { success: boolean; data?: unknown; code?: string }; const summary = readCommercialSummary(body.data); if (!response.ok || !summary) throw new Error(body.code ?? "REQUEST_FAILED"); setData(summary); }, []);
  useEffect(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : "REQUEST_FAILED")); }, [load]);
  async function command(body: Record<string, unknown>) { const workspaceId = getActiveWorkspaceId(); if (!workspaceId) return; setBusy(true); setError(""); try { const response = await fetch("/api/studio/billing", { method: "POST", headers: { "content-type": "application/json", "x-workspace-id": workspaceId }, body: JSON.stringify({ ...body, idempotencyKey: crypto.randomUUID() }) }); const result = await response.json() as { success: boolean; code?: string }; if (!response.ok || !result.success) throw new Error(result.code ?? "REQUEST_FAILED"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "REQUEST_FAILED"); } finally { setBusy(false); } }
  async function portal() { const workspaceId = getActiveWorkspaceId(); if (!workspaceId) return; setBusy(true); try { const response = await fetch("/api/studio/billing/portal", { method: "POST", headers: { "x-workspace-id": workspaceId } }); const result = await response.json() as { success: boolean; code?: string; portal?: { url: string } }; if (!result.portal) throw new Error(result.code ?? "MERCHANT_PORTAL_UNAVAILABLE"); window.location.assign(result.portal.url); } catch (cause) { setError(cause instanceof Error ? cause.message : "REQUEST_FAILED"); } finally { setBusy(false); } }
  async function checkout(purpose: Record<string, unknown>) { const workspaceId = getActiveWorkspaceId(); if (!workspaceId) return; setBusy(true); setError(""); try { const response = await fetch("/api/studio/billing/checkout", { method: "POST", headers: { "content-type": "application/json", "x-workspace-id": workspaceId }, body: JSON.stringify({ purpose, idempotencyKey: crypto.randomUUID() }) }); const result = await response.json() as { success: boolean; code?: string; checkout?: { url: string | null } }; if (!response.ok || !result.checkout?.url) throw new Error(result.code ?? "CHECKOUT_UNAVAILABLE"); window.location.assign(result.checkout.url); } catch (cause) { setError(cause instanceof Error ? cause.message : "REQUEST_FAILED"); } finally { setBusy(false); } }
  const date = new Intl.DateTimeFormat(locale, { dateStyle: "medium" });
  const canChoosePlan = !data?.subscription || (data.subscription.state === "active" && data.subscription.planId === "free" && data.subscription.planVersion === 1);
  const canOpenPortal = Boolean(data?.subscription?.merchantCustomerRef);
  if (!data) return <div className="p-6">{error ? <p role="alert">{t(`errors.${error}`)}</p> : <LoaderCircle className="size-5 animate-spin" aria-label={t("loading")} />}</div>;
  return <div dir={getDirection(locale)} className="space-y-8 p-5 sm:p-8"><header><h2 className="text-2xl font-semibold">{t("title")}</h2><p className="mt-2 text-sm text-muted-foreground">{t("description")}</p></header>{error && <p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{t(`errors.${error}`)}</p>}
    <section className="grid gap-4 md:grid-cols-2"><article className="rounded-2xl border p-5"><p className="text-sm text-muted-foreground">{t("subscription")}</p><p className="mt-2 text-xl font-semibold">{data.subscription ? t(`states.${data.subscription.state}`) : t("noSubscription")}</p>{data.subscription && <><p dir="ltr" className="mt-1 text-left text-sm">{data.subscription.planId} v{data.subscription.planVersion}</p><p className="mt-1 text-xs text-muted-foreground">{t("periodEnds", { date: date.format(new Date(data.subscription.currentPeriodEndsAt)) })}</p>{canManage && canOpenPortal && <button disabled={busy} onClick={() => void portal()} className="mt-4 min-h-10 rounded-lg border px-4 text-sm">{t("portal")}</button>}</>}</article><article className="rounded-2xl border p-5"><p className="text-sm text-muted-foreground">{t("credits")}</p><p className="mt-2 text-3xl font-semibold tabular-nums"><bdi>{new Intl.NumberFormat(locale).format(data.credit.availableUnits)}</bdi></p><p className="mt-1 text-xs text-muted-foreground">{t("creditBoundary")}</p></article></section>
    {canChoosePlan && <section><h3 className="font-semibold">{t("plans")}</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{data.plans.map((plan) => <article key={`${plan.planId}:${plan.version}`} className="rounded-xl border p-4"><h4 className="font-semibold">{plan.authoredName[locale]}</h4><p className="mt-1 text-sm"><bdi>{new Intl.NumberFormat(locale, { style: "currency", currency: plan.currency }).format(plan.priceMinor / 100)}</bdi> / {t(`intervals.${plan.billingInterval}`)}</p>{plan.trialDays > 0 && <p className="text-xs text-muted-foreground">{t("trialOffer", { days: plan.trialDays, credits: plan.trialCreditUnits })}</p>}{plan.planId === "free" ? <p className="mt-3 text-sm font-semibold text-muted-foreground">{t("currentPlan")}</p> : canPurchase && <div className="mt-3 flex flex-wrap gap-2">{plan.trialDays > 0 && canManage && <button disabled={busy} onClick={() => void command({ action: "start_trial", planId: plan.planId, planVersion: plan.version })} className="min-h-10 rounded-lg border px-4 text-sm">{t("startTrial")}</button>}<button disabled={busy} onClick={() => void checkout({ kind: "subscription", planId: plan.planId, planVersion: plan.version })} className="min-h-10 rounded-lg bg-amber-300 px-4 text-sm font-semibold text-stone-950">{t("subscribe")}</button></div>}</article>)}</div></section>}
    <section><h3 className="font-semibold">{t("creditPacks")}</h3><div className="mt-3 grid gap-3 md:grid-cols-3">{data.creditPacks.map((pack) => <article key={`${pack.packId}:${pack.version}`} className="rounded-xl border p-4"><h4 className="font-semibold">{pack.authoredName[locale]}</h4><p className="mt-1 text-sm"><bdi>{new Intl.NumberFormat(locale, { style: "currency", currency: pack.currency }).format((pack.priceMinor + pack.taxMinor) / 100)}</bdi></p>{canPurchase && <button disabled={busy} onClick={() => void checkout({ kind: "credit_pack", packId: pack.packId, packVersion: pack.version })} className="mt-3 min-h-10 rounded-lg bg-amber-300 px-4 text-sm font-semibold text-stone-950">{t("buyCredits", { credits: pack.creditUnits })}</button>}</article>)}</div></section>
    <section><h3 className="font-semibold">{t("buckets")}</h3><div className="mt-3 grid gap-2">{data.credit.buckets.map((bucket) => <div key={bucket.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3 text-sm"><span>{t(`bucketKinds.${bucket.kind}`)} · {bucket.expiresAt ? t("bucketExpiry", { date: date.format(new Date(bucket.expiresAt)) }) : t("noExpiry")}</span><strong><bdi>{new Intl.NumberFormat(locale).format(bucket.availableUnits)}</bdi></strong></div>)}</div>{data.credit.heldReservations.map((reservation) => <p key={reservation.id} className="mt-2 text-sm text-amber-700">{t("held", { count: reservation.maxDebitUnits, state: t(`reservationStates.${reservation.state}`) })}</p>)}</section>
    <section><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">{t("referrals")}</h3>{canManage && data.referrals.codes.length === 0 && <div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => void command({ action: "create_referral_code", rewardMode: "generation_credit" })} className="min-h-10 rounded-lg border px-3 text-sm">{t("creditReferral")}</button><button disabled={busy} onClick={() => void command({ action: "create_referral_code", rewardMode: "cash" })} className="min-h-10 rounded-lg border px-3 text-sm">{t("cashReferral")}</button></div>}</div>{data.referrals.codes.map((code) => <div key={code.id} className="mt-3 rounded-xl border p-4"><code dir="ltr" className="block overflow-wrap-anywhere text-left font-semibold">{code.code}</code><p className="mt-1 text-xs text-muted-foreground">{t(`rewardModes.${code.rewardMode}`)} · {t(`referralStates.${code.status}`)}</p></div>)}<p className="mt-3 text-xs text-muted-foreground">{t("referralBoundary")}</p></section>
  </div>;
}
