"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useLocale, useTranslations } from "next-intl";
import { LoaderCircle } from "lucide-react";
import { readCommercialSummary, type CommercialSummary } from "@/lib/commercial/summary";
import { getDirection } from "@/i18n/config";

export function BillingSettings({ workspaceId, canManage, canPurchase }: { workspaceId: string; canManage: boolean; canPurchase: boolean }) {
  const t = useTranslations("product.billing") as (key: string, values?: Record<string, string | number>) => string; const locale = useLocale() as "ar" | "en";
  const [data, setData] = useState<CommercialSummary | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/studio/billing", { headers: { "x-workspace-id": workspaceId }, cache: "no-store" }); const body = await response.json() as { success: boolean; data?: unknown; code?: string }; const summary = readCommercialSummary(body.data); if (!response.ok || !summary) throw new Error(body.code ?? "REQUEST_FAILED"); setData(summary); }, [workspaceId]);
  useEffect(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : "REQUEST_FAILED")); }, [load]);
  async function command(body: Record<string, unknown>) { setBusy(true); setError(""); try { const response = await fetch("/api/studio/billing", { method: "POST", headers: { "content-type": "application/json", "x-workspace-id": workspaceId }, body: JSON.stringify({ ...body, idempotencyKey: crypto.randomUUID() }) }); const result = await response.json() as { success: boolean; code?: string }; if (!response.ok || !result.success) throw new Error(result.code ?? "REQUEST_FAILED"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "REQUEST_FAILED"); } finally { setBusy(false); } }
  async function portal() { setBusy(true); try { const response = await fetch("/api/studio/billing/portal", { method: "POST", headers: { "x-workspace-id": workspaceId } }); const result = await response.json() as { success: boolean; code?: string; portal?: { url: string } }; if (!result.portal) throw new Error(result.code ?? "MERCHANT_PORTAL_UNAVAILABLE"); window.location.assign(result.portal.url); } catch (cause) { setError(cause instanceof Error ? cause.message : "REQUEST_FAILED"); } finally { setBusy(false); } }
  async function checkout(purpose: Record<string, unknown>) { setBusy(true); setError(""); try { const response = await fetch("/api/studio/billing/checkout", { method: "POST", headers: { "content-type": "application/json", "x-workspace-id": workspaceId }, body: JSON.stringify({ purpose, idempotencyKey: crypto.randomUUID() }) }); const result = await response.json() as { success: boolean; code?: string; checkout?: { url: string | null } }; if (!response.ok || !result.checkout?.url) throw new Error(result.code ?? "CHECKOUT_UNAVAILABLE"); window.location.assign(result.checkout.url); } catch (cause) { setError(cause instanceof Error ? cause.message : "REQUEST_FAILED"); } finally { setBusy(false); } }
  async function invoice(transactionRef: string) { setBusy(true); setError(""); try { const response = await fetch(`/api/studio/billing/invoices/${encodeURIComponent(transactionRef)}`, { method: "POST", headers: { "x-workspace-id": workspaceId } }); const result = await response.json() as { success: boolean; code?: string; invoice?: { url: string } }; if (!response.ok || !result.invoice?.url) throw new Error(result.code ?? "BILLING_DOCUMENT_UNAVAILABLE"); window.location.assign(result.invoice.url); } catch (cause) { setError(cause instanceof Error ? cause.message : "REQUEST_FAILED"); } finally { setBusy(false); } }
  const date = new Intl.DateTimeFormat(locale, { dateStyle: "medium" });
  const dateTime = new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" });
  const integer = new Intl.NumberFormat(locale, { signDisplay: "always" });
  const canChoosePlan = !data?.subscription || (data.subscription.state === "active" && data.subscription.planId === "free" && data.subscription.planVersion === 1);
  const canOpenPortal = Boolean(data?.subscription?.merchantCustomerRef);
  const errorMessage = error === "CHECKOUT_OUTCOME_UNKNOWN" ? t("checkoutOutcomeUnknown") : error.startsWith("BILLING_DOCUMENT_") ? t("billingDocumentUnavailable") : error ? t(`errors.${error}`) : "";
  if (!data) return <div className="p-6">{error ? <p role="alert">{errorMessage}</p> : <LoaderCircle className="size-5 animate-spin" aria-label={t("loading")} />}</div>;
  return <div dir={getDirection(locale)} className="space-y-8 p-5 sm:p-8"><header className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-semibold">{t("title")}</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{t("description")}</p></div><Link href="/pricing" className="inline-flex min-h-10 items-center rounded-lg border px-4 text-sm font-semibold hover:bg-muted">{t("viewPricing")}</Link></header>{error && <p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{errorMessage}</p>}
    <section className="grid gap-4 md:grid-cols-2"><article className="rounded-2xl border p-5"><p className="text-sm text-muted-foreground">{t("subscription")}</p><p className="mt-2 text-xl font-semibold">{data.subscription ? t(`states.${data.subscription.state}`) : t("noSubscription")}</p>{data.subscription && <><p dir="ltr" className="mt-1 text-start text-sm">{data.subscription.planId} v{data.subscription.planVersion}</p><p className="mt-1 text-xs text-muted-foreground">{t("periodEnds", { date: date.format(new Date(data.subscription.currentPeriodEndsAt)) })}</p>{canManage && canOpenPortal && <button disabled={busy} onClick={() => void portal()} className="mt-4 min-h-10 rounded-lg border px-4 text-sm">{t("portal")}</button>}</>}</article><article className="rounded-2xl border p-5"><p className="text-sm text-muted-foreground">{t("credits")}</p><p className="mt-2 text-3xl font-semibold tabular-nums"><bdi>{new Intl.NumberFormat(locale).format(data.credit.availableUnits)}</bdi></p><p className="mt-1 text-xs text-muted-foreground">{t("creditBoundary")}</p></article></section>
    {canChoosePlan && <section><h3 className="font-semibold">{t("plans")}</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{data.plans.map((plan) => <article key={`${plan.planId}:${plan.version}`} className="rounded-xl border p-4"><h4 className="font-semibold">{plan.authoredName[locale]}</h4><p className="mt-1 text-sm"><bdi>{new Intl.NumberFormat(locale, { style: "currency", currency: plan.currency }).format(plan.priceMinor / 100)}</bdi> / {t(`intervals.${plan.billingInterval}`)}</p>{plan.trialDays > 0 && <p className="text-xs text-muted-foreground">{t("trialOffer", { days: plan.trialDays, credits: plan.trialCreditUnits })}</p>}{plan.planId === "free" ? <p className="mt-3 text-sm font-semibold text-muted-foreground">{t("currentPlan")}</p> : canPurchase && <div className="mt-3 flex flex-wrap gap-2">{plan.trialDays > 0 && canManage && <button disabled={busy} onClick={() => void command({ action: "start_trial", planId: plan.planId, planVersion: plan.version })} className="min-h-10 rounded-lg border px-4 text-sm">{t("startTrial")}</button>}<button disabled={busy} onClick={() => void checkout({ kind: "subscription", planId: plan.planId, planVersion: plan.version })} className="min-h-10 rounded-lg bg-amber-300 px-4 text-sm font-semibold text-stone-950">{t("subscribe")}</button></div>}</article>)}</div></section>}
    <section><h3 className="font-semibold">{t("creditPacks")}</h3><div className="mt-3 grid gap-3 md:grid-cols-3">{data.creditPacks.map((pack) => <article key={`${pack.packId}:${pack.version}`} className="rounded-xl border p-4"><h4 className="font-semibold">{pack.authoredName[locale]}</h4><p className="mt-1 text-sm"><bdi>{new Intl.NumberFormat(locale, { style: "currency", currency: pack.currency }).format((pack.priceMinor + pack.taxMinor) / 100)}</bdi></p>{canPurchase && <button disabled={busy} onClick={() => void checkout({ kind: "credit_pack", packId: pack.packId, packVersion: pack.version })} className="mt-3 min-h-10 rounded-lg bg-amber-300 px-4 text-sm font-semibold text-stone-950">{t("buyCredits", { credits: pack.creditUnits })}</button>}</article>)}</div></section>
    <section><h3 className="font-semibold">{t("buckets")}</h3><div className="mt-3 grid gap-2">{data.credit.buckets.map((bucket) => <div key={bucket.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3 text-sm"><span>{t(`bucketKinds.${bucket.kind}`)} · {bucket.expiresAt ? t("bucketExpiry", { date: date.format(new Date(bucket.expiresAt)) }) : t("noExpiry")}</span><strong><bdi>{new Intl.NumberFormat(locale).format(bucket.availableUnits)}</bdi></strong></div>)}</div>{data.credit.heldReservations.map((reservation) => <p key={reservation.id} className="mt-2 text-sm text-amber-700">{t("held", { count: reservation.maxDebitUnits, state: t(`reservationStates.${reservation.state}`) })}</p>)}</section>
    <section aria-labelledby="credit-activity-title"><h3 id="credit-activity-title" className="font-semibold">{t("creditActivity")}</h3><p className="mt-1 text-xs text-muted-foreground">{t("creditActivityDescription")}</p>{data.credit.recentEntries.length === 0 ? <p className="mt-3 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">{t("noCreditActivity")}</p> : <ol className="mt-3 grid gap-2">{data.credit.recentEntries.map((entry) => <li key={entry.id} className="grid gap-1 rounded-lg border p-3 text-sm sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-medium">{t(`entryTypes.${entry.entryType}`)}</p><time className="text-xs text-muted-foreground" dateTime={entry.createdAt}>{dateTime.format(new Date(entry.createdAt))}</time></div><div className="text-start sm:text-end"><strong className={entry.deltaUnits < 0 ? "text-amber-700" : "text-emerald-700"}><bdi>{integer.format(entry.deltaUnits)}</bdi></strong><p className="text-xs text-muted-foreground">{t("balanceAfter", { count: new Intl.NumberFormat(locale).format(entry.balanceAfterUnits) })}</p></div></li>)}</ol>}</section>
    <section aria-labelledby="billing-history-title"><h3 id="billing-history-title" className="font-semibold">{t("billingHistory")}</h3><p className="mt-1 text-xs text-muted-foreground">{t("billingHistoryDescription")}</p>{data.financials.transactions.length === 0 ? <p className="mt-3 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">{t("noBillingHistory")}</p> : <ol className="mt-3 grid gap-2">{data.financials.transactions.map((transaction) => <li key={`${transaction.provider}:${transaction.transactionRef}`} className="grid gap-3 rounded-lg border p-4 text-sm sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><strong>{t(`transactionKinds.${transaction.purposeKind}`)}</strong><span className="rounded-full bg-muted px-2 py-0.5 text-xs">{t(`transactionStates.${transaction.status}`)}</span></div><time className="mt-1 block text-xs text-muted-foreground" dateTime={transaction.providerOccurredAt}>{dateTime.format(new Date(transaction.providerOccurredAt))}</time><code dir="ltr" className="mt-1 block break-all text-xs text-muted-foreground">{transaction.invoiceNumber ?? transaction.transactionRef}</code>{transaction.refundedMinor > 0 && <p className="mt-1 text-xs text-amber-700">{t("refundedAmount", { price: new Intl.NumberFormat(locale, { style: "currency", currency: transaction.currency }).format(transaction.refundedMinor / 100) })}</p>}</div><div className="text-start sm:text-end"><p className="font-semibold"><bdi>{new Intl.NumberFormat(locale, { style: "currency", currency: transaction.currency }).format(transaction.amountMinor / 100)}</bdi></p><button type="button" disabled={busy || transaction.amountMinor === 0} onClick={() => void invoice(transaction.transactionRef)} className="mt-2 min-h-10 rounded-lg border px-3 text-xs font-semibold">{t("openInvoice")}</button></div></li>)}</ol>}{data.financials.adjustments.length > 0 && <p className="mt-3 text-xs text-muted-foreground">{t("adjustmentEvidence", { count: data.financials.adjustments.length })}</p>}</section>
    <section aria-labelledby="managed-quotes-title"><h3 id="managed-quotes-title" className="font-semibold">{t("managedQuotes")}</h3><p className="mt-1 text-xs text-muted-foreground">{t("managedQuotesDescription")}</p>{data.quotes.length === 0 ? <p className="mt-3 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">{t("noManagedQuotes")}</p> : <div className="mt-3 grid gap-3">{data.quotes.map((quote) => <article key={quote.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{t("quoteCredits", { count: new Intl.NumberFormat(locale).format(quote.maxCreditDebit) })}</p><p className="mt-1 break-all text-xs text-muted-foreground"><bdi>{quote.purposeRef}</bdi></p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-semibold">{t(`quoteStates.${quote.state}`)}</span></div><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div className="text-xs text-muted-foreground"><p>{t("quoteExpires", { date: dateTime.format(new Date(quote.expiresAt)) })}</p>{quote.currency && quote.localPriceMinor !== null ? <p>{t("quoteLocalPrice", { price: new Intl.NumberFormat(locale, { style: "currency", currency: quote.currency }).format((quote.localPriceMinor + (quote.taxMinor ?? 0)) / 100) })}</p> : null}</div>{quote.state === "offered" && canManage ? <button disabled={busy} onClick={() => void command({ action: "accept_quote", quoteId: quote.id })} className="min-h-10 rounded-lg border px-4 text-sm font-semibold">{t("acceptQuote")}</button> : null}</div></article>)}</div>}</section>
    <section><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">{t("referrals")}</h3>{canManage && data.referrals.codes.length === 0 && <div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => void command({ action: "create_referral_code", rewardMode: "generation_credit" })} className="min-h-10 rounded-lg border px-3 text-sm">{t("creditReferral")}</button><button disabled={busy} onClick={() => void command({ action: "create_referral_code", rewardMode: "cash" })} className="min-h-10 rounded-lg border px-3 text-sm">{t("cashReferral")}</button></div>}</div>{data.referrals.codes.map((code) => <div key={code.id} className="mt-3 rounded-xl border p-4"><code dir="ltr" className="block break-all text-start font-semibold">{code.code}</code><p className="mt-1 text-xs text-muted-foreground">{t(`rewardModes.${code.rewardMode}`)} · {t(`referralStates.${code.status}`)}</p></div>)}<p className="mt-3 text-xs text-muted-foreground">{t("referralBoundary")}</p></section>
  </div>;
}
