import "server-only";
import { and, asc, desc, eq, gt, inArray, isNull, lte, or } from "drizzle-orm";
import { randomUUID } from "node:crypto";
import { canonicalDigest } from "@/lib/agent-tools/canonical";
import { getDb } from "@/lib/db";
import {
  billingPlanVersions,
  channelOnboardingCommandReceipts,
  channelOnboardingCommercialQuotes,
  channelOnboardingCredentialHandoffs,
  channelOnboardingEvents,
  channelOnboardingOrders,
  channelOnboardingOfferVersions,
  channelOnboardingPartnerAssignments,
  channelOnboardingPartners,
  channelOnboardingReadinessReviews,
  channelOnboardingTasks,
  credentialProfiles,
  socialAccounts,
  workspaceSubscriptions,
} from "@/lib/db/schema";
import { assertTransition, partnerScopeIsSafe, type ChannelOnboardingState } from "./types";

type Db = ReturnType<typeof getDb>;
type Tx = Parameters<Parameters<Db["transaction"]>[0]>[0];
type JsonResult = Record<string, unknown>;

export class ChannelOnboardingError extends Error {
  constructor(readonly code: string) { super(code); this.name = "ChannelOnboardingError"; }
}

async function claim(tx: Tx, input: { workspaceId: string; idempotencyKey: string; request: unknown }) {
  const requestDigest = canonicalDigest(input.request);
  const inserted = await tx.insert(channelOnboardingCommandReceipts).values({ workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest, result: { state: "processing" } }).onConflictDoNothing().returning({ key: channelOnboardingCommandReceipts.idempotencyKey });
  if (inserted[0]) return { kind: "claimed" as const, requestDigest };
  const [receipt] = await tx.select().from(channelOnboardingCommandReceipts).where(and(eq(channelOnboardingCommandReceipts.workspaceId, input.workspaceId), eq(channelOnboardingCommandReceipts.idempotencyKey, input.idempotencyKey))).limit(1);
  if (!receipt || receipt.requestDigest !== requestDigest) throw new ChannelOnboardingError("IDEMPOTENCY_CONFLICT");
  return { kind: "replay" as const, result: receipt.result };
}

async function complete(tx: Tx, input: { workspaceId: string; idempotencyKey: string; requestDigest: string; result: JsonResult }) {
  await tx.update(channelOnboardingCommandReceipts).set({ result: input.result }).where(and(eq(channelOnboardingCommandReceipts.workspaceId, input.workspaceId), eq(channelOnboardingCommandReceipts.idempotencyKey, input.idempotencyKey), eq(channelOnboardingCommandReceipts.requestDigest, input.requestDigest)));
}

async function lockedOrder(tx: Tx, input: { workspaceId: string; orderId: string; expectedRevision: number }) {
  const [order] = await tx.select().from(channelOnboardingOrders).where(and(eq(channelOnboardingOrders.workspaceId, input.workspaceId), eq(channelOnboardingOrders.id, input.orderId))).for("update").limit(1);
  if (!order) throw new ChannelOnboardingError("ORDER_NOT_FOUND");
  if (order.revision !== input.expectedRevision) throw new ChannelOnboardingError("REVISION_CONFLICT");
  return order;
}

async function transition(tx: Tx, input: { order: typeof channelOnboardingOrders.$inferSelect; to: ChannelOnboardingState; actorRef: string; reasonCode: string; facts?: JsonResult; now: Date }) {
  try { assertTransition(input.order.state, input.to); } catch { throw new ChannelOnboardingError("ORDER_TRANSITION_INVALID"); }
  const revision = input.order.revision + 1;
  const updated = await tx.update(channelOnboardingOrders).set({ state: input.to, revision, blockedReasonCode: input.to === "blocked" ? input.reasonCode : null, updatedAt: input.now }).where(and(eq(channelOnboardingOrders.workspaceId, input.order.workspaceId), eq(channelOnboardingOrders.id, input.order.id), eq(channelOnboardingOrders.revision, input.order.revision))).returning();
  if (!updated[0]) throw new ChannelOnboardingError("REVISION_CONFLICT");
  await tx.insert(channelOnboardingEvents).values({ workspaceId: input.order.workspaceId, orderId: input.order.id, revision, id: randomUUID(), fromState: input.order.state, toState: input.to, actorRef: input.actorRef, reasonCode: input.reasonCode, facts: input.facts ?? {}, occurredAt: input.now });
  return updated[0];
}

export class ChannelOnboardingRepository {
  constructor(private readonly database: Db = getDb(), private readonly now = () => new Date()) {}

  async summary(workspaceId: string) {
    const now = this.now();
    const [offers, orders, quotes, tasks, assignments, handoffs, profiles, channels] = await Promise.all([
      this.database.select().from(channelOnboardingOfferVersions).where(and(eq(channelOnboardingOfferVersions.status, "active"), lte(channelOnboardingOfferVersions.effectiveAt, now), or(isNull(channelOnboardingOfferVersions.retiredAt), gt(channelOnboardingOfferVersions.retiredAt, now)))).orderBy(asc(channelOnboardingOfferVersions.platform), asc(channelOnboardingOfferVersions.localPriceMinor)),
      this.database.select().from(channelOnboardingOrders).where(eq(channelOnboardingOrders.workspaceId, workspaceId)).orderBy(desc(channelOnboardingOrders.updatedAt), desc(channelOnboardingOrders.id)).limit(100),
      this.database.select().from(channelOnboardingCommercialQuotes).where(eq(channelOnboardingCommercialQuotes.workspaceId, workspaceId)).orderBy(desc(channelOnboardingCommercialQuotes.issuedAt)).limit(100),
      this.database.select().from(channelOnboardingTasks).where(eq(channelOnboardingTasks.workspaceId, workspaceId)).orderBy(desc(channelOnboardingTasks.createdAt)).limit(500),
      this.database.select().from(channelOnboardingPartnerAssignments).where(eq(channelOnboardingPartnerAssignments.workspaceId, workspaceId)).orderBy(desc(channelOnboardingPartnerAssignments.createdAt)).limit(200),
      this.database.select().from(channelOnboardingCredentialHandoffs).where(eq(channelOnboardingCredentialHandoffs.workspaceId, workspaceId)).orderBy(desc(channelOnboardingCredentialHandoffs.handedOffAt)).limit(100),
      this.database.select({ id: credentialProfiles.id, name: credentialProfiles.name, provider: credentialProfiles.provider, activeVersion: credentialProfiles.activeVersion }).from(credentialProfiles).where(and(eq(credentialProfiles.workspaceId, workspaceId), eq(credentialProfiles.status, "active"), eq(credentialProfiles.enabled, true))).orderBy(asc(credentialProfiles.name)),
      this.database.select({ id: socialAccounts.id, displayName: socialAccounts.displayName, platform: socialAccounts.platform }).from(socialAccounts).where(and(eq(socialAccounts.workspaceId, workspaceId), eq(socialAccounts.disabled, false), eq(socialAccounts.requiresReauth, false))).orderBy(asc(socialAccounts.displayName)),
    ]);
    return { offers, orders, quotes, tasks, assignments, handoffs, profiles, channels };
  }

  async detail(workspaceId: string, orderId: string) {
    const [order] = await this.database.select().from(channelOnboardingOrders).where(and(eq(channelOnboardingOrders.workspaceId, workspaceId), eq(channelOnboardingOrders.id, orderId))).limit(1);
    if (!order) throw new ChannelOnboardingError("ORDER_NOT_FOUND");
    const [quote, tasks, assignments, handoffs, reviews, events] = await Promise.all([
      order.quoteId ? this.database.select().from(channelOnboardingCommercialQuotes).where(and(eq(channelOnboardingCommercialQuotes.workspaceId, workspaceId), eq(channelOnboardingCommercialQuotes.id, order.quoteId))).limit(1) : Promise.resolve([]),
      this.database.select().from(channelOnboardingTasks).where(and(eq(channelOnboardingTasks.workspaceId, workspaceId), eq(channelOnboardingTasks.orderId, orderId))).orderBy(asc(channelOnboardingTasks.createdAt)),
      this.database.select().from(channelOnboardingPartnerAssignments).where(and(eq(channelOnboardingPartnerAssignments.workspaceId, workspaceId), eq(channelOnboardingPartnerAssignments.orderId, orderId))).orderBy(desc(channelOnboardingPartnerAssignments.createdAt)),
      this.database.select().from(channelOnboardingCredentialHandoffs).where(and(eq(channelOnboardingCredentialHandoffs.workspaceId, workspaceId), eq(channelOnboardingCredentialHandoffs.orderId, orderId))).orderBy(desc(channelOnboardingCredentialHandoffs.handedOffAt)),
      this.database.select().from(channelOnboardingReadinessReviews).where(and(eq(channelOnboardingReadinessReviews.workspaceId, workspaceId), eq(channelOnboardingReadinessReviews.orderId, orderId))).orderBy(desc(channelOnboardingReadinessReviews.reviewedAt)),
      this.database.select().from(channelOnboardingEvents).where(and(eq(channelOnboardingEvents.workspaceId, workspaceId), eq(channelOnboardingEvents.orderId, orderId))).orderBy(asc(channelOnboardingEvents.revision)),
    ]);
    return { order, quote: quote[0] ?? null, tasks, assignments, handoffs, reviews, events };
  }

  async createOrder(input: { workspaceId: string; userId: string; offerId: string; offerVersion: number; region: string; compliancePolicyAccepted: true; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => {
      const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result;
      const [subscription] = await tx.select({ state: workspaceSubscriptions.state, entitlements: billingPlanVersions.entitlements }).from(workspaceSubscriptions).innerJoin(billingPlanVersions, and(eq(workspaceSubscriptions.planId, billingPlanVersions.planId), eq(workspaceSubscriptions.planVersion, billingPlanVersions.version))).where(and(eq(workspaceSubscriptions.workspaceId, input.workspaceId), inArray(workspaceSubscriptions.state, ["trialing", "active", "grace"]))).for("update").limit(1);
      if (!subscription || subscription.entitlements.managedChannelOnboarding !== true) throw new ChannelOnboardingError("ENTITLEMENT_REQUIRED");
      const now = this.now(); const [offer] = await tx.select().from(channelOnboardingOfferVersions).where(and(eq(channelOnboardingOfferVersions.offerId, input.offerId), eq(channelOnboardingOfferVersions.version, input.offerVersion), eq(channelOnboardingOfferVersions.status, "active"))).limit(1);
      if (!offer || offer.effectiveAt > now || (offer.retiredAt && offer.retiredAt <= now) || !offer.supportedRegions.includes(input.region)) throw new ChannelOnboardingError("OFFER_NOT_AVAILABLE");
      const orderId = randomUUID(), quoteId = randomUUID(), expiresAt = new Date(now.getTime() + 30 * 60_000);
      const complianceEvidenceDigest = canonicalDigest({ schema: "channel-onboarding-compliance-acceptance/v1", workspaceId: input.workspaceId, actorUserId: input.userId, offerId: offer.offerId, offerVersion: offer.version, termsDigest: offer.termsDigest, compliancePolicyVersion: offer.compliancePolicyVersion, region: input.region, accepted: input.compliancePolicyAccepted });
      await tx.insert(channelOnboardingCommercialQuotes).values({ workspaceId: input.workspaceId, id: quoteId, purposeRef: `channel-onboarding:${orderId}`, offerId: offer.offerId, offerVersion: offer.version, state: "offered", subtotalMinor: offer.localPriceMinor, taxMinor: 0, totalMinor: offer.localPriceMinor, currency: offer.currency, termsDigest: offer.termsDigest, issuedAt: now, expiresAt });
      await tx.insert(channelOnboardingOrders).values({ workspaceId: input.workspaceId, id: orderId, offerId: offer.offerId, offerVersion: offer.version, platform: offer.platform, region: input.region, state: "quoted", revision: 1, quoteId, complianceEvidenceDigest, createdByUserId: input.userId, createdAt: now, updatedAt: now });
      await tx.insert(channelOnboardingEvents).values({ workspaceId: input.workspaceId, orderId, revision: 1, id: randomUUID(), fromState: null, toState: "quoted", actorRef: `human:${input.userId}`, reasonCode: "order.quoted", facts: { offerId: offer.offerId, offerVersion: offer.version, quoteId, region: input.region }, occurredAt: now });
      const result = { orderId, state: "quoted", revision: 1, quoteId, totalMinor: offer.localPriceMinor, currency: offer.currency, expiresAt: expiresAt.toISOString() }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result;
    });
  }

  async acceptQuote(input: { workspaceId: string; userId: string; orderId: string; expectedRevision: number; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); if (order.state !== "quoted" || !order.quoteId) throw new ChannelOnboardingError("QUOTE_NOT_ACCEPTABLE"); const now = this.now(); const quote = await tx.update(channelOnboardingCommercialQuotes).set({ state: "payment_pending", acceptedByUserId: input.userId, acceptedAt: now }).where(and(eq(channelOnboardingCommercialQuotes.workspaceId, input.workspaceId), eq(channelOnboardingCommercialQuotes.id, order.quoteId), eq(channelOnboardingCommercialQuotes.state, "offered"), gt(channelOnboardingCommercialQuotes.expiresAt, now))).returning(); if (!quote[0]) throw new ChannelOnboardingError("QUOTE_NOT_ACCEPTABLE"); const updated = await transition(tx, { order, to: "payment_pending", actorRef: `human:${input.userId}`, reasonCode: "quote.accepted", facts: { quoteId: order.quoteId }, now }); const result = { orderId: order.id, state: updated.state, revision: updated.revision }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async bindCredential(input: { workspaceId: string; userId: string; orderId: string; expectedRevision: number; credentialProfileId: string; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); if (!["accepted", "customer_action", "blocked"].includes(order.state)) throw new ChannelOnboardingError("CREDENTIAL_HANDOFF_NOT_ALLOWED"); const [profile] = await tx.select().from(credentialProfiles).where(and(eq(credentialProfiles.workspaceId, input.workspaceId), eq(credentialProfiles.id, input.credentialProfileId), eq(credentialProfiles.status, "active"), eq(credentialProfiles.enabled, true))).limit(1); if (!profile || profile.provider !== order.platform) throw new ChannelOnboardingError("CREDENTIAL_PROFILE_MISMATCH"); const now = this.now(), handoffId = randomUUID(); await tx.insert(channelOnboardingCredentialHandoffs).values({ workspaceId: input.workspaceId, id: handoffId, orderId: order.id, credentialProfileId: profile.id, profileVersion: profile.activeVersion, provider: profile.provider, handedOffByUserId: input.userId, handedOffAt: now }); await tx.update(channelOnboardingOrders).set({ credentialProfileId: profile.id, updatedAt: now }).where(and(eq(channelOnboardingOrders.workspaceId, input.workspaceId), eq(channelOnboardingOrders.id, order.id), eq(channelOnboardingOrders.revision, order.revision))); const result = { orderId: order.id, revision: order.revision, state: order.state, handoffId, credentialProfileId: profile.id, profileVersion: profile.activeVersion }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async completeTask(input: { workspaceId: string; actorRef: string; actorKind: "customer" | "partner"; orderId: string; taskId: string; assignmentId?: string; expectedRevision: number; evidenceDigest?: string; evidenceNote?: string; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); const [task] = await tx.select().from(channelOnboardingTasks).where(and(eq(channelOnboardingTasks.workspaceId, input.workspaceId), eq(channelOnboardingTasks.id, input.taskId), eq(channelOnboardingTasks.orderId, input.orderId), eq(channelOnboardingTasks.actorKind, input.actorKind), eq(channelOnboardingTasks.status, "open"))).for("update").limit(1); if (!task) throw new ChannelOnboardingError("TASK_NOT_COMPLETABLE"); if (input.actorKind === "partner") { const [assignment] = await tx.select().from(channelOnboardingPartnerAssignments).where(and(eq(channelOnboardingPartnerAssignments.workspaceId, input.workspaceId), eq(channelOnboardingPartnerAssignments.id, input.assignmentId ?? ""), eq(channelOnboardingPartnerAssignments.orderId, input.orderId), isNull(channelOnboardingPartnerAssignments.revokedAt), gt(channelOnboardingPartnerAssignments.expiresAt, this.now()))).limit(1); if (!assignment || assignment.id !== task.assignmentId || !assignment.scope.permittedActions.includes(task.kind)) throw new ChannelOnboardingError("PARTNER_ASSIGNMENT_DENIED"); } const evidenceDigest = input.evidenceDigest ?? canonicalDigest({ schema: "channel-onboarding-customer-task-evidence/v1", workspaceId: input.workspaceId, orderId: input.orderId, taskId: input.taskId, actorRef: input.actorRef, note: input.evidenceNote }); const now = this.now(); await tx.update(channelOnboardingTasks).set({ status: "completed", evidenceDigest, completedAt: now }).where(and(eq(channelOnboardingTasks.workspaceId, input.workspaceId), eq(channelOnboardingTasks.id, task.id), eq(channelOnboardingTasks.status, "open"))); const remaining = await tx.select({ id: channelOnboardingTasks.id, actorKind: channelOnboardingTasks.actorKind }).from(channelOnboardingTasks).where(and(eq(channelOnboardingTasks.workspaceId, input.workspaceId), eq(channelOnboardingTasks.orderId, input.orderId), eq(channelOnboardingTasks.status, "open"))); const to = remaining.some((row) => row.actorKind === "customer") ? "customer_action" : remaining.some((row) => row.actorKind === "partner") ? "partner_action" : "readiness_review"; const updated = order.state === to ? order : await transition(tx, { order, to, actorRef: input.actorRef, reasonCode: "task.completed", facts: { taskId: task.id, evidenceDigest }, now }); const result = { orderId: order.id, state: updated.state, revision: updated.revision, taskId: task.id }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async cancel(input: { workspaceId: string; userId: string; orderId: string; expectedRevision: number; reasonCode: string; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); const now = this.now(); const updated = await transition(tx, { order, to: "cancelled", actorRef: `human:${input.userId}`, reasonCode: input.reasonCode, now }); if (order.quoteId) await tx.update(channelOnboardingCommercialQuotes).set({ state: "cancelled" }).where(and(eq(channelOnboardingCommercialQuotes.workspaceId, input.workspaceId), eq(channelOnboardingCommercialQuotes.id, order.quoteId), inArray(channelOnboardingCommercialQuotes.state, ["offered", "accepted", "payment_pending"]))); const result = { orderId: order.id, state: updated.state, revision: updated.revision, refundRequired: order.quoteId ? (await tx.select({ state: channelOnboardingCommercialQuotes.state }).from(channelOnboardingCommercialQuotes).where(and(eq(channelOnboardingCommercialQuotes.workspaceId, input.workspaceId), eq(channelOnboardingCommercialQuotes.id, order.quoteId))).limit(1))[0]?.state === "paid" : false }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async connect(input: { workspaceId: string; userId: string; orderId: string; expectedRevision: number; socialAccountId: string; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); if (order.state !== "ready_to_connect" || !order.credentialProfileId) throw new ChannelOnboardingError("ORDER_NOT_READY_TO_CONNECT"); const [account] = await tx.select({ id: socialAccounts.id, platform: socialAccounts.platform }).from(socialAccounts).where(and(eq(socialAccounts.workspaceId, input.workspaceId), eq(socialAccounts.id, input.socialAccountId), eq(socialAccounts.disabled, false), eq(socialAccounts.requiresReauth, false))).limit(1); if (!account || account.platform !== order.platform) throw new ChannelOnboardingError("CHANNEL_MISMATCH"); const now = this.now(); const updated = await transition(tx, { order, to: "connected", actorRef: `human:${input.userId}`, reasonCode: "channel.connected", facts: { socialAccountId: account.id }, now }); await tx.update(channelOnboardingOrders).set({ connectedSocialAccountId: account.id }).where(and(eq(channelOnboardingOrders.workspaceId, input.workspaceId), eq(channelOnboardingOrders.id, order.id), eq(channelOnboardingOrders.revision, updated.revision))); const result = { orderId: order.id, state: updated.state, revision: updated.revision, socialAccountId: account.id }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async confirmPayment(input: { workspaceId: string; orderId: string; expectedRevision: number; merchantReceiptRef: string; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); if (order.state !== "payment_pending" || !order.quoteId) throw new ChannelOnboardingError("PAYMENT_NOT_CONFIRMABLE"); const now = this.now(); const paid = await tx.update(channelOnboardingCommercialQuotes).set({ state: "paid", merchantPaymentRef: input.merchantReceiptRef }).where(and(eq(channelOnboardingCommercialQuotes.workspaceId, input.workspaceId), eq(channelOnboardingCommercialQuotes.id, order.quoteId), eq(channelOnboardingCommercialQuotes.state, "payment_pending"))).returning(); if (!paid[0]) throw new ChannelOnboardingError("PAYMENT_NOT_CONFIRMABLE"); const accepted = await transition(tx, { order, to: "accepted", actorRef: "system:merchant-of-record", reasonCode: "payment.confirmed", facts: { quoteId: order.quoteId, merchantReceiptRef: input.merchantReceiptRef }, now }); const result = { orderId: order.id, state: accepted.state, revision: accepted.revision }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async createTask(input: { workspaceId: string; orderId: string; expectedRevision: number; actorKind: "customer" | "partner"; assignmentId?: string; taskKind: string; taskInstructions: { ar: string; en: string }; taskDueAt: Date | null; actorRef: string; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); if (!["accepted", "customer_action", "partner_action", "blocked", "readiness_review"].includes(order.state)) throw new ChannelOnboardingError("TASK_NOT_ALLOWED"); const now = this.now(), taskId = randomUUID(); await tx.insert(channelOnboardingTasks).values({ workspaceId: input.workspaceId, id: taskId, orderId: order.id, assignmentId: input.assignmentId ?? null, actorKind: input.actorKind, kind: input.taskKind, status: "open", instructions: input.taskInstructions, dueAt: input.taskDueAt, createdAt: now }); const to = input.actorKind === "customer" ? "customer_action" : "partner_action"; const updated = order.state === to ? order : await transition(tx, { order, to, actorRef: input.actorRef, reasonCode: "task.created", facts: { taskId, taskKind: input.taskKind }, now }); const result = { orderId: order.id, state: updated.state, revision: updated.revision, taskId }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async assignPartner(input: { workspaceId: string; orderId: string; expectedRevision: number; partnerId: string; purpose: "guided_setup" | "readiness_review" | "support"; permittedActions: string[]; expiresAt: Date; assignedByUserId: string | null; taskKind: string; taskInstructions: { ar: string; en: string }; taskDueAt: Date | null; idempotencyKey: string }) {
    if (!partnerScopeIsSafe(input.permittedActions)) throw new ChannelOnboardingError("PARTNER_SCOPE_FORBIDDEN");
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); if (!["accepted", "customer_action", "partner_action", "blocked", "readiness_review"].includes(order.state)) throw new ChannelOnboardingError("PARTNER_ASSIGNMENT_NOT_ALLOWED"); const now = this.now(); if (input.expiresAt <= now || input.expiresAt.getTime() - now.getTime() > 14 * 86_400_000) throw new ChannelOnboardingError("PARTNER_ASSIGNMENT_EXPIRY_INVALID"); const [partner] = await tx.select().from(channelOnboardingPartners).where(and(eq(channelOnboardingPartners.id, input.partnerId), eq(channelOnboardingPartners.status, "vetted"), gt(channelOnboardingPartners.expiresAt, input.expiresAt))).limit(1); if (!partner || !partner.supportedPlatforms.includes(order.platform) || !partner.supportedRegions.includes(order.region)) throw new ChannelOnboardingError("PARTNER_NOT_ELIGIBLE"); const assignmentId = randomUUID(), taskId = randomUUID(); await tx.insert(channelOnboardingPartnerAssignments).values({ workspaceId: input.workspaceId, id: assignmentId, orderId: order.id, partnerId: partner.id, purpose: input.purpose, scope: { permittedActions: input.permittedActions, orderId: order.id, platform: order.platform, region: order.region }, startsAt: now, expiresAt: input.expiresAt, assignedByUserId: input.assignedByUserId, createdAt: now }); await tx.insert(channelOnboardingTasks).values({ workspaceId: input.workspaceId, id: taskId, orderId: order.id, assignmentId, actorKind: "partner", kind: input.taskKind, status: "open", instructions: input.taskInstructions, dueAt: input.taskDueAt, createdAt: now }); const updated = order.state === "partner_action" ? order : await transition(tx, { order, to: "partner_action", actorRef: input.assignedByUserId ? `human:${input.assignedByUserId}` : "system:partner-assignment", reasonCode: "partner.assigned", facts: { assignmentId, partnerId: partner.id, purpose: input.purpose, expiresAt: input.expiresAt.toISOString() }, now }); const result = { orderId: order.id, state: updated.state, revision: updated.revision, assignmentId, taskId }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async readinessReview(input: { workspaceId: string; orderId: string; expectedRevision: number; decision: "ready" | "customer_action" | "partner_action" | "blocked"; checklist: Record<string, boolean>; evidenceDigest: string; reviewerRef: string; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); if (order.state !== "readiness_review") throw new ChannelOnboardingError("READINESS_REVIEW_NOT_ALLOWED"); if (input.decision === "ready" && (Object.keys(input.checklist).length === 0 || Object.values(input.checklist).some((value) => !value) || !order.credentialProfileId)) throw new ChannelOnboardingError("READINESS_GATES_INCOMPLETE"); const open = await tx.select({ id: channelOnboardingTasks.id }).from(channelOnboardingTasks).where(and(eq(channelOnboardingTasks.workspaceId, input.workspaceId), eq(channelOnboardingTasks.orderId, input.orderId), eq(channelOnboardingTasks.status, "open"))).limit(1); if (open[0]) throw new ChannelOnboardingError("OPEN_TASKS_REMAIN"); const now = this.now(), reviewId = randomUUID(); await tx.insert(channelOnboardingReadinessReviews).values({ workspaceId: input.workspaceId, id: reviewId, orderId: order.id, decision: input.decision, checklist: input.checklist, evidenceDigest: input.evidenceDigest, reviewerRef: input.reviewerRef, reviewedAt: now }); const to = input.decision === "ready" ? "ready_to_connect" : input.decision; const updated = await transition(tx, { order, to, actorRef: input.reviewerRef, reasonCode: `readiness.${input.decision}`, facts: { reviewId, evidenceDigest: input.evidenceDigest }, now }); const result = { orderId: order.id, state: updated.state, revision: updated.revision, reviewId }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async recordRefund(input: { workspaceId: string; orderId: string; expectedRevision: number; merchantRefundRef: string; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); if (!order.quoteId || !["cancelled", "failed"].includes(order.state)) throw new ChannelOnboardingError("REFUND_NOT_RECORDABLE"); const now = this.now(); const refunded = await tx.update(channelOnboardingCommercialQuotes).set({ state: "refunded", merchantRefundRef: input.merchantRefundRef }).where(and(eq(channelOnboardingCommercialQuotes.workspaceId, input.workspaceId), eq(channelOnboardingCommercialQuotes.id, order.quoteId), eq(channelOnboardingCommercialQuotes.state, "paid"))).returning(); if (!refunded[0]) throw new ChannelOnboardingError("REFUND_NOT_RECORDABLE"); const updated = await transition(tx, { order, to: "refunded", actorRef: "system:merchant-of-record", reasonCode: "payment.refunded", facts: { merchantRefundRef: input.merchantRefundRef }, now }); const result = { orderId: order.id, state: updated.state, revision: updated.revision }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async setState(input: { workspaceId: string; orderId: string; expectedRevision: number; state: ChannelOnboardingState; reasonCode: string; actorRef: string; idempotencyKey: string }) {
    return this.database.transaction(async (tx) => { const command = await claim(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, request: input }); if (command.kind === "replay") return command.result; const order = await lockedOrder(tx, input); const updated = await transition(tx, { order, to: input.state, actorRef: input.actorRef, reasonCode: input.reasonCode, now: this.now() }); const result = { orderId: order.id, state: updated.state, revision: updated.revision }; await complete(tx, { workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: command.requestDigest, result }); return result; });
  }

  async publishOffer(input: typeof channelOnboardingOfferVersions.$inferInsert) { await this.database.insert(channelOnboardingOfferVersions).values(input); return { offerId: input.offerId, version: input.version }; }
  async publishPartner(input: typeof channelOnboardingPartners.$inferInsert) { await this.database.insert(channelOnboardingPartners).values(input); return { partnerId: input.id, status: input.status }; }
}
