"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { BookmarkPlus, ExternalLink, LoaderCircle, Plus } from "lucide-react";
import { CONTENT_FORMATS } from "@/lib/product-surfaces/definitions";
import { productRequest } from "@/components/product-surfaces/ProductApi";

type Item = { id: string; title: string; revision: number; state: string; payload: Record<string, unknown> };
export function InspirationClient({ items }: { items: Item[] }) {
  const t = useTranslations("product.inspiration") as (key: string, values?: Record<string, string | number>) => string; const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); const now = new Date().toISOString(); try { await productRequest("/api/product-records", { kind: "inspiration_item", title: String(data.get("title")), state: "active", idempotencyKey: crypto.randomUUID(), payload: { sourceUrl: String(data.get("sourceUrl")), sourceName: String(data.get("sourceName")), capturedAt: now, metricsObservedAt: now, metrics: { views: 0, likes: 0 }, region: String(data.get("region")), contentLanguage: String(data.get("language")), arabicVariety: data.get("language") === "ar" ? "msa" : null, format: String(data.get("format")), rightsStatus: "user_submitted", permittedInfluence: ["topic", "hook", "pacing", "structure"], whyThisAppears: [t("userSubmittedReason")], tags: String(data.get("tags")).split(",").map((x) => x.trim()).filter(Boolean) } }); event.currentTarget.reset(); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("error")); } finally { setBusy(false); } }
  async function queue(item: Item) { setBusy(true); setError(""); try { await productRequest("/api/product-records", { kind: "blitz_item", title: item.title, state: "queued", idempotencyKey: crypto.randomUUID(), payload: { inspirationItemId: item.id, contentPieceId: null, sourceAttribution: String(item.payload.sourceUrl), remixBrief: { influences: ["topic", "hook", "pacing", "structure"], protectedExpressionExcluded: true }, rationale: t("remixRationale"), rejectionReasons: [] } }); router.push("/blitz"); } catch (cause) { setError(cause instanceof Error ? cause.message : t("error")); } finally { setBusy(false); } }
  return <div className="space-y-7"><form onSubmit={submit} className="grid gap-4 rounded-3xl border bg-card p-6 md:grid-cols-2"><h2 className="text-xl font-semibold md:col-span-2">{t("addTitle")}</h2><Input name="title" label={t("fields.title")} /><Input name="sourceUrl" label={t("fields.url")} type="url" /><Input name="sourceName" label={t("fields.source")} /><Input name="region" label={t("fields.region")} /><label className="grid gap-2 text-sm font-medium">{t("fields.format")}<select name="format" className="min-h-11 rounded-xl border bg-background px-3">{CONTENT_FORMATS.map((format) => <option value={format} key={format}>{t(`formats.${format}`)}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">{t("fields.language")}<select name="language" className="min-h-11 rounded-xl border bg-background px-3"><option value="ar">{t("languages.ar")}</option><option value="en">{t("languages.en")}</option></select></label><Input name="tags" label={t("fields.tags")} required={false} /><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 self-end rounded-xl bg-amber-300 px-4 font-semibold text-stone-950 disabled:opacity-50">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Plus className="size-4" />}{t("add")}</button>{error && <p role="alert" className="text-sm text-destructive md:col-span-2">{error}</p>}</form>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="flex flex-col rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><h2 dir="auto" className="font-semibold">{item.title}</h2><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs text-emerald-800">{t(`rights.${String(item.payload.rightsStatus)}`)}</span></div><p className="mt-3 text-sm text-muted-foreground">{String(item.payload.sourceName)} · {String(item.payload.region || t("allRegions"))}</p><div className="mt-4 flex flex-wrap gap-2">{(item.payload.whyThisAppears as string[]).map((reason) => <span key={reason} className="rounded-full bg-muted px-2 py-1 text-xs">{reason}</span>)}</div><div className="mt-auto flex gap-3 pt-6"><a href={String(item.payload.sourceUrl)} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center gap-2 rounded-lg border px-3 text-sm"><ExternalLink className="size-4" />{t("source")}</a><button onClick={() => queue(item)} disabled={busy || item.payload.rightsStatus === "restricted"} className="inline-flex min-h-10 flex-1 items-center justify-center gap-2 rounded-lg bg-stone-950 px-3 text-sm font-semibold text-white disabled:opacity-50"><BookmarkPlus className="size-4" />{t("queue")}</button></div></article>)}{items.length === 0 && <p className="rounded-2xl border border-dashed p-8 text-center text-muted-foreground md:col-span-2 xl:col-span-3">{t("empty")}</p>}</section></div>;
}
function Input({ name, label, type = "text", required = true }: { name: string; label: string; type?: string; required?: boolean }) { return <label className="grid gap-2 text-sm font-medium">{label}<input dir="auto" name={name} type={type} required={required} className="min-h-11 rounded-xl border bg-background px-3 font-normal" /></label>; }
