"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useTranslations } from "next-intl";
import { getActiveWorkspaceId } from "@/lib/studio/client";

type Json = Record<string, unknown>;
const kinds = ["evidence", "flag", "incident", "recovery_objective", "restore_drill", "contract_migration", "parity_requirement", "experiment"] as const;
const editableKinds = ["flag", "incident", "experiment"] as const;
const gates = ["performance", "accessibility", "flags", "incidents", "recovery", "migrations", "parity", "privacy"] as const;

const templates: Record<(typeof editableKinds)[number], Json> = {
  flag: { id: "flag_change_me", buildId: "build-CHANGE-ME", ownerUserId: "user-change-me", hypothesis: "Document the falsifiable release hypothesis.", createdAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 7 * 86400000).toISOString(), rolloutPercent: 0, safeDefault: "off", status: "active", evidenceIds: ["evidence_change_me"], eligibility: { roles: ["owner"], entitlements: ["pro"], locales: ["ar", "en"] }, dependencyFlagIds: [], telemetryEventName: "release_flag_evaluated", rollback: { mode: "automatic", triggerMetric: "error_rate", threshold: 0.05, windowMinutes: 15, ownerUserId: "user-change-me" } },
  incident: { id: "incident_change_me", severity: "minor", status: "investigating", impactedServices: ["generation"], startedAt: new Date().toISOString(), resolvedAt: null, publicSummary: { ar: "REPLACE_WITH_ARABIC_SUMMARY", en: "REPLACE_WITH_ENGLISH_SUMMARY" }, operationOutcome: "waiting", creditRisk: "at_risk", publishingRisk: "none" },
  experiment: { id: "exp_change_me", buildId: "build-CHANGE-ME", hypothesis: "Document the experiment hypothesis.", variants: ["control", "treatment"], allocationPercent: 0, status: "draft", startsAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 14 * 86400000).toISOString(), ownerUserId: "user-change-me", metric: "completion", guardrails: [{ metric: "error_rate", direction: "below", threshold: 0.05 }], evidenceIds: [] },
};

async function request() { const workspaceId = getActiveWorkspaceId(); if (!workspaceId) throw new Error("WORKSPACE_REQUIRED"); const response = await fetch("/api/studio/release-control", { cache: "no-store", headers: { "x-workspace-id": workspaceId } }); const data = await response.json() as Json; if (!response.ok) throw new Error(String(data.code || "UNAVAILABLE")); return data; }

export function ReleaseQualityCockpit() {
  const t = useTranslations("releaseQuality"); const [data, setData] = useState<Json>({}); const [kind, setKind] = useState<(typeof editableKinds)[number]>("flag"); const [document, setDocument] = useState(JSON.stringify(templates.flag, null, 2)); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(""); try { setData(await request()); } catch (cause) { setError(cause instanceof Error ? cause.message : "UNAVAILABLE"); } }, []); useEffect(() => { void load(); }, [load]);
  const readiness = (data.readiness || {}) as Json; const parityMatrix = (readiness.parityMatrix || {}) as Json; const blockers = Array.isArray(readiness.blockers) ? readiness.blockers as Json[] : []; const snapshot = (data.snapshot || {}) as Json; const records = useMemo(() => Array.isArray(snapshot.records) ? snapshot.records as Json[] : [], [snapshot.records]);
  const counts = useMemo(() => Object.fromEntries(kinds.map((item) => [item, records.filter((record) => record.kind === item).length])), [records]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const workspaceId = getActiveWorkspaceId(); if (!workspaceId) throw new Error("WORKSPACE_REQUIRED"); const parsed = JSON.parse(document) as Json; const response = await fetch("/api/studio/release-control", { method: "POST", headers: { "content-type": "application/json", "x-workspace-id": workspaceId, "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ recordKind: kind, document: parsed }) }); const result = await response.json() as Json; if (!response.ok) throw new Error(String(result.code || "INVALID_INPUT")); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "INVALID_INPUT"); } finally { setBusy(false); } }
  return <main className="mx-auto w-full max-w-7xl space-y-8 p-4 lg:p-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-violet-600">{t("eyebrow")}</p><h1 className="text-3xl font-semibold">{t("title")}</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{t("description")}</p><p className="mt-2 font-mono text-xs text-muted-foreground">{t("manifestBuild", { build: String(readiness.buildId ?? "—") })}</p></div><button type="button" onClick={() => void load()} className="rounded-md border px-3 py-2 text-sm">{t("refresh")}</button></header>{error ? <p role="alert" className="rounded-lg border border-destructive/30 p-3 text-destructive">{t("error", { code: error })}</p> : null}
    <section className={`rounded-xl border p-5 ${readiness.releasable ? "border-emerald-500/40 bg-emerald-500/5" : "border-amber-500/40 bg-amber-500/5"}`}><h2 className="text-xl font-semibold">{readiness.releasable ? t("ready") : t("blocked")}</h2><p className="mt-1 text-sm">{t("blockerCount", { count: blockers.length })}</p><p className="mt-1 text-sm text-muted-foreground">{t("parityCoverage", { passing: Number(parityMatrix.passingCells ?? 0), required: Number(parityMatrix.requiredCells ?? 0) })}</p><ol className="mt-4 grid gap-2 md:grid-cols-2">{blockers.map((blocker, index) => <li key={`${String(blocker.code)}:${String(blocker.subject)}:${index}`} className="rounded-lg border bg-background p-3 text-sm"><strong>{String(blocker.code)}</strong><p className="mt-1 text-muted-foreground">{String(blocker.subject)}</p></li>)}</ol></section>
    <section><h2 className="text-xl font-semibold">{t("evidenceRegister")}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{kinds.map((item) => <article key={item} className="rounded-xl border bg-card p-4"><p className="text-sm text-muted-foreground">{t(`kinds.${item}`)}</p><p className="mt-2 text-2xl font-semibold">{counts[item]}</p></article>)}</div></section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(20rem,.7fr)]"><form onSubmit={submit} className="rounded-xl border bg-card p-5"><h2 className="text-xl font-semibold">{t("recordEvidence")}</h2><p className="mt-1 text-sm text-muted-foreground">{t("appendOnly")}</p><label className="mt-4 block text-sm font-medium">{t("kind")}<select value={kind} onChange={(event) => { const next = event.target.value as typeof kind; setKind(next); setDocument(JSON.stringify(templates[next], null, 2)); }} className="mt-1 w-full rounded-md border bg-background p-2">{editableKinds.map((item) => <option key={item} value={item}>{t(`kinds.${item}`)}</option>)}</select></label><label className="mt-4 block text-sm font-medium">{t("signedDocument")}<textarea dir="ltr" spellCheck={false} value={document} onChange={(event) => setDocument(event.target.value)} className="mt-1 min-h-96 w-full rounded-md border bg-neutral-950 p-3 font-mono text-xs text-neutral-100"/></label><button disabled={busy} className="mt-4 rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50">{busy ? t("saving") : t("save")}</button></form><aside className="rounded-xl border p-5"><h2 className="text-xl font-semibold">{t("gates")}</h2><ul className="mt-4 space-y-3 text-sm text-muted-foreground">{gates.map((gate) => <li key={gate} className="rounded-lg border p-3">{t(`gateHelp.${gate}`)}</li>)}</ul></aside></section>
  </main>;
}
