"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { BellOff, LoaderCircle, Send } from "lucide-react";
import { productRequest } from "@/components/product-surfaces/ProductApi";
import { SupportAssetPicker } from "./SupportAssetPicker";

export function SupportActions({ mode, progress, releases }: { mode: "feedback" | "case" | "releases"; progress: { id: string; revision: number; payload: Record<string, unknown> } | null; releases: string[] }) {
  const rawT = useTranslations(); const t = rawT as unknown as (key: string) => string; const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [attachmentAssetIds, setAttachmentAssetIds] = useState<string[]>([]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = event.currentTarget; const data = new FormData(form); const common = { kind: mode === "feedback" ? "feedback" : "support_case", title: String(data.get("title")), body: String(data.get("body")), category: String(data.get("category")), attachmentAssetIds, idempotencyKey: crypto.randomUUID() }; try { await productRequest("/api/product-support/submit", mode === "feedback" ? { ...common, route: window.location.pathname } : { ...common, severity: String(data.get("severity")) }); form.reset(); setAttachmentAssetIds([]); router.refresh(); } catch (cause) { const code = cause instanceof Error ? cause.message : "REQUEST_FAILED"; setError(SUPPORT_ERROR_CODES.includes(code) ? t(`product.support.errors.${code}`) : t("product.support.error")); } finally { setBusy(false); } }
  async function dismissReleases() { setBusy(true); setError(""); try { const payload = { completedKeys: Array.isArray(progress?.payload.completedKeys) ? progress.payload.completedKeys : [], dismissedReleaseIds: Array.from(new Set([...(Array.isArray(progress?.payload.dismissedReleaseIds) ? progress.payload.dismissedReleaseIds as string[] : []), ...releases])) }; await productRequest("/api/product-guidance", { ...(progress ? { id: progress.id, expectedRevision: progress.revision } : {}), ...payload, idempotencyKey: crypto.randomUUID() }); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("product.support.error")); } finally { setBusy(false); } }
  if (mode === "releases") return <aside className="h-fit rounded-2xl border bg-card p-5"><BellOff className="size-5 text-amber-600" /><h2 className="mt-4 font-semibold">{t("product.support.releaseNotifications")}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{t("product.support.releaseNotificationsHelp")}</p><button type="button" onClick={dismissReleases} disabled={busy} className="mt-4 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-lg border px-3 text-sm font-semibold">{busy && <LoaderCircle className="size-4 animate-spin" />}{t("product.support.dismissReleases")}</button>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}</aside>;
  return <form onSubmit={submit} className="h-fit rounded-2xl border bg-card p-5"><h2 className="text-lg font-semibold">{t(`product.support.forms.${mode}Title`)}</h2><div className="mt-4 grid gap-3"><label className="grid gap-2 text-sm font-medium">{t("product.support.forms.title")}<input name="title" required dir="auto" className="min-h-11 rounded-xl border bg-background px-3" /></label><label className="grid gap-2 text-sm font-medium">{t("product.support.forms.category")}<select name="category" className="min-h-11 rounded-xl border bg-background px-3">{(mode === "feedback" ? ["idea", "problem", "praise"] : ["account", "billing", "generation", "publishing", "safety", "other"]).map((value) => <option key={value} value={value}>{t(`product.support.categories.${value}`)}</option>)}</select></label>{mode === "case" && <label className="grid gap-2 text-sm font-medium">{t("product.support.forms.severity")}<select name="severity" className="min-h-11 rounded-xl border bg-background px-3"><option value="normal">{t("product.support.severity.normal")}</option><option value="urgent">{t("product.support.severity.urgent")}</option></select></label>}<label className="grid gap-2 text-sm font-medium">{t("product.support.forms.body")}<textarea name="body" required dir="auto" rows={6} className="rounded-xl border bg-background p-3" /></label><SupportAssetPicker selected={attachmentAssetIds} onChange={setAttachmentAssetIds} /><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-amber-300 font-semibold text-stone-950">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Send className="size-4" />}{t("product.support.forms.submit")}</button></div>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}</form>;
}

const SUPPORT_ERROR_CODES = ["SUPPORT_SUBMISSION_INVALID", "SUPPORT_SUBMISSION_IDEMPOTENCY_CONFLICT", "SUPPORT_ATTACHMENT_COUNT_EXCEEDED", "SUPPORT_ATTACHMENT_DUPLICATE", "SUPPORT_ATTACHMENT_NOT_AVAILABLE", "SUPPORT_ATTACHMENT_TYPE_UNSUPPORTED", "SUPPORT_ATTACHMENT_NOT_READY", "SUPPORT_ATTACHMENT_MIME_INVALID", "SUPPORT_ATTACHMENT_SIZE_EXCEEDED", "SUPPORT_ATTACHMENT_TOTAL_SIZE_EXCEEDED", "SUPPORT_ATTACHMENT_CHECKSUM_REQUIRED", "REQUEST_FAILED"];
