import Link from "next/link";
import { BookOpen, ExternalLink, Flag, Headphones, MessageSquareText, Rocket } from "lucide-react";
import { getLocale, getTranslations } from "next-intl/server";
import { requireOnboardingComplete } from "@/lib/onboarding/server-access";
import { listProductRecords } from "@/lib/product-surfaces/repository";
import { GUIDE_ENTRIES, RELEASE_NOTES, ROADMAP_ITEMS, type SupportTab } from "@/lib/product-support/catalog";
import { SupportActions } from "./SupportActions";

const tabs: Array<{ key: SupportTab; href: string }> = [{ key: "guide", href: "/guide" }, { key: "feedback", href: "/feedback" }, { key: "roadmap", href: "/roadmap" }, { key: "releases", href: "/releases" }, { key: "cases", href: "/support" }];

export async function SupportHub({ activeTab, path }: { activeTab: SupportTab; path: string }) {
  const { aggregate } = await requireOnboardingComplete(path);
  const workspaceId = aggregate?.session.workspaceId;
  const rawT = await getTranslations();
  const t = rawT as unknown as (key: string, values?: Record<string, string | number>) => string;
  const locale = await getLocale();
  if (!workspaceId) return null;
  const records = await listProductRecords({ workspaceId, kinds: ["feedback", "support_case", "guidance_progress"], includeArchived: true });
  const feedback = records.filter((record) => record.kind === "feedback");
  const cases = records.filter((record) => record.kind === "support_case");
  const progress = records.find((record) => record.kind === "guidance_progress") ?? null;
  const date = new Intl.DateTimeFormat(locale, { dateStyle: "medium" });
  return <main className="flex-1 px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl space-y-7"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-600">{t("product.support.eyebrow")}</p><h1 className="mt-2 text-3xl font-semibold sm:text-4xl">{t("product.support.title")}</h1><p className="mt-2 max-w-3xl text-muted-foreground">{t("product.support.description")}</p></header><nav className="flex gap-2 overflow-x-auto border-b" aria-label={t("product.support.tabsLabel")}>{tabs.map((tab) => <Link key={tab.key} href={tab.href} aria-current={activeTab === tab.key ? "page" : undefined} className={`shrink-0 border-b-2 px-3 py-3 text-sm font-semibold ${activeTab === tab.key ? "border-amber-500" : "border-transparent text-muted-foreground"}`}>{t(`product.support.tabs.${tab.key}`)}</Link>)}</nav>
    {activeTab === "guide" && <section className="grid gap-4 md:grid-cols-2">{GUIDE_ENTRIES.map((entry) => <article key={entry.id} className="rounded-2xl border bg-card p-5"><BookOpen className="size-5 text-amber-600" /><div className="mt-4 flex items-start justify-between gap-3"><h2 className="font-semibold">{t(`product.support.guide.${entry.titleKey}`)}</h2><span className="text-xs text-muted-foreground">{t("product.support.version", { version: entry.version })}</span></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{t(`product.support.guide.${entry.summaryKey}`)}</p><details className="mt-4 rounded-xl bg-muted p-3"><summary className="cursor-pointer text-sm font-semibold">{t("product.support.transcript")}</summary><ol className="mt-3 list-decimal space-y-2 ps-5 text-sm leading-6">{entry.transcriptKeys.map((key) => <li key={key}>{t(`product.support.guide.${key}`)}</li>)}</ol></details><Link href={entry.href} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-amber-700">{t("product.support.openGuideAction")}<ExternalLink className="size-4" /></Link></article>)}</section>}
    {activeTab === "feedback" && <section className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><SupportActions mode="feedback" progress={null} releases={[]} /><RecordList icon={MessageSquareText} records={feedback} t={t} emptyKey="feedbackEmpty" date={date} /></section>}
    {activeTab === "roadmap" && <section className="space-y-4"><p className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950">{t("product.support.roadmapBoundary")}</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{ROADMAP_ITEMS.map((item) => <article key={item.id} className="rounded-2xl border bg-card p-5"><Flag className="size-5 text-amber-600" /><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{t(`product.support.roadmapStates.${item.status}`)} · {item.target ?? t("product.support.targetUnscheduled")}</p><h2 className="mt-2 font-semibold">{t(`product.support.roadmap.${item.titleKey}`)}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{t(`product.support.roadmap.${item.descriptionKey}`)}</p></article>)}</div></section>}
    {activeTab === "releases" && <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-4">{RELEASE_NOTES.map((release) => <article key={release.id} className="rounded-2xl border bg-card p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">{t("product.support.releaseVersion", { version: release.version })}</h2><time className="text-xs text-muted-foreground" dateTime={release.releasedAt}>{date.format(new Date(`${release.releasedAt}T00:00:00Z`))}</time></div><ul className="mt-4 list-disc space-y-2 ps-5 text-sm leading-6">{release.factKeys.map((key) => <li key={key}>{t(`product.support.releases.${key}`)}</li>)}</ul></article>)}</div><SupportActions mode="releases" progress={progress ? { id: progress.id, revision: progress.revision, payload: progress.payload } : null} releases={RELEASE_NOTES.map(({ id }) => id)} /></section>}
    {activeTab === "cases" && <section className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-5"><SupportActions mode="case" progress={null} releases={[]} /><a href="https://discord.com/invite/89Nr6EKkTf" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-2xl border bg-card p-5"><span><strong className="block">{t("product.support.communityTitle")}</strong><span className="mt-1 block text-sm text-muted-foreground">{t("product.support.communityHelp")}</span></span><ExternalLink className="size-5" /></a></div><RecordList icon={Headphones} records={cases} t={t} emptyKey="casesEmpty" date={date} /></section>}
  </div></main>;
}

function RecordList({ records, t, emptyKey, date, icon: Icon }: { records: Array<{ id: string; title: string; state: string; revision: number; updatedAt: Date }>; t: (key: string, values?: Record<string, string | number>) => string; emptyKey: string; date: Intl.DateTimeFormat; icon: typeof Rocket }) { return <section><h2 className="mb-3 text-lg font-semibold">{t("product.support.history")}</h2><div className="space-y-3">{records.length ? records.map((record) => <article key={record.id} className="rounded-2xl border bg-card p-4"><div className="flex items-start gap-3"><Icon className="mt-1 size-4 text-amber-600" /><div><h3 dir="auto" className="font-semibold">{record.title}</h3><p className="mt-1 text-xs text-muted-foreground">{t(`product.support.states.${record.state}`)} · {t("product.support.revision", { revision: record.revision })} · {date.format(record.updatedAt)}</p></div></div></article>) : <p className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">{t(`product.support.${emptyKey}`)}</p>}</div></section>; }
