import { and, desc, eq, sql, type SQLWrapper } from "drizzle-orm";
import type { getDb } from "@/lib/db";
import {
  agentSecurityEvents,
  artifactAuditEvents,
  credentialEffectAuditEvents,
  credentialSecurityEvents,
  credentialSpendEvents,
  runtimeAutomationEvents,
  runtimeBudgetReservationEvents,
  runtimeDiagnosticTraceAccessAudits,
  runtimePublishingApprovalAuthorityGrants,
  runtimePublishingApprovalAuthorityRevocations,
  runtimePublishingDeliveryEvents,
  runtimeQuotaReservationEvents,
  runtimeSpendControlEvents,
  runtimeSupportBundleAccessAudits,
  runtimeSupportBundleAuditEvents,
  runtimeTelemetryOperatorGrantAudits,
  runtimeUsageMeteringEvents,
  socialEvents,
  usageLedgerReceipts,
  workflowRunEvents,
} from "@/lib/db/schema";
import type { GovernanceAuditEvent } from "./types";

export interface GovernanceAuditFederationPort {
  list(input: {
    workspaceId: string;
    limit: number;
    before?: { occurredAt: Date; id: string };
  }): Promise<GovernanceAuditEvent[]>;
}

export const EMPTY_GOVERNANCE_AUDIT_FEDERATION: GovernanceAuditFederationPort = { list: async () => [] };
export const GOVERNANCE_AUDIT_FEDERATION_SOURCES = Object.freeze([
  "agent_security", "credential_security", "credential_effect", "credential_spend",
  "budget", "spend_control", "usage", "usage_receipt", "quota", "artifact",
  "generation", "automation", "publishing_delivery", "social", "diagnostic_access",
  "support_access", "publishing_authority_grant", "publishing_authority_revocation",
  "telemetry_operator_grant", "support_bundle_lifecycle",
] as const);
type Db = ReturnType<typeof getDb>;

function event(input: { workspaceId: string; source: string; id: string; action: string; capability: string; actorUserId?: string | null; principalId?: string | null; resourceKind: string; resourceId: string; outcome: GovernanceAuditEvent["outcome"]; occurredAt: Date; details?: Record<string, unknown> }): GovernanceAuditEvent {
  return { schema: "workspace-audit-event/v1", id: `federated:${input.source}:${input.id}`, workspaceId: input.workspaceId, actor: input.actorUserId ? { kind: "human", id: input.actorUserId } : { kind: "system", id: input.principalId ?? null }, capability: input.capability, action: input.action, resource: { kind: input.resourceKind, id: input.resourceId }, outcome: input.outcome, redactedDetails: { source: input.source, ...(input.details ?? {}) }, occurredAt: input.occurredAt };
}

function beforeCursor(
  occurredAt: SQLWrapper,
  id: SQLWrapper,
  source: string,
  before: { occurredAt: Date; id: string } | undefined,
) {
  if (!before) return undefined;
  const idPrefix = `federated:${source}:`;
  // PostgreSQL row comparison gives the same strict, stable ordering used by
  // the merged customer audit timeline, including timestamp ties.
  return sql`(${occurredAt}, ${idPrefix} || ${id}) < (${before.occurredAt}, ${before.id})`;
}

/** Read-only federation over authoritative append-only domain ledgers. Only
 * allowlisted non-secret columns are projected into the customer audit view. */
export class DrizzleGovernanceAuditFederation implements GovernanceAuditFederationPort {
  constructor(private readonly database: () => Db) {}

  async list(input: { workspaceId: string; limit: number; before?: { occurredAt: Date; id: string } }) {
    const perSource = Math.min(Math.max(input.limit, 1), 10_000);
    const db = this.database();
    const [agents, credentialSecurity, credentialEffects, credentialSpend, budgets, spendControls, usage, usageReceipts, quotas, artifacts, runs, automations, deliveries, social, diagnostics, support, publishingAuthorityGrants, publishingAuthorityRevocations, telemetryOperatorGrants, supportLifecycle] = await Promise.all([
      db.select({ id: agentSecurityEvents.id, actorUserId: agentSecurityEvents.actorUserId, principalId: agentSecurityEvents.principalId, eventType: agentSecurityEvents.eventType, capabilityName: agentSecurityEvents.capabilityName, capabilityVersion: agentSecurityEvents.capabilityVersion, reason: agentSecurityEvents.reason, createdAt: agentSecurityEvents.createdAt }).from(agentSecurityEvents).where(and(eq(agentSecurityEvents.workspaceId, input.workspaceId), beforeCursor(agentSecurityEvents.createdAt, agentSecurityEvents.id, "agent_security", input.before))).orderBy(desc(agentSecurityEvents.createdAt), desc(agentSecurityEvents.id)).limit(perSource),
      db.select({ id: credentialSecurityEvents.id, actorUserId: credentialSecurityEvents.actorUserId, principalId: credentialSecurityEvents.principalId, eventType: credentialSecurityEvents.eventType, profileId: credentialSecurityEvents.profileId, createdAt: credentialSecurityEvents.createdAt }).from(credentialSecurityEvents).where(and(eq(credentialSecurityEvents.workspaceId, input.workspaceId), beforeCursor(credentialSecurityEvents.createdAt, credentialSecurityEvents.id, "credential_security", input.before))).orderBy(desc(credentialSecurityEvents.createdAt), desc(credentialSecurityEvents.id)).limit(perSource),
      db.select({ id: credentialEffectAuditEvents.id, principalId: credentialEffectAuditEvents.principalId, eventType: credentialEffectAuditEvents.eventType, effectRef: credentialEffectAuditEvents.effectRef, failureCode: credentialEffectAuditEvents.failureCode, createdAt: credentialEffectAuditEvents.createdAt }).from(credentialEffectAuditEvents).where(and(eq(credentialEffectAuditEvents.workspaceId, input.workspaceId), beforeCursor(credentialEffectAuditEvents.createdAt, credentialEffectAuditEvents.id, "credential_effect", input.before))).orderBy(desc(credentialEffectAuditEvents.createdAt), desc(credentialEffectAuditEvents.id)).limit(perSource),
      db.select({ id: credentialSpendEvents.id, principalId: credentialSpendEvents.principalId, effectRef: credentialSpendEvents.effectRef, provider: credentialSpendEvents.resolvedProvider, priceCeilingCents: credentialSpendEvents.priceCeilingCents, status: credentialSpendEvents.status, failureCode: credentialSpendEvents.failureCode, createdAt: credentialSpendEvents.createdAt }).from(credentialSpendEvents).where(and(eq(credentialSpendEvents.workspaceId, input.workspaceId), beforeCursor(credentialSpendEvents.createdAt, credentialSpendEvents.id, "credential_spend", input.before))).orderBy(desc(credentialSpendEvents.createdAt), desc(credentialSpendEvents.id)).limit(perSource),
      db.select({ id: runtimeBudgetReservationEvents.id, eventType: runtimeBudgetReservationEvents.eventType, reservationId: runtimeBudgetReservationEvents.reservationId, runId: runtimeBudgetReservationEvents.runId, amount: runtimeBudgetReservationEvents.amount, currency: runtimeBudgetReservationEvents.currency, occurredAt: runtimeBudgetReservationEvents.occurredAt }).from(runtimeBudgetReservationEvents).where(and(eq(runtimeBudgetReservationEvents.workspaceId, input.workspaceId), beforeCursor(runtimeBudgetReservationEvents.occurredAt, runtimeBudgetReservationEvents.id, "budget", input.before))).orderBy(desc(runtimeBudgetReservationEvents.occurredAt), desc(runtimeBudgetReservationEvents.id)).limit(perSource),
      db.select({ id: runtimeSpendControlEvents.id, revision: runtimeSpendControlEvents.revision, suspended: runtimeSpendControlEvents.suspended, actorUserId: runtimeSpendControlEvents.actorUserId, recordedAt: runtimeSpendControlEvents.recordedAt }).from(runtimeSpendControlEvents).where(and(eq(runtimeSpendControlEvents.workspaceId, input.workspaceId), beforeCursor(runtimeSpendControlEvents.recordedAt, runtimeSpendControlEvents.id, "spend_control", input.before))).orderBy(desc(runtimeSpendControlEvents.recordedAt), desc(runtimeSpendControlEvents.id)).limit(perSource),
      db.select({ id: runtimeUsageMeteringEvents.id, principalId: runtimeUsageMeteringEvents.principalId, eventType: runtimeUsageMeteringEvents.eventType, runId: runtimeUsageMeteringEvents.runId, occurredAt: runtimeUsageMeteringEvents.occurredAt }).from(runtimeUsageMeteringEvents).where(and(eq(runtimeUsageMeteringEvents.workspaceId, input.workspaceId), beforeCursor(runtimeUsageMeteringEvents.occurredAt, runtimeUsageMeteringEvents.id, "usage", input.before))).orderBy(desc(runtimeUsageMeteringEvents.occurredAt), desc(runtimeUsageMeteringEvents.id)).limit(perSource),
      db.select({ id: usageLedgerReceipts.id, kind: usageLedgerReceipts.kind, createdAt: usageLedgerReceipts.createdAt }).from(usageLedgerReceipts).where(and(eq(usageLedgerReceipts.workspaceId, input.workspaceId), beforeCursor(usageLedgerReceipts.createdAt, usageLedgerReceipts.id, "usage_receipt", input.before))).orderBy(desc(usageLedgerReceipts.createdAt), desc(usageLedgerReceipts.id)).limit(perSource),
      db.select({ id: runtimeQuotaReservationEvents.id, reservationId: runtimeQuotaReservationEvents.reservationId, eventType: runtimeQuotaReservationEvents.eventType, amount: runtimeQuotaReservationEvents.amount, occurredAt: runtimeQuotaReservationEvents.occurredAt }).from(runtimeQuotaReservationEvents).where(and(eq(runtimeQuotaReservationEvents.workspaceId, input.workspaceId), beforeCursor(runtimeQuotaReservationEvents.occurredAt, runtimeQuotaReservationEvents.id, "quota", input.before))).orderBy(desc(runtimeQuotaReservationEvents.occurredAt), desc(runtimeQuotaReservationEvents.id)).limit(perSource),
      db.select({ id: artifactAuditEvents.id, principalId: artifactAuditEvents.principalId, artifactId: artifactAuditEvents.artifactId, uploadId: artifactAuditEvents.uploadId, eventType: artifactAuditEvents.eventType, createdAt: artifactAuditEvents.createdAt }).from(artifactAuditEvents).where(and(eq(artifactAuditEvents.workspaceId, input.workspaceId), beforeCursor(artifactAuditEvents.createdAt, artifactAuditEvents.id, "artifact", input.before))).orderBy(desc(artifactAuditEvents.createdAt), desc(artifactAuditEvents.id)).limit(perSource),
      db.select({ id: workflowRunEvents.id, runId: workflowRunEvents.runId, type: workflowRunEvents.type, occurredAt: workflowRunEvents.occurredAt }).from(workflowRunEvents).where(and(eq(workflowRunEvents.workspaceId, input.workspaceId), beforeCursor(workflowRunEvents.occurredAt, workflowRunEvents.id, "generation", input.before))).orderBy(desc(workflowRunEvents.occurredAt), desc(workflowRunEvents.id)).limit(perSource),
      db.select({ id: runtimeAutomationEvents.id, automationId: runtimeAutomationEvents.automationId, type: runtimeAutomationEvents.type, occurrenceId: runtimeAutomationEvents.occurrenceId, occurredAt: runtimeAutomationEvents.occurredAt }).from(runtimeAutomationEvents).where(and(eq(runtimeAutomationEvents.workspaceId, input.workspaceId), beforeCursor(runtimeAutomationEvents.occurredAt, runtimeAutomationEvents.id, "automation", input.before))).orderBy(desc(runtimeAutomationEvents.occurredAt), desc(runtimeAutomationEvents.id)).limit(perSource),
      db.select({ id: runtimePublishingDeliveryEvents.id, deliveryId: runtimePublishingDeliveryEvents.deliveryId, type: runtimePublishingDeliveryEvents.type, occurredAt: runtimePublishingDeliveryEvents.occurredAt }).from(runtimePublishingDeliveryEvents).where(and(eq(runtimePublishingDeliveryEvents.workspaceId, input.workspaceId), beforeCursor(runtimePublishingDeliveryEvents.occurredAt, runtimePublishingDeliveryEvents.id, "publishing_delivery", input.before))).orderBy(desc(runtimePublishingDeliveryEvents.occurredAt), desc(runtimePublishingDeliveryEvents.id)).limit(perSource),
      db.select({ id: socialEvents.id, eventType: socialEvents.eventType, postId: socialEvents.postId, accountId: socialEvents.accountId, createdByUserId: socialEvents.createdByUserId, createdAt: socialEvents.createdAt }).from(socialEvents).where(and(eq(socialEvents.workspaceId, input.workspaceId), beforeCursor(socialEvents.createdAt, socialEvents.id, "social", input.before))).orderBy(desc(socialEvents.createdAt), desc(socialEvents.id)).limit(perSource),
      db.select({ id: runtimeDiagnosticTraceAccessAudits.id, operatorTraceRef: runtimeDiagnosticTraceAccessAudits.operatorTraceRef, operatorId: runtimeDiagnosticTraceAccessAudits.operatorId, outcome: runtimeDiagnosticTraceAccessAudits.outcome, occurredAt: runtimeDiagnosticTraceAccessAudits.occurredAt }).from(runtimeDiagnosticTraceAccessAudits).where(and(eq(runtimeDiagnosticTraceAccessAudits.workspaceId, input.workspaceId), beforeCursor(runtimeDiagnosticTraceAccessAudits.occurredAt, runtimeDiagnosticTraceAccessAudits.id, "diagnostic_access", input.before))).orderBy(desc(runtimeDiagnosticTraceAccessAudits.occurredAt), desc(runtimeDiagnosticTraceAccessAudits.id)).limit(perSource),
      db.select({ id: runtimeSupportBundleAccessAudits.id, bundleId: runtimeSupportBundleAccessAudits.bundleId, operatorId: runtimeSupportBundleAccessAudits.operatorId, outcome: runtimeSupportBundleAccessAudits.outcome, occurredAt: runtimeSupportBundleAccessAudits.occurredAt }).from(runtimeSupportBundleAccessAudits).where(and(eq(runtimeSupportBundleAccessAudits.workspaceId, input.workspaceId), beforeCursor(runtimeSupportBundleAccessAudits.occurredAt, runtimeSupportBundleAccessAudits.id, "support_access", input.before))).orderBy(desc(runtimeSupportBundleAccessAudits.occurredAt), desc(runtimeSupportBundleAccessAudits.id)).limit(perSource),
      db.select({ id: runtimePublishingApprovalAuthorityGrants.id, userId: runtimePublishingApprovalAuthorityGrants.userId, issuedByUserId: runtimePublishingApprovalAuthorityGrants.issuedByUserId, channelId: runtimePublishingApprovalAuthorityGrants.channelId, issuedAt: runtimePublishingApprovalAuthorityGrants.issuedAt }).from(runtimePublishingApprovalAuthorityGrants).where(and(eq(runtimePublishingApprovalAuthorityGrants.workspaceId, input.workspaceId), beforeCursor(runtimePublishingApprovalAuthorityGrants.issuedAt, runtimePublishingApprovalAuthorityGrants.id, "publishing_authority_grant", input.before))).orderBy(desc(runtimePublishingApprovalAuthorityGrants.issuedAt), desc(runtimePublishingApprovalAuthorityGrants.id)).limit(perSource),
      db.select({ grantId: runtimePublishingApprovalAuthorityRevocations.grantId, revokedByUserId: runtimePublishingApprovalAuthorityRevocations.revokedByUserId, revokedAt: runtimePublishingApprovalAuthorityRevocations.revokedAt }).from(runtimePublishingApprovalAuthorityRevocations).where(and(eq(runtimePublishingApprovalAuthorityRevocations.workspaceId, input.workspaceId), beforeCursor(runtimePublishingApprovalAuthorityRevocations.revokedAt, runtimePublishingApprovalAuthorityRevocations.grantId, "publishing_authority_revocation", input.before))).orderBy(desc(runtimePublishingApprovalAuthorityRevocations.revokedAt), desc(runtimePublishingApprovalAuthorityRevocations.grantId)).limit(perSource),
      db.select({ id: runtimeTelemetryOperatorGrantAudits.id, grantId: runtimeTelemetryOperatorGrantAudits.grantId, eventType: runtimeTelemetryOperatorGrantAudits.eventType, occurredAt: runtimeTelemetryOperatorGrantAudits.occurredAt }).from(runtimeTelemetryOperatorGrantAudits).where(and(eq(runtimeTelemetryOperatorGrantAudits.workspaceId, input.workspaceId), beforeCursor(runtimeTelemetryOperatorGrantAudits.occurredAt, runtimeTelemetryOperatorGrantAudits.id, "telemetry_operator_grant", input.before))).orderBy(desc(runtimeTelemetryOperatorGrantAudits.occurredAt), desc(runtimeTelemetryOperatorGrantAudits.id)).limit(perSource),
      db.select({ id: runtimeSupportBundleAuditEvents.id, bundleId: runtimeSupportBundleAuditEvents.bundleId, eventType: runtimeSupportBundleAuditEvents.eventType, occurredAt: runtimeSupportBundleAuditEvents.occurredAt }).from(runtimeSupportBundleAuditEvents).where(and(eq(runtimeSupportBundleAuditEvents.workspaceId, input.workspaceId), beforeCursor(runtimeSupportBundleAuditEvents.occurredAt, runtimeSupportBundleAuditEvents.id, "support_bundle_lifecycle", input.before))).orderBy(desc(runtimeSupportBundleAuditEvents.occurredAt), desc(runtimeSupportBundleAuditEvents.id)).limit(perSource),
    ]);
    const events: GovernanceAuditEvent[] = [
      ...agents.map((row) => event({ workspaceId: input.workspaceId, source: "agent_security", id: row.id, action: row.eventType, capability: `${row.capabilityName}@${row.capabilityVersion}`, actorUserId: row.actorUserId, principalId: row.principalId, resourceKind: "agent_principal", resourceId: row.principalId ?? row.id, outcome: row.eventType.endsWith("denied") ? "denied" : "completed", occurredAt: row.createdAt, details: { reason: row.reason } })),
      ...credentialSecurity.map((row) => event({ workspaceId: input.workspaceId, source: "credential_security", id: row.id, action: row.eventType, capability: "credential_profiles.audit@1", actorUserId: row.actorUserId, principalId: row.principalId, resourceKind: "credential_profile", resourceId: row.profileId ?? row.id, outcome: "completed", occurredAt: row.createdAt })),
      ...credentialEffects.map((row) => event({ workspaceId: input.workspaceId, source: "credential_effect", id: row.id, action: row.eventType, capability: "provider_effects.audit@1", principalId: row.principalId, resourceKind: "provider_effect", resourceId: row.effectRef, outcome: row.failureCode ? "failed" : "completed", occurredAt: row.createdAt, details: { failureCode: row.failureCode } })),
      ...credentialSpend.map((row) => event({ workspaceId: input.workspaceId, source: "credential_spend", id: row.id, action: `credential_spend.${row.status}`, capability: "credential_spend.audit@1", principalId: row.principalId, resourceKind: "provider_effect", resourceId: row.effectRef, outcome: row.failureCode ? "failed" : row.status === "unknown" ? "failed" : "completed", occurredAt: row.createdAt, details: { provider: row.provider, priceCeilingCents: row.priceCeilingCents, failureCode: row.failureCode } })),
      ...budgets.map((row) => event({ workspaceId: input.workspaceId, source: "budget", id: row.id, action: row.eventType, capability: "budgets.audit@1", resourceKind: "budget_reservation", resourceId: row.reservationId, outcome: row.eventType === "outcome_unknown" ? "failed" : "completed", occurredAt: row.occurredAt, details: { runId: row.runId, amount: row.amount, currency: row.currency } })),
      ...spendControls.map((row) => event({ workspaceId: input.workspaceId, source: "spend_control", id: row.id, action: row.suspended ? "spend.suspended" : "spend.resumed", capability: "budgets.audit@1", actorUserId: row.actorUserId, resourceKind: "spend_control", resourceId: `revision:${row.revision}`, outcome: "completed", occurredAt: row.recordedAt })),
      ...usage.map((row) => event({ workspaceId: input.workspaceId, source: "usage", id: row.id, action: row.eventType, capability: "usage.audit@1", principalId: row.principalId, resourceKind: "workflow_run", resourceId: row.runId, outcome: "completed", occurredAt: row.occurredAt })),
      ...usageReceipts.map((row) => event({ workspaceId: input.workspaceId, source: "usage_receipt", id: row.id, action: `usage.${row.kind}`, capability: "usage.audit@1", resourceKind: "usage_receipt", resourceId: row.id, outcome: "completed", occurredAt: row.createdAt })),
      ...quotas.map((row) => event({ workspaceId: input.workspaceId, source: "quota", id: row.id, action: `quota.${row.eventType}`, capability: "quotas.audit@1", resourceKind: "quota_reservation", resourceId: row.reservationId, outcome: "completed", occurredAt: row.occurredAt, details: { amount: row.amount } })),
      ...artifacts.map((row) => event({ workspaceId: input.workspaceId, source: "artifact", id: row.id, action: row.eventType, capability: "artifacts.audit@1", principalId: row.principalId, resourceKind: row.artifactId ? "artifact" : "artifact_upload", resourceId: row.artifactId ?? row.uploadId ?? row.id, outcome: row.eventType.includes("failed") ? "failed" : "completed", occurredAt: row.createdAt })),
      ...runs.map((row) => event({ workspaceId: input.workspaceId, source: "generation", id: row.id, action: row.type, capability: "workflow_runs.audit@1", resourceKind: "workflow_run", resourceId: row.runId, outcome: row.type.includes("failed") ? "failed" : "completed", occurredAt: row.occurredAt })),
      ...automations.map((row) => event({ workspaceId: input.workspaceId, source: "automation", id: row.id, action: row.type, capability: "automations.audit@1", resourceKind: row.occurrenceId ? "automation_occurrence" : "automation", resourceId: row.occurrenceId ?? row.automationId, outcome: row.type.includes("failed") ? "failed" : "completed", occurredAt: row.occurredAt })),
      ...deliveries.map((row) => event({ workspaceId: input.workspaceId, source: "publishing_delivery", id: row.id, action: row.type, capability: "publishing_deliveries.audit@1", resourceKind: "publishing_delivery", resourceId: row.deliveryId, outcome: row.type.includes("failed") ? "failed" : "completed", occurredAt: row.occurredAt })),
      ...social.map((row) => event({ workspaceId: input.workspaceId, source: "social", id: row.id, action: row.eventType, capability: "social.audit@1", actorUserId: row.createdByUserId, resourceKind: row.postId ? "social_post" : "channel", resourceId: row.postId ?? row.accountId ?? row.id, outcome: row.eventType.includes("failed") ? "failed" : "completed", occurredAt: row.createdAt })),
      ...diagnostics.map((row) => event({ workspaceId: input.workspaceId, source: "diagnostic_access", id: row.id, action: `diagnostic_access.${row.outcome}`, capability: "diagnostic_traces.audit@1", resourceKind: "diagnostic_trace", resourceId: row.operatorTraceRef, outcome: row.outcome === "granted" ? "completed" : "denied", occurredAt: row.occurredAt, details: { operatorId: row.operatorId } })),
      ...support.map((row) => event({ workspaceId: input.workspaceId, source: "support_access", id: row.id, action: `support_access.${row.outcome}`, capability: "support_bundles.audit@1", resourceKind: "support_bundle", resourceId: row.bundleId, outcome: row.outcome === "granted" ? "completed" : "denied", occurredAt: row.occurredAt, details: { operatorId: row.operatorId } })),
      ...publishingAuthorityGrants.map((row) => event({ workspaceId: input.workspaceId, source: "publishing_authority_grant", id: row.id, action: "publishing_authority.granted", capability: "publishing_approval_authority.audit@1", actorUserId: row.issuedByUserId, resourceKind: "publishing_approval_authority", resourceId: row.id, outcome: "completed", occurredAt: row.issuedAt, details: { subjectUserId: row.userId, channelId: row.channelId } })),
      ...publishingAuthorityRevocations.map((row) => event({ workspaceId: input.workspaceId, source: "publishing_authority_revocation", id: row.grantId, action: "publishing_authority.revoked", capability: "publishing_approval_authority.audit@1", actorUserId: row.revokedByUserId, resourceKind: "publishing_approval_authority", resourceId: row.grantId, outcome: "completed", occurredAt: row.revokedAt })),
      ...telemetryOperatorGrants.map((row) => event({ workspaceId: input.workspaceId, source: "telemetry_operator_grant", id: row.id, action: `telemetry_operator.${row.eventType}`, capability: "observability.operator_grants.audit@1", resourceKind: "telemetry_operator_grant", resourceId: row.grantId, outcome: "completed", occurredAt: row.occurredAt })),
      ...supportLifecycle.map((row) => event({ workspaceId: input.workspaceId, source: "support_bundle_lifecycle", id: row.id, action: row.eventType, capability: "support_bundles.audit@1", resourceKind: "support_bundle", resourceId: row.bundleId, outcome: "completed", occurredAt: row.occurredAt })),
    ];
    return events.sort((a, b) => b.occurredAt.getTime() - a.occurredAt.getTime() || b.id.localeCompare(a.id)).slice(0, input.limit);
  }
}
