import { and, asc, eq, gt, inArray, lte, or, sql } from "drizzle-orm";
import type { getDb } from "@/lib/db";
import {
  runtimeDiagnosticTraceAccessAudits, runtimeDiagnosticTraces, runtimeObservabilityAdminReceipts,
  runtimeObservabilityRetentionPolicies, runtimeObservabilityRetentionRevisions,
  runtimeOperationalMetricDeltaReceipts, runtimeOperationalMetrics, runtimeSupportBundleAccessAudits, runtimeSupportBundleAuditEvents, runtimeSupportBundleBindIntents, runtimeSupportBundleReceipts,
  runtimeSupportBundles, runtimeTelemetryOperatorGrantAudits, runtimeTelemetryOperatorGrants,
} from "@/lib/db/schema";
import type { DiagnosticTrace, DiagnosticTraceAccessAuditEvent, ObservabilityRepository, ObservabilityRetentionPolicy, ObservabilityRetentionRevision, OperationalMetricAggregate, OperatorGrantAuditEvent, SupportBundleAccessAuditEvent, SupportBundleAuditEvent, SupportBundleRecord, WorkspaceTelemetryOperatorGrant } from "./types";
import { supportBundleIntentMatchesRecord } from "./support-bundle-intent-match";
import type { SupportBundleBindIntent } from "./support-bundles";

type Db = ReturnType<typeof getDb>;
const date = (value: Date | string) => value instanceof Date ? value : new Date(value);
function retentionRevision(value: ObservabilityRetentionRevision): ObservabilityRetentionRevision { return { ...structuredClone(value), createdAt: date(value.createdAt) }; }
function policy(value: ObservabilityRetentionPolicy): ObservabilityRetentionPolicy { return { ...structuredClone(value), createdAt: date(value.createdAt), updatedAt: date(value.updatedAt) }; }
function trace(value: DiagnosticTrace): DiagnosticTrace { return { ...structuredClone(value), createdAt: date(value.createdAt), expiresAt: date(value.expiresAt) }; }
function metric(value: OperationalMetricAggregate): OperationalMetricAggregate { return { ...structuredClone(value), windowStartsAt: date(value.windowStartsAt), windowEndsAt: date(value.windowEndsAt), recordedAt: date(value.recordedAt), expiresAt: date(value.expiresAt) }; }
function grant(value: WorkspaceTelemetryOperatorGrant): WorkspaceTelemetryOperatorGrant { return { ...structuredClone(value), issuedAt: date(value.issuedAt), expiresAt: date(value.expiresAt), revokedAt: value.revokedAt ? date(value.revokedAt) : null }; }
function bundle(value: SupportBundleRecord): SupportBundleRecord { return { ...structuredClone(value), selections: value.selections.map((item) => structuredClone(item)), consent: { ...structuredClone(value.consent), grantedAt: date(value.consent.grantedAt), expiresAt: date(value.consent.expiresAt) }, createdAt: date(value.createdAt), expiresAt: date(value.expiresAt), storedAt: date(value.storedAt) }; }

export class DrizzleObservabilityRepository implements ObservabilityRepository {
  constructor(private readonly database: () => Db) {}
  async getAdminReceipt(workspaceId: string, key: string) { const [row] = await this.database().select().from(runtimeObservabilityAdminReceipts).where(and(eq(runtimeObservabilityAdminReceipts.workspaceId, workspaceId), eq(runtimeObservabilityAdminReceipts.idempotencyKey, key))).limit(1); return row ? { digest: row.requestDigest, resourceId: row.resourceId } : null; }
  async getRetentionPolicy(workspaceId: string) { const [row] = await this.database().select({ policy: runtimeObservabilityRetentionPolicies.policy, revision: runtimeObservabilityRetentionRevisions.revisionRecord }).from(runtimeObservabilityRetentionPolicies).innerJoin(runtimeObservabilityRetentionRevisions, and(eq(runtimeObservabilityRetentionRevisions.workspaceId, runtimeObservabilityRetentionPolicies.workspaceId), eq(runtimeObservabilityRetentionRevisions.id, runtimeObservabilityRetentionPolicies.currentRevisionId))).where(eq(runtimeObservabilityRetentionPolicies.workspaceId, workspaceId)).limit(1); return row ? { policy: policy(row.policy), revision: retentionRevision(row.revision) } : null; }
  appendRetentionRevision(input: { policy: ObservabilityRetentionPolicy; revision: ObservabilityRetentionRevision; idempotencyKey: string; digest: string }) { return this.database().transaction(async (tx) => { await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`runtime-observability:${input.policy.workspaceId}`}, 0))`); const [receipt] = await tx.select().from(runtimeObservabilityAdminReceipts).where(and(eq(runtimeObservabilityAdminReceipts.workspaceId, input.policy.workspaceId), eq(runtimeObservabilityAdminReceipts.idempotencyKey, input.idempotencyKey))).limit(1); if (receipt) return receipt.requestDigest === input.digest ? "replayed" as const : "conflict" as const; const [current] = await tx.select().from(runtimeObservabilityRetentionPolicies).where(eq(runtimeObservabilityRetentionPolicies.workspaceId, input.policy.workspaceId)).for("update"); if (current) { const [lockedRevision] = await tx.select({ value: runtimeObservabilityRetentionRevisions.revisionRecord }).from(runtimeObservabilityRetentionRevisions).where(eq(runtimeObservabilityRetentionRevisions.id, current.currentRevisionId)).limit(1); if (!lockedRevision) return "conflict" as const; const revision = retentionRevision(lockedRevision.value); if (input.revision.revision !== revision.revision + 1 || input.revision.metricTtlSeconds > revision.metricTtlSeconds || input.revision.traceTtlSeconds > revision.traceTtlSeconds || input.revision.supportBundleTtlSeconds > revision.supportBundleTtlSeconds) return "conflict" as const; await tx.update(runtimeObservabilityRetentionPolicies).set({ currentRevisionId: input.revision.id, status: input.policy.status, policy: input.policy, updatedAt: input.policy.updatedAt }).where(eq(runtimeObservabilityRetentionPolicies.id, current.id)); } else await tx.insert(runtimeObservabilityRetentionPolicies).values({ id: input.policy.id, workspaceId: input.policy.workspaceId, currentRevisionId: input.policy.currentRevisionId, status: input.policy.status, policy: input.policy, createdAt: input.policy.createdAt, updatedAt: input.policy.updatedAt }); await tx.insert(runtimeObservabilityRetentionRevisions).values({ id: input.revision.id, workspaceId: input.revision.workspaceId, policyId: input.revision.policyId, revision: input.revision.revision, metricTtlSeconds: input.revision.metricTtlSeconds, traceTtlSeconds: input.revision.traceTtlSeconds, supportBundleTtlSeconds: input.revision.supportBundleTtlSeconds, revisionRecord: input.revision, createdAt: input.revision.createdAt }); await tx.insert(runtimeObservabilityAdminReceipts).values({ workspaceId: input.policy.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: input.digest, resourceId: input.revision.id, createdAt: input.revision.createdAt }); return "created" as const; }).catch(() => "unavailable" as const); }
  applyMetricDelta(input: { aggregate: OperationalMetricAggregate; eventId: string; requestDigest: string; countDelta: number; sumDelta: number }) { return this.database().transaction(async (tx) => { await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`runtime-observability:${input.aggregate.workspaceId}`}, 0))`); await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`runtime-metric:${input.aggregate.workspaceId}:${input.aggregate.id}`}, 0))`); const [receipt] = await tx.select().from(runtimeOperationalMetricDeltaReceipts).where(and(eq(runtimeOperationalMetricDeltaReceipts.workspaceId, input.aggregate.workspaceId), eq(runtimeOperationalMetricDeltaReceipts.eventId, input.eventId))).limit(1); const [row] = await tx.select({ value: runtimeOperationalMetrics.metric }).from(runtimeOperationalMetrics).where(eq(runtimeOperationalMetrics.id, input.aggregate.id)).for("update"); if (receipt) return receipt.requestDigest === input.requestDigest && row ? { kind: "replayed" as const, aggregate: metric(row.value) } : { kind: "conflict" as const }; const [retention] = await tx.select({ value: runtimeObservabilityRetentionRevisions.revisionRecord }).from(runtimeObservabilityRetentionPolicies).innerJoin(runtimeObservabilityRetentionRevisions, eq(runtimeObservabilityRetentionRevisions.id, runtimeObservabilityRetentionPolicies.currentRevisionId)).where(eq(runtimeObservabilityRetentionPolicies.workspaceId, input.aggregate.workspaceId)).limit(1); if (!retention || input.aggregate.expiresAt.getTime() > input.aggregate.recordedAt.getTime() + retentionRevision(retention.value).metricTtlSeconds * 1000) return { kind: "conflict" as const }; const next = row ? { ...metric(row.value), count: metric(row.value).count + input.countDelta, sum: metric(row.value).sum + input.sumDelta, recordedAt: input.aggregate.recordedAt, expiresAt: input.aggregate.expiresAt } : input.aggregate; if (row) await tx.update(runtimeOperationalMetrics).set({ metric: next, expiresAt: next.expiresAt, createdAt: next.recordedAt }).where(eq(runtimeOperationalMetrics.id, next.id)); else await tx.insert(runtimeOperationalMetrics).values({ id: next.id, workspaceId: next.workspaceId, name: next.name, metric: next, windowStartsAt: next.windowStartsAt, windowEndsAt: next.windowEndsAt, expiresAt: next.expiresAt, createdAt: next.recordedAt }); await tx.insert(runtimeOperationalMetricDeltaReceipts).values({ workspaceId: next.workspaceId, eventId: input.eventId, requestDigest: input.requestDigest, aggregateId: next.id, createdAt: input.aggregate.recordedAt }); return { kind: "applied" as const, aggregate: next }; }).catch(() => ({ kind: "unavailable" as const })); }
  async listMetrics(input: { workspaceId: string; cursor: { recordedAt: Date; id: string } | null; limit: number; at: Date }) { const cursorClause = input.cursor ? or(gt(runtimeOperationalMetrics.createdAt, input.cursor.recordedAt), and(eq(runtimeOperationalMetrics.createdAt, input.cursor.recordedAt), gt(runtimeOperationalMetrics.id, input.cursor.id))) : undefined; const rows = await this.database().select({ value: runtimeOperationalMetrics.metric }).from(runtimeOperationalMetrics).where(and(eq(runtimeOperationalMetrics.workspaceId, input.workspaceId), gt(runtimeOperationalMetrics.expiresAt, input.at), cursorClause)).orderBy(asc(runtimeOperationalMetrics.createdAt), asc(runtimeOperationalMetrics.id)).limit(input.limit); return rows.map((row) => metric(row.value)); }
  appendTrace(value: DiagnosticTrace) { return this.database().transaction(async (tx) => { await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`runtime-observability:${value.workspaceId}`}, 0))`); const [retention] = await tx.select({ value: runtimeObservabilityRetentionRevisions.revisionRecord }).from(runtimeObservabilityRetentionPolicies).innerJoin(runtimeObservabilityRetentionRevisions, eq(runtimeObservabilityRetentionRevisions.id, runtimeObservabilityRetentionPolicies.currentRevisionId)).where(eq(runtimeObservabilityRetentionPolicies.workspaceId, value.workspaceId)).limit(1); if (!retention || value.expiresAt.getTime() > value.createdAt.getTime() + retentionRevision(retention.value).traceTtlSeconds * 1000) return "conflict" as const; await tx.insert(runtimeDiagnosticTraces).values({ operatorTraceRef: value.operatorTraceRef, workspaceId: value.workspaceId, trace: value, createdAt: value.createdAt, expiresAt: value.expiresAt }); return "created" as const; }).catch(() => "conflict" as const); }
  async getTrace(workspaceId: string, ref: string, at: Date) { const [row] = await this.database().select({ value: runtimeDiagnosticTraces.trace }).from(runtimeDiagnosticTraces).where(and(eq(runtimeDiagnosticTraces.workspaceId, workspaceId), eq(runtimeDiagnosticTraces.operatorTraceRef, ref), sql`${runtimeDiagnosticTraces.expiresAt} > ${at}`)).limit(1); return row ? trace(row.value) : null; }
  async appendTraceAccessAudit(value: DiagnosticTraceAccessAuditEvent) { await this.database().insert(runtimeDiagnosticTraceAccessAudits).values({ id: value.id, workspaceId: value.workspaceId, operatorTraceRef: value.operatorTraceRef, operatorId: value.operatorId, outcome: value.outcome, audit: value, occurredAt: value.occurredAt }); }
  appendOperatorGrant(input: { grant: WorkspaceTelemetryOperatorGrant; idempotencyKey: string; digest: string; audit: OperatorGrantAuditEvent }) { return this.database().transaction(async (tx) => { await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`runtime-observability:${input.grant.workspaceId}`}, 0))`); const key = `grant:${input.idempotencyKey}`; const [receipt] = await tx.select().from(runtimeObservabilityAdminReceipts).where(and(eq(runtimeObservabilityAdminReceipts.workspaceId, input.grant.workspaceId), eq(runtimeObservabilityAdminReceipts.idempotencyKey, key))).limit(1); if (receipt) return receipt.requestDigest === input.digest ? "replayed" as const : "conflict" as const; await tx.insert(runtimeTelemetryOperatorGrants).values({ id: input.grant.id, workspaceId: input.grant.workspaceId, operatorId: input.grant.operatorId, status: input.grant.status, grant: input.grant, issuedAt: input.grant.issuedAt, expiresAt: input.grant.expiresAt, revokedAt: null }); await tx.insert(runtimeTelemetryOperatorGrantAudits).values({ id: input.audit.id, workspaceId: input.audit.workspaceId, grantId: input.audit.grantId, eventType: input.audit.eventType, audit: input.audit, occurredAt: input.audit.occurredAt }); await tx.insert(runtimeObservabilityAdminReceipts).values({ workspaceId: input.grant.workspaceId, idempotencyKey: key, requestDigest: input.digest, resourceId: input.grant.id, createdAt: input.grant.issuedAt }); return "created" as const; }).catch(() => "unavailable" as const); }
  async getOperatorGrant(workspaceId: string, grantId: string) { const [row] = await this.database().select({ value: runtimeTelemetryOperatorGrants.grant }).from(runtimeTelemetryOperatorGrants).where(and(eq(runtimeTelemetryOperatorGrants.workspaceId, workspaceId), eq(runtimeTelemetryOperatorGrants.id, grantId))).limit(1); return row ? grant(row.value) : null; }
  async listOperatorGrants(input: { workspaceId: string; operatorId: string; at: Date; limit: number }) { const rows = await this.database().select({ value: runtimeTelemetryOperatorGrants.grant }).from(runtimeTelemetryOperatorGrants).where(and(eq(runtimeTelemetryOperatorGrants.workspaceId, input.workspaceId), eq(runtimeTelemetryOperatorGrants.operatorId, input.operatorId), eq(runtimeTelemetryOperatorGrants.status, "active"), gt(runtimeTelemetryOperatorGrants.expiresAt, input.at))).orderBy(asc(runtimeTelemetryOperatorGrants.expiresAt), asc(runtimeTelemetryOperatorGrants.id)).limit(input.limit); return rows.map((row) => grant(row.value)); }
  revokeOperatorGrant(input: { workspaceId: string; grantId: string; revokedByUserId: string; revokedAt: Date; audit: OperatorGrantAuditEvent }) { return this.database().transaction(async (tx) => { const [row] = await tx.select().from(runtimeTelemetryOperatorGrants).where(and(eq(runtimeTelemetryOperatorGrants.workspaceId, input.workspaceId), eq(runtimeTelemetryOperatorGrants.id, input.grantId))).for("update"); if (!row) return "conflict" as const; const current = grant(row.grant); if (current.status === "revoked") return current.revokedByUserId === input.revokedByUserId ? "replayed" as const : "conflict" as const; const next: WorkspaceTelemetryOperatorGrant = { ...current, status: "revoked", revokedAt: input.revokedAt, revokedByUserId: input.revokedByUserId }; await tx.update(runtimeTelemetryOperatorGrants).set({ status: next.status, grant: next, revokedAt: next.revokedAt }).where(eq(runtimeTelemetryOperatorGrants.id, next.id)); await tx.insert(runtimeTelemetryOperatorGrantAudits).values({ id: input.audit.id, workspaceId: input.workspaceId, grantId: input.grantId, eventType: input.audit.eventType, audit: input.audit, occurredAt: input.audit.occurredAt }).onConflictDoNothing(); return "created" as const; }); }
  createSupportBundle(input: { bundle: SupportBundleRecord; audit: SupportBundleAuditEvent; idempotencyKey: string; digest: string; bindIntentRequestDigest?: `sha256:${string}` }) { return this.database().transaction(async (tx) => {
    await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`runtime-observability:${input.bundle.workspaceId}`}, 0))`);
    const [receipt] = await tx.select().from(runtimeSupportBundleReceipts).where(and(eq(runtimeSupportBundleReceipts.workspaceId, input.bundle.workspaceId), eq(runtimeSupportBundleReceipts.idempotencyKey, input.idempotencyKey))).limit(1);
    if (receipt) return receipt.requestDigest === input.digest ? "replayed" as const : "conflict" as const;
    if (input.bindIntentRequestDigest) {
      const [intentRow] = await tx.select().from(runtimeSupportBundleBindIntents).where(and(eq(runtimeSupportBundleBindIntents.workspaceId, input.bundle.workspaceId), eq(runtimeSupportBundleBindIntents.idempotencyKey, input.idempotencyKey))).for("update");
      if (!intentRow) return "conflict" as const;
      const bindIntent: SupportBundleBindIntent = { schema: "support-bundle-bind-intent/v1", id: intentRow.id, workspaceId: intentRow.workspaceId, idempotencyKey: intentRow.idempotencyKey, requestDigest: intentRow.requestDigest as `sha256:${string}`, state: intentRow.state as SupportBundleBindIntent["state"], selections: structuredClone(intentRow.selections), consent: { ...structuredClone(intentRow.consent), grantedAt: date(intentRow.consent.grantedAt), expiresAt: date(intentRow.consent.expiresAt) }, contentDigest: intentRow.contentDigest as `sha256:${string}`, sizeBytes: intentRow.sizeBytes, storageKey: intentRow.storageKey, payloadJson: intentRow.payloadJson, bundleId: intentRow.bundleId, createdAt: date(intentRow.createdAt), updatedAt: date(intentRow.updatedAt) };
      if (!supportBundleIntentMatchesRecord({ intent: bindIntent, bundle: input.bundle, idempotencyKey: input.idempotencyKey, requestDigest: input.bindIntentRequestDigest })) return "conflict" as const;
    }
    const [retention] = await tx.select({ value: runtimeObservabilityRetentionRevisions.revisionRecord }).from(runtimeObservabilityRetentionPolicies).innerJoin(runtimeObservabilityRetentionRevisions, eq(runtimeObservabilityRetentionRevisions.id, runtimeObservabilityRetentionPolicies.currentRevisionId)).where(eq(runtimeObservabilityRetentionPolicies.workspaceId, input.bundle.workspaceId)).limit(1);
    if (!retention || input.bundle.expiresAt.getTime() > input.bundle.createdAt.getTime() + retentionRevision(retention.value).supportBundleTtlSeconds * 1000) return "conflict" as const;
    await tx.insert(runtimeSupportBundles).values({ id: input.bundle.id, workspaceId: input.bundle.workspaceId, state: input.bundle.state, bundle: input.bundle, storageKey: input.bundle.storageKey, contentDigest: input.bundle.contentDigest, sizeBytes: input.bundle.sizeBytes, createdAt: input.bundle.createdAt, expiresAt: input.bundle.expiresAt, storedAt: input.bundle.storedAt });
    await tx.insert(runtimeSupportBundleAuditEvents).values({ id: input.audit.id, workspaceId: input.audit.workspaceId, bundleId: input.audit.bundleId, eventType: input.audit.eventType, audit: input.audit, occurredAt: input.audit.occurredAt });
    await tx.insert(runtimeSupportBundleReceipts).values({ workspaceId: input.bundle.workspaceId, idempotencyKey: input.idempotencyKey, requestDigest: input.digest, bundleId: input.bundle.id, createdAt: input.bundle.createdAt });
    if (input.bindIntentRequestDigest) {
      const [bound] = await tx.update(runtimeSupportBundleBindIntents).set({ state: "bound", payloadJson: null, bundleId: input.bundle.id, updatedAt: sql`${runtimeSupportBundleBindIntents.updatedAt}` }).where(and(eq(runtimeSupportBundleBindIntents.workspaceId, input.bundle.workspaceId), eq(runtimeSupportBundleBindIntents.idempotencyKey, input.idempotencyKey), eq(runtimeSupportBundleBindIntents.requestDigest, input.bindIntentRequestDigest), eq(runtimeSupportBundleBindIntents.state, "pending"))).returning({ id: runtimeSupportBundleBindIntents.id });
      if (!bound) throw new Error("support bundle bind intent transition conflict");
    }
    return "created" as const;
  }).catch(() => "unavailable" as const); }
  async getSupportBundle(workspaceId: string, bundleId: string, at: Date) { const [row] = await this.database().select({ value: runtimeSupportBundles.bundle }).from(runtimeSupportBundles).where(and(eq(runtimeSupportBundles.workspaceId, workspaceId), eq(runtimeSupportBundles.id, bundleId), sql`${runtimeSupportBundles.expiresAt} > ${at}`, sql`${runtimeSupportBundles.state} not in ('expired', 'revoked')`)).limit(1); return row ? bundle(row.value) : null; }
  async getSupportBundleRecord(workspaceId: string, bundleId: string) { const [row] = await this.database().select({ value: runtimeSupportBundles.bundle }).from(runtimeSupportBundles).where(and(eq(runtimeSupportBundles.workspaceId, workspaceId), eq(runtimeSupportBundles.id, bundleId))).limit(1); return row ? bundle(row.value) : null; }
  revokeSupportBundle(input: { workspaceId: string; bundleId: string; actorUserId: string; revokedAt: Date; audit: SupportBundleAuditEvent }) { return this.database().transaction(async (tx) => { const [row] = await tx.select().from(runtimeSupportBundles).where(and(eq(runtimeSupportBundles.workspaceId, input.workspaceId), eq(runtimeSupportBundles.id, input.bundleId))).for("update"); if (!row) return "conflict" as const; const current = bundle(row.bundle); if (current.state === "revoked") return "replayed" as const; if (current.state === "expired") return "conflict" as const; const next: SupportBundleRecord = { ...current, state: "revoked" }; await tx.update(runtimeSupportBundles).set({ state: "revoked", bundle: next }).where(eq(runtimeSupportBundles.id, row.id)); await tx.insert(runtimeSupportBundleAuditEvents).values({ id: input.audit.id, workspaceId: input.workspaceId, bundleId: input.bundleId, eventType: input.audit.eventType, audit: input.audit, occurredAt: input.revokedAt }).onConflictDoNothing(); return "created" as const; }); }
  async listSupportBundleAudit(input: { workspaceId: string; bundleId: string; limit: number }) { const lifecycleRows = await this.database().select({ value: runtimeSupportBundleAuditEvents.audit }).from(runtimeSupportBundleAuditEvents).where(and(eq(runtimeSupportBundleAuditEvents.workspaceId, input.workspaceId), eq(runtimeSupportBundleAuditEvents.bundleId, input.bundleId))).orderBy(asc(runtimeSupportBundleAuditEvents.occurredAt), asc(runtimeSupportBundleAuditEvents.id)).limit(input.limit); const accessRows = await this.database().select({ value: runtimeSupportBundleAccessAudits.audit }).from(runtimeSupportBundleAccessAudits).where(and(eq(runtimeSupportBundleAccessAudits.workspaceId, input.workspaceId), eq(runtimeSupportBundleAccessAudits.bundleId, input.bundleId))).orderBy(asc(runtimeSupportBundleAccessAudits.occurredAt), asc(runtimeSupportBundleAccessAudits.id)).limit(input.limit); const lifecycle = lifecycleRows.map((row) => ({ ...structuredClone(row.value), occurredAt: date(row.value.occurredAt) })); const access = accessRows.map((row): SupportBundleAuditEvent => ({ schema: "support-bundle-audit-event/v1", id: row.value.id, workspaceId: row.value.workspaceId, bundleId: row.value.bundleId, eventType: row.value.outcome === "granted" ? "bundle.read" : "bundle.read_denied", actorType: "operator", actorId: row.value.operatorId, occurredAt: date(row.value.occurredAt) })); return [...lifecycle, ...access].sort((a, b) => a.occurredAt.getTime() - b.occurredAt.getTime() || a.id.localeCompare(b.id)).slice(0, input.limit); }
  async appendSupportBundleAccessAudit(value: SupportBundleAccessAuditEvent) { await this.database().insert(runtimeSupportBundleAccessAudits).values({ id: value.id, workspaceId: value.workspaceId, bundleId: value.bundleId, operatorId: value.operatorId, outcome: value.outcome, audit: value, occurredAt: value.occurredAt }); }
  async listSupportBundleCleanup(input: { at: Date; limit: number }) { const rows = await this.database().select({ bundleId: runtimeSupportBundles.id, workspaceId: runtimeSupportBundles.workspaceId, storageKey: runtimeSupportBundles.storageKey, contentDigest: runtimeSupportBundles.contentDigest }).from(runtimeSupportBundles).where(and(sql`${runtimeSupportBundles.state} in ('expired','revoked')`, sql`${runtimeSupportBundles.storageKey} is not null`, sql`${runtimeSupportBundles.contentDigest} is not null`, sql`not exists (select 1 from runtime_support_bundles active where active.state = 'stored' and active.expires_at > ${input.at} and active.storage_key = ${runtimeSupportBundles.storageKey})`)).orderBy(asc(runtimeSupportBundles.expiresAt), asc(runtimeSupportBundles.id)).limit(input.limit); return rows.map((row) => ({ bundleId: row.bundleId, workspaceId: row.workspaceId, storageKey: row.storageKey!, contentDigest: row.contentDigest! as `sha256:${string}` })); }
  acknowledgeSupportBundleCleanup(input: { bundleId: string; workspaceId: string; storageKey: string; contentDigest: `sha256:${string}` }) { return this.database().transaction(async (tx) => { const [row] = await tx.select().from(runtimeSupportBundles).where(and(eq(runtimeSupportBundles.workspaceId, input.workspaceId), eq(runtimeSupportBundles.id, input.bundleId))).for("update"); if (!row || row.state === "stored") return "conflict" as const; if (!row.storageKey && !row.contentDigest) return "replayed" as const; if (row.storageKey !== input.storageKey || row.contentDigest !== input.contentDigest) return "conflict" as const; const current = bundle(row.bundle); await tx.update(runtimeSupportBundles).set({ storageKey: null, contentDigest: null, bundle: { ...current, storageKey: null, contentDigest: null } }).where(eq(runtimeSupportBundles.id, row.id)); return "cleared" as const; }); }
  expire(at: Date, limit: number) { return this.database().transaction(async (tx) => {
    const traceRows = await tx.select({ id: runtimeDiagnosticTraces.operatorTraceRef }).from(runtimeDiagnosticTraces).where(lte(runtimeDiagnosticTraces.expiresAt, at)).orderBy(asc(runtimeDiagnosticTraces.expiresAt), asc(runtimeDiagnosticTraces.operatorTraceRef)).limit(limit).for("update", { skipLocked: true });
    if (traceRows.length) await tx.delete(runtimeDiagnosticTraces).where(inArray(runtimeDiagnosticTraces.operatorTraceRef, traceRows.map((row) => row.id)));
    const metricRows = await tx.select({ id: runtimeOperationalMetrics.id }).from(runtimeOperationalMetrics).where(lte(runtimeOperationalMetrics.expiresAt, at)).orderBy(asc(runtimeOperationalMetrics.expiresAt), asc(runtimeOperationalMetrics.id)).limit(limit).for("update", { skipLocked: true });
    if (metricRows.length) await tx.delete(runtimeOperationalMetrics).where(inArray(runtimeOperationalMetrics.id, metricRows.map((row) => row.id)));
    const bundleRows = await tx.select().from(runtimeSupportBundles).where(and(lte(runtimeSupportBundles.expiresAt, at), sql`${runtimeSupportBundles.state} not in ('expired', 'revoked')`)).orderBy(asc(runtimeSupportBundles.expiresAt), asc(runtimeSupportBundles.id)).limit(limit).for("update", { skipLocked: true });
    for (const row of bundleRows) { const next = { ...bundle(row.bundle), state: "expired" as const }; await tx.update(runtimeSupportBundles).set({ state: "expired", bundle: next }).where(eq(runtimeSupportBundles.id, row.id)); const audit: SupportBundleAuditEvent = { schema: "support-bundle-audit-event/v1", id: `expire:${row.id}`, workspaceId: row.workspaceId, bundleId: row.id, eventType: "bundle.expired", actorType: "system", actorId: null, occurredAt: at }; await tx.insert(runtimeSupportBundleAuditEvents).values({ id: audit.id, workspaceId: audit.workspaceId, bundleId: audit.bundleId, eventType: audit.eventType, audit, occurredAt: at }).onConflictDoNothing(); }
    const grantRows = await tx.select().from(runtimeTelemetryOperatorGrants).where(and(lte(runtimeTelemetryOperatorGrants.expiresAt, at), eq(runtimeTelemetryOperatorGrants.status, "active"))).orderBy(asc(runtimeTelemetryOperatorGrants.expiresAt), asc(runtimeTelemetryOperatorGrants.id)).limit(limit).for("update", { skipLocked: true });
    for (const row of grantRows) { const next = { ...grant(row.grant), status: "expired" as const }; await tx.update(runtimeTelemetryOperatorGrants).set({ status: "expired", grant: next }).where(eq(runtimeTelemetryOperatorGrants.id, row.id)); const audit: OperatorGrantAuditEvent = { schema: "operator-grant-audit-event/v1", id: `expire:${row.id}`, workspaceId: row.workspaceId, grantId: row.id, eventType: "grant.expired", actorType: "system", actorId: null, occurredAt: at }; await tx.insert(runtimeTelemetryOperatorGrantAudits).values({ id: audit.id, workspaceId: audit.workspaceId, grantId: audit.grantId, eventType: audit.eventType, audit, occurredAt: at }).onConflictDoNothing(); }
    return { traces: traceRows.length, metrics: metricRows.length, bundles: bundleRows.length, grants: grantRows.length };
  }); }
}
