import { createHmac, timingSafeEqual } from "node:crypto";
import { canonicalDigest } from "@/lib/agent-tools/canonical";
import type { OperationKind, OperationState } from "./types";

interface Payload { v: 1; workspaceId: string; filterDigest: string; updatedAt: string; id: string }
export class InvalidOperationCursorError extends Error { constructor() { super("Operation cursor is invalid or unavailable."); this.name = "InvalidOperationCursorError"; } }
export const operationFilterDigest = (states?: OperationState[], kinds?: OperationKind[]) => canonicalDigest({ states: states ? [...states].sort() : [], kinds: kinds ? [...kinds].sort() : [], order: "updated_at_desc_id_desc" });
function key(secret: string) { if (Buffer.byteLength(secret) < 32) throw new Error("OPERATION_CURSOR_SECRET must contain at least 32 bytes."); return secret; }
export function sealOperationCursor(input: { workspaceId: string; filterDigest: string; updatedAt: Date; id: string; secret: string }) { const payload: Payload = { v: 1, workspaceId: input.workspaceId, filterDigest: input.filterDigest, updatedAt: input.updatedAt.toISOString(), id: input.id }; const encoded = Buffer.from(JSON.stringify(payload)).toString("base64url"); const signature = createHmac("sha256", key(input.secret)).update(encoded).digest("base64url"); return `opc1.${encoded}.${signature}`; }
export function openOperationCursor(input: { cursor: string; workspaceId: string; filterDigest: string; secret: string }): { updatedAt: Date; id: string } {
  try { if (input.cursor.length > 2_048) throw new InvalidOperationCursorError(); const [prefix, encoded, signature, extra] = input.cursor.split("."); if (prefix !== "opc1" || !encoded || !signature || extra) throw new InvalidOperationCursorError(); const expected = createHmac("sha256", key(input.secret)).update(encoded).digest(); const actual = Buffer.from(signature, "base64url"); if (actual.length !== expected.length || !timingSafeEqual(actual, expected)) throw new InvalidOperationCursorError(); const parsed = JSON.parse(Buffer.from(encoded, "base64url").toString("utf8")) as Partial<Payload>; const updatedAt = typeof parsed.updatedAt === "string" ? new Date(parsed.updatedAt) : null; if (parsed.v !== 1 || parsed.workspaceId !== input.workspaceId || parsed.filterDigest !== input.filterDigest || !updatedAt || !Number.isFinite(updatedAt.getTime()) || updatedAt.toISOString() !== parsed.updatedAt || typeof parsed.id !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}$/.test(parsed.id)) throw new InvalidOperationCursorError(); return { updatedAt, id: parsed.id }; } catch (error) { if (error instanceof InvalidOperationCursorError) throw error; throw new InvalidOperationCursorError(); }
}
