"use client";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useLocale, useTranslations } from "next-intl";
import { CircleCheck, LoaderCircle, ShieldCheck } from "lucide-react";
import { getActiveWorkspaceId } from "@/lib/studio/client";

type Offer = { offerId: string; version: number; platform: string; authoredName: { ar: string; en: string }; authoredDescription: { ar: string; en: string }; supportedRegions: string[]; customerRequirements: string[]; localPriceMinor: number; currency: string; termsDigest: string; compliancePolicyVersion: string };
type Order = { id: string; platform: string; region: string; state: string; revision: number; quoteId: string | null; credentialProfileId: string | null; connectedSocialAccountId: string | null; updatedAt: string };
type Quote = { id: string; totalMinor: number; currency: string; expiresAt: string; state: string };
type Task = { id: string; orderId: string; actorKind: string; kind: string; status: string; instructions: { ar: string; en: string }; dueAt: string | null };
type Summary = { offers: Offer[]; orders: Order[]; quotes: Quote[]; tasks: Task[]; profiles: Array<{ id: string; name: string; provider: string; activeVersion: number }>; channels: Array<{ id: string; displayName: string; platform: string }> };

export function ChannelOnboardingManager() {
  const t = useTranslations("product.channelOnboarding") as (key: string, values?: Record<string, string | number>) => string;
  const locale = useLocale() as "ar" | "en"; const [data, setData] = useState<Summary | null>(null); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { const workspaceId = getActiveWorkspaceId(); if (!workspaceId) throw new Error("WORKSPACE_REQUIRED"); const response = await fetch("/api/studio/channel-onboarding", { headers: { "x-workspace-id": workspaceId }, cache: "no-store" }); const body = await response.json() as { data?: Summary; code?: string }; if (!response.ok || !body.data) throw new Error(body.code ?? "REQUEST_FAILED"); setData(body.data); }, []);
  useEffect(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : "REQUEST_FAILED")); }, [load]);
  async function command(body: Record<string, unknown>) { const workspaceId = getActiveWorkspaceId(); if (!workspaceId) return; setBusy(String(body.action)); setError(""); try { const response = await fetch("/api/studio/channel-onboarding", { method: "POST", headers: { "content-type": "application/json", "x-workspace-id": workspaceId }, body: JSON.stringify({ ...body, idempotencyKey: crypto.randomUUID() }) }); const result = await response.json() as { success: boolean; code?: string }; if (!response.ok || !result.success) throw new Error(result.code ?? "REQUEST_FAILED"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "REQUEST_FAILED"); } finally { setBusy(""); } }
  if (!data) return <div className="p-8">{error ? <p role="alert">{t(`errors.${error}`)}</p> : <LoaderCircle className="size-5 animate-spin" aria-label={t("loading")} />}</div>;
  return <div className="space-y-8">
    {error && <p role="alert" className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{t(`errors.${error}`)}</p>}
    <section><h2 className="text-xl font-semibold">{t("offers")}</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{data.offers.map((offer) => <article key={`${offer.offerId}:${offer.version}`} className="rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{offer.authoredName[locale]}</h3><p className="mt-1 text-sm text-muted-foreground">{offer.authoredDescription[locale]}</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs">{t(`platforms.${offer.platform}`)}</span></div><p className="mt-4 text-xl font-semibold">{new Intl.NumberFormat(locale, { style: "currency", currency: offer.currency }).format(offer.localPriceMinor / 100)}</p><ul className="mt-3 space-y-1 text-xs text-muted-foreground">{offer.customerRequirements.map((requirement) => <li key={requirement}>• <bdi>{requirement}</bdi></li>)}</ul><form className="mt-5 grid gap-3" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void command({ action: "create_order", offerId: offer.offerId, offerVersion: offer.version, region: String(form.get("region")), compliancePolicyAccepted: form.get("accepted") === "on" }); }}><label className="grid gap-2 text-sm font-medium">{t("region")}<select name="region" className="min-h-11 rounded-xl border bg-background px-3">{offer.supportedRegions.map((region) => <option key={region}>{region}</option>)}</select></label><label className="flex items-start gap-2 text-xs"><input required name="accepted" type="checkbox" className="mt-0.5" /><span>{t("acceptCompliance", { policy: offer.compliancePolicyVersion })}</span></label><button disabled={Boolean(busy)} className="min-h-11 rounded-xl bg-amber-300 px-4 text-sm font-semibold text-stone-950">{t("requestQuote")}</button></form></article>)}</div>{data.offers.length === 0 && <p className="mt-4 rounded-xl border border-dashed p-8 text-center text-muted-foreground">{t("noOffers")}</p>}</section>
    <section><h2 className="text-xl font-semibold">{t("orders")}</h2><div className="mt-4 grid gap-4">{data.orders.map((order) => { const quote = data.quotes.find((item) => item.id === order.quoteId); const tasks = data.tasks.filter((item) => item.orderId === order.id && item.status === "open"); return <article key={order.id} className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{t(`platforms.${order.platform}`)} · <bdi>{order.region}</bdi></h3><p className="text-xs text-muted-foreground">{t("revision", { revision: order.revision })}</p></div><span className="rounded-full bg-muted px-3 py-1 text-xs">{t(`states.${order.state}`)}</span></div>{quote && <p className="mt-4 text-sm">{t("quote", { amount: new Intl.NumberFormat(locale, { style: "currency", currency: quote.currency }).format(quote.totalMinor / 100), state: t(`quoteStates.${quote.state}`) })}</p>}
      {order.state === "quoted" && <button disabled={Boolean(busy)} onClick={() => void command({ action: "accept_quote", orderId: order.id, expectedRevision: order.revision })} className="mt-4 min-h-10 rounded-lg bg-amber-300 px-4 text-sm font-semibold text-stone-950">{t("acceptQuote")}</button>}{order.state === "payment_pending" && <p className="mt-4 rounded-lg bg-muted p-3 text-sm">{t("paymentPending")}</p>}
      {tasks.map((task) => <form key={task.id} className="mt-4 rounded-xl border p-4" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void command({ action: "complete_customer_task", orderId: order.id, taskId: task.id, expectedRevision: order.revision, evidenceNote: String(form.get("evidenceNote")) }); }}><p className="font-medium">{task.instructions[locale]}</p><label className="mt-3 grid gap-2 text-sm">{t("completionEvidence")}<textarea required name="evidenceNote" maxLength={2000} className="min-h-24 rounded-lg border bg-background p-3" /></label><button className="mt-3 min-h-10 rounded-lg border px-4 text-sm">{t("completeTask")}</button></form>)}
      {["accepted", "customer_action", "blocked"].includes(order.state) && !order.credentialProfileId && <form className="mt-4 grid gap-3 rounded-xl border p-4 sm:grid-cols-[1fr_auto]" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void command({ action: "bind_credential", orderId: order.id, expectedRevision: order.revision, credentialProfileId: String(form.get("profileId")) }); }}><label className="grid gap-2 text-sm">{t("credentialProfile")}<select required name="profileId" className="min-h-10 rounded-lg border bg-background px-3"><option value="">{t("selectCredential")}</option>{data.profiles.filter((profile) => profile.provider === order.platform).map((profile) => <option key={profile.id} value={profile.id}>{profile.name} · v{profile.activeVersion}</option>)}</select></label><button className="self-end min-h-10 rounded-lg border px-4 text-sm">{t("bindCredential")}</button><p className="text-xs text-muted-foreground sm:col-span-2"><ShieldCheck className="me-1 inline size-4" />{t("credentialBoundary")} <Link href="/settings?section=providers" className="underline">{t("openVault")}</Link></p></form>}
      {order.credentialProfileId && <p className="mt-4 text-sm text-emerald-700"><CircleCheck className="me-1 inline size-4" />{t("credentialReady")}</p>}
      {order.state === "ready_to_connect" && <form className="mt-4 flex gap-3" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void command({ action: "connect_channel", orderId: order.id, expectedRevision: order.revision, socialAccountId: String(form.get("socialAccountId")) }); }}><select required name="socialAccountId" aria-label={t("socialAccountId")} className="min-h-10 flex-1 rounded-lg border bg-background px-3"><option value="">{t("selectChannel")}</option>{data.channels.filter((channel) => channel.platform === order.platform).map((channel) => <option key={channel.id} value={channel.id}>{channel.displayName}</option>)}</select><button className="min-h-10 rounded-lg bg-amber-300 px-4 text-sm font-semibold text-stone-950">{t("markConnected")}</button></form>}
      {!['connected', 'cancelled', 'refunded'].includes(order.state) && <button disabled={Boolean(busy)} onClick={() => void command({ action: "cancel", orderId: order.id, expectedRevision: order.revision, reasonCode: "customer.cancelled" })} className="mt-5 text-xs text-destructive">{t("cancel")}</button>}
    </article>; })}</div>{data.orders.length === 0 && <p className="mt-4 rounded-xl border border-dashed p-8 text-center text-muted-foreground">{t("noOrders")}</p>}</section>
    <aside className="rounded-2xl bg-muted p-5 text-sm"><h2 className="font-semibold">{t("safetyTitle")}</h2><p className="mt-2 text-muted-foreground">{t("safetyBoundary")}</p></aside>
  </div>;
}
