"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { Check, ExternalLink, LoaderCircle, ThumbsDown } from "lucide-react";
import { productRequest } from "@/components/product-surfaces/ProductApi";

type Item = { id: string; title: string; revision: number; payload: Record<string, unknown> };
export function BlitzClient({ items }: { items: Item[] }) { const t = useTranslations("product.blitzQueue"); const router = useRouter(); const [index, setIndex] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const item = items[index];
  async function decide(decision: "accepted" | "rejected") { if (!item) return; setBusy(true); setError(""); try { await productRequest("/api/blitz/decision", { itemId: item.id, expectedRevision: item.revision, decision, reasons: decision === "rejected" ? [t("notRelevant")] : [], idempotencyKey: crypto.randomUUID() }); if (index < items.length - 1) setIndex(index + 1); else router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("error")); } finally { setBusy(false); } }
  if (!item) return <div className="rounded-3xl border border-dashed p-12 text-center"><h2 className="text-xl font-semibold">{t("emptyTitle")}</h2><p className="mt-2 text-muted-foreground">{t("empty")}</p><Link href="/inspiration" className="mt-5 inline-flex rounded-xl bg-amber-300 px-5 py-3 font-semibold text-stone-950">{t("browse")}</Link></div>;
  const brief = item.payload.remixBrief as { influences: string[]; protectedExpressionExcluded: boolean };
  return <div className="mx-auto grid max-w-6xl gap-5 lg:grid-cols-[.8fr_1.2fr]"><aside className="rounded-3xl border bg-card p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-amber-600">{t("remixedFrom")}</p><h2 dir="auto" className="mt-3 text-xl font-semibold">{item.title}</h2><a href={String(item.payload.sourceAttribution)} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm text-amber-700"><ExternalLink className="size-4" />{t("viewOriginal")}</a><h3 className="mt-8 font-semibold">{t("influence")}</h3><div className="mt-3 flex flex-wrap gap-2">{brief.influences.map((value) => <span key={value} className="rounded-full bg-muted px-3 py-1.5 text-xs">{t(`influences.${value}`)}</span>)}</div><p className="mt-5 rounded-xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-900">{t("expressionExcluded")}</p></aside><section className="rounded-3xl bg-stone-950 p-6 text-white sm:p-8"><div className="mx-auto aspect-[9/16] max-h-[56vh] max-w-sm rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_50%_20%,rgba(251,191,36,.22),transparent_40%),linear-gradient(160deg,#292524,#0c0a09)] p-6 shadow-2xl"><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs">{t("proposal")}</span><h2 dir="auto" className="mt-10 text-3xl font-semibold leading-tight">{item.title}</h2><p dir="auto" className="mt-5 leading-7 text-stone-300">{String(item.payload.rationale)}</p></div><div className="mx-auto mt-5 grid max-w-sm grid-cols-2 gap-3"><button onClick={() => decide("rejected")} disabled={busy} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/15 bg-white/5 font-semibold"><ThumbsDown className="size-4" />{t("reject")}</button><button onClick={() => decide("accepted")} disabled={busy} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-amber-300 font-semibold text-stone-950">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Check className="size-4" />}{t("accept")}</button></div><p className="mt-4 text-center text-xs text-stone-500">{t("acceptanceBoundary")}</p>{error && <p role="alert" className="mt-3 text-center text-sm text-red-300">{error}</p>}</section></div>;
}

