import Link from "next/link";
import { BarChart3, Globe2, Heart, MessageCircle, Radar, Send } from "lucide-react";
import { getLocale, getTranslations } from "next-intl/server";
import { requireOnboardingComplete } from "@/lib/onboarding/server-access";
import { ANALYTICS_METRICS, getAudienceAnalytics, type AnalyticsMetric } from "@/lib/product-surfaces/analytics";
import { AnalyticsSourceActions } from "./AnalyticsSourceActions";
import { AnalyticsSourcesClient } from "./AnalyticsSourcesClient";

const ranges = [7, 30, 90] as const;
type Range = (typeof ranges)[number];
export const dynamic = "force-dynamic";

export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ range?: string; metric?: string }> }) {
  const query = await searchParams;
  const requested = Number(query.range);
  const days: Range = ranges.includes(requested as Range) ? requested as Range : 30;
  const selectedMetric = ANALYTICS_METRICS.includes(query.metric as AnalyticsMetric) ? query.metric as AnalyticsMetric : null;
  const { aggregate } = await requireOnboardingComplete("/analytics");
  const workspaceId = aggregate?.session.workspaceId;
  const t = await getTranslations("product.analytics");
  const locale = await getLocale();
  if (!workspaceId) return null;
  const analytics = await getAudienceAnalytics({ workspaceId, days, metric: selectedMetric });
  const number = new Intl.NumberFormat(locale, { notation: "compact", maximumFractionDigits: 1 });
  const date = new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" });
  const maxViews = Math.max(1, ...analytics.perDay.map((day) => day.views + day.websiteViews));

  return <main className="flex-1 px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl space-y-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-600">{t("eyebrow")}</p><h1 className="mt-2 text-3xl font-semibold sm:text-4xl">{t("title")}</h1><p className="mt-2 max-w-3xl text-muted-foreground">{t("description")}</p></div><div className="flex rounded-xl border bg-card p-1" aria-label={t("rangeLabel")}>{ranges.map((range) => <Link key={range} href={`/analytics?range=${range}`} aria-current={range === days ? "page" : undefined} className={`rounded-lg px-3 py-2 text-sm font-semibold ${range === days ? "bg-stone-950 text-white" : "text-muted-foreground"}`}>{t("days", { count: range })}</Link>)}</div></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">
      <Metric icon={BarChart3} label={t("metrics.views")} value={analytics.totals.views === null ? t("unknown") : number.format(analytics.totals.views)} href={`/analytics?range=${days}&metric=views`} />
      <Metric icon={Heart} label={t("metrics.likes")} value={analytics.totals.likes === null ? t("unknown") : number.format(analytics.totals.likes)} href={`/analytics?range=${days}&metric=likes`} />
      <Metric icon={MessageCircle} label={t("metrics.comments")} value={analytics.totals.comments === null ? t("unknown") : number.format(analytics.totals.comments)} href={`/analytics?range=${days}&metric=comments`} />
      <Metric icon={Send} label={t("metrics.posts")} value={number.format(analytics.totals.posts)} href={`/analytics?range=${days}&metric=posts`} />
      <Metric icon={Globe2} label={t("metrics.websiteViews")} value={analytics.totals.websiteViews === null ? t("unknown") : number.format(analytics.totals.websiteViews)} href={`/analytics?range=${days}&metric=websiteViews`} />
      <Metric icon={Radar} label={t("metrics.geoCitations")} value={analytics.totals.geoCitations === null ? t("unknown") : number.format(analytics.totals.geoCitations)} href={`/analytics?range=${days}&metric=geoCitations`} />
    </section>
    <section className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]">
      <div className="rounded-3xl border bg-card p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">{t("trendTitle")}</h2><p className="mt-1 text-sm text-muted-foreground">{t("trendHelp")}</p></div><p className="text-xs text-muted-foreground">{analytics.freshness ? t("freshness", { time: date.format(analytics.freshness) }) : t("noFreshness")}</p></div><div className="mt-8 flex h-52 items-end gap-1" role="img" aria-label={t("chartLabel")}>{analytics.perDay.map((day) => <div key={day.date} className="group relative flex min-w-0 flex-1 flex-col justify-end"><div className="w-full rounded-t-sm bg-amber-300 transition-colors group-hover:bg-amber-400" style={{ height: `${Math.max(2, ((day.views + day.websiteViews) / maxViews) * 100)}%` }} /><span className="sr-only">{t("chartDay", { date: day.date, views: day.views + day.websiteViews })}</span></div>)}</div><p className="mt-4 rounded-xl bg-muted p-3 text-xs leading-5 text-muted-foreground">{t("correlation")}</p></div>
      <div className="rounded-3xl border bg-card p-6"><h2 className="text-lg font-semibold">{t("platformTitle")}</h2><div className="mt-5 space-y-4">{analytics.platform.length ? analytics.platform.map((platform) => <div key={platform.id}><div className="flex justify-between gap-3 text-sm"><span>{platform.name || platform.platform}</span><span className="font-semibold">{t("postCount", { count: platform.posts })}</span></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-stone-900" style={{ width: `${analytics.totals.posts ? Math.max(3, platform.posts / analytics.totals.posts * 100) : 0}%` }} /></div></div>) : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">{t("emptyPlatforms")}</p>}</div></div>
    </section>
    <section className="rounded-3xl border bg-card p-6"><h2 className="text-xl font-semibold">{t("definitions.title")}</h2><p className="mt-1 text-sm text-muted-foreground">{t("definitions.description")}</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{ANALYTICS_METRICS.map((metric) => <article key={metric} className="rounded-xl bg-muted/50 p-4"><h3 className="font-semibold">{t(`metrics.${metric}`)}</h3><p className="mt-1 text-sm text-muted-foreground">{t(`definitions.metrics.${metric}`)}</p><p className="mt-2 text-xs text-muted-foreground">{t(`definitions.sources.${analytics.contracts[metric].source}`)} · {t("definitions.unitCount")}</p><p className="mt-1 text-xs text-muted-foreground">{t("definitions.comparison", { group: analytics.contracts[metric].comparisonGroup })}</p></article>)}</div></section>
    {analytics.selectedMetric && <section className="rounded-3xl border bg-card p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{t("drilldown.title", { metric: t(`metrics.${analytics.selectedMetric}`) })}</h2><p className="mt-1 text-sm text-muted-foreground">{t("drilldown.description")}</p></div><Link href={`/analytics?range=${days}`} className="text-sm font-semibold text-amber-700">{t("drilldown.close")}</Link></div><div className="mt-4 divide-y">{analytics.drilldown.length ? analytics.drilldown.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 py-3 text-sm"><div><p dir="auto" className="font-medium">{item.label}</p><p dir="auto" className="text-xs text-muted-foreground">{item.source} · {date.format(item.occurredAt)}</p></div><span className="font-semibold">{number.format(item.value)}</span></div>) : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">{t("drilldown.empty")}</p>}</div></section>}
    <section><div className="mb-4"><h2 className="text-xl font-semibold">{t("sources.title")}</h2><p className="mt-1 text-sm text-muted-foreground">{t("sources.description")}</p></div>{analytics.sources.length > 0 && <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{analytics.sources.map((source) => <article key={source.id} className="rounded-2xl border bg-card p-4"><div className="flex items-start justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-wide text-amber-700">{t(`sources.kinds.${source.kind}`)}</p><span className="rounded-full bg-muted px-2 py-1 text-xs">{t(`sources.verification.${source.payload.verificationStatus}`)}</span></div><h3 dir="auto" className="mt-2 font-semibold">{source.title}</h3><p className="mt-1 text-xs text-muted-foreground">{t(`states.${source.state}` as never)} · {t(`sources.refreshStatus.${source.payload.refreshStatus}`)}</p>{source.payload.verificationStatus !== "verified" && <div className="mt-3 rounded-xl bg-muted p-3"><p className="text-xs text-muted-foreground">{t("sources.challengeHelp")}</p><code dir="ltr" className="mt-1 block break-all text-xs">{source.payload.verificationChallenge}</code></div>}<p className="mt-3 text-xs text-muted-foreground">{source.payload.verifiedAt ? t("sources.verifiedAt", { time: date.format(new Date(source.payload.verifiedAt)) }) : t("sources.notVerified")}</p><AnalyticsSourceActions id={source.id} revision={source.revision} verified={source.payload.verificationStatus === "verified"} refreshPending={source.payload.refreshStatus === "queued" || source.payload.refreshStatus === "running"} /></article>)}</div>}<AnalyticsSourcesClient /></section>
  </div></main>;
}

function Metric({ icon: Icon, label, value, href }: { icon: typeof BarChart3; label: string; value: string; href: string }) { return <Link href={href} className="rounded-2xl border bg-card p-4 transition-colors hover:border-amber-300"><Icon className="size-5 text-muted-foreground" /><p className="mt-4 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></Link>; }
