#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
TOTAL_MINUTES=50
[[ "$ENV_FILE" == ".env" ]] && ENV_FILE=".env.local"
APP_BASE_URL="http://localhost:3002"
SECRETS_DIR=".local-secrets"
MODEL_SIGNING_KEY_ID="model-qualification-local-v1"
MODEL_SIGNING_PRIVATE_PATH="$SECRETS_DIR/$MODEL_SIGNING_KEY_ID.pem"

banner "Local Replicate qualification"

stage "Local cryptographic base" 4
say "Generate local-only vault and harness secrets, then bind every private observer to this app."
BYOK_KEY_ENCRYPTION_KEY=$(_existing BYOK_KEY_ENCRYPTION_KEY || true)
[[ "$BYOK_KEY_ENCRYPTION_KEY" =~ ^[a-f0-9]{64}$ ]] || BYOK_KEY_ENCRYPTION_KEY=$(openssl rand -hex 32)
QUALIFICATION_HARNESS_TOKEN=$(_existing QUALIFICATION_HARNESS_TOKEN || true)
[[ ${#QUALIFICATION_HARNESS_TOKEN} -ge 32 ]] || QUALIFICATION_HARNESS_TOKEN=$(openssl rand -hex 32)
write_env BYOK_KEY_ENCRYPTION_KEY "$BYOK_KEY_ENCRYPTION_KEY"
write_env QUALIFICATION_HARNESS_TOKEN "$QUALIFICATION_HARNESS_TOKEN"
write_env QUALIFICATION_WEBHOOK_OBSERVER_URL "$APP_BASE_URL/api/studio/internal/qualification-webhooks"
write_env QUALIFICATION_INGESTION_URL "$APP_BASE_URL/api/studio/internal/qualification-artifacts"
write_env QUALIFICATION_SPEND_OBSERVER_URL "$APP_BASE_URL/api/studio/internal/qualification-spend"
note "These are infrastructure secrets and local service URLs; none is an AI-provider credential."

stage "Dedicated Replicate qualification token" 5
say "Create a token used only for model-contract inspection and the explicitly confirmed qualification run."
open_url "https://replicate.com/account/api-tokens"
step "Create a separate token named 'Node Banana local qualification'. Do not reuse Workspace BYOK or the managed-production token."
ask_secret REPLICATE_QUALIFICATION_API_TOKEN "Paste the dedicated r8_ token:"
[[ "$REPLICATE_QUALIFICATION_API_TOKEN" == r8_* ]] || { warn "Replicate tokens are expected to start with r8_."; exit 1; }
write_env REPLICATE_QUALIFICATION_API_TOKEN "$REPLICATE_QUALIFICATION_API_TOKEN"
write_env REPLICATE_QUALIFICATION_API_BASE_URL "https://api.replicate.com/v1/"

stage "Replicate webhook verification" 4
say "Retrieve the signing secret belonging to that exact Replicate account. This GET does not create a prediction."
REPLICATE_WEBHOOK_SIGNING_SECRET=""
if command -v curl >/dev/null 2>&1 && command -v node >/dev/null 2>&1; then
  WEBHOOK_RESPONSE=$(curl -fsS -H "Authorization: Bearer $REPLICATE_QUALIFICATION_API_TOKEN" "https://api.replicate.com/v1/webhooks/default/secret" || true)
  REPLICATE_WEBHOOK_SIGNING_SECRET=$(printf '%s' "$WEBHOOK_RESPONSE" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const v=JSON.parse(s);if(typeof v.key==="string")process.stdout.write(v.key)}catch{}})' || true)
fi
if [[ -z "$REPLICATE_WEBHOOK_SIGNING_SECRET" ]]; then
  step "Run Replicate's documented GET /v1/webhooks/default/secret request, copy the key field, and return here."
  ask_secret REPLICATE_WEBHOOK_SIGNING_SECRET "Paste the whsec_ signing secret:"
fi
[[ "$REPLICATE_WEBHOOK_SIGNING_SECRET" == whsec_* ]] || { warn "The webhook signing secret is expected to start with whsec_."; exit 1; }
write_env REPLICATE_WEBHOOK_SIGNING_SECRET "$REPLICATE_WEBHOOK_SIGNING_SECRET"

stage "Public HTTPS webhook tunnel" 6
say "Replicate must reach the local completion receiver over HTTPS. Start a trusted tunnel to localhost:3002 in another terminal."
open_url "https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/trycloudflare/"
step "For a temporary Cloudflare tunnel, run: cloudflared tunnel --url http://localhost:3002"
ask QUALIFICATION_TUNNEL_ORIGIN "Paste the public HTTPS tunnel origin, without a trailing path:"
[[ "$QUALIFICATION_TUNNEL_ORIGIN" == https://* ]] || { warn "A public HTTPS origin is required."; exit 1; }
QUALIFICATION_TUNNEL_ORIGIN="${QUALIFICATION_TUNNEL_ORIGIN%/}"
write_env QUALIFICATION_WEBHOOK_URL "$QUALIFICATION_TUNNEL_ORIGIN/api/studio/webhooks/replicate-qualification"
note "Keep the tunnel running for the complete paid matrix and all webhook retries."

stage "Spend evidence signing authority" 4
say "Create a distinct Ed25519 key pair for reviewed-price authorizations and exact-charge receipts."
QUALIFICATION_SPEND_SIGNING_KEY_ID=$(_existing QUALIFICATION_SPEND_SIGNING_KEY_ID || true)
[[ -n "$QUALIFICATION_SPEND_SIGNING_KEY_ID" ]] || QUALIFICATION_SPEND_SIGNING_KEY_ID="qualification-spend-local-v1"
SPEND_PRIVATE=$(_existing QUALIFICATION_SPEND_SIGNING_PRIVATE_KEY || true)
SPEND_TRUST=$(_existing QUALIFICATION_SPEND_RECEIPT_PUBLIC_KEYS_JSON || true)
if [[ -z "$SPEND_PRIVATE" || -z "$SPEND_TRUST" ]]; then
  SPEND_PRIVATE_PATH=$(mktemp)
  SPEND_PUBLIC_PATH=$(mktemp)
  openssl genpkey -algorithm ED25519 -out "$SPEND_PRIVATE_PATH"
  openssl pkey -in "$SPEND_PRIVATE_PATH" -pubout -out "$SPEND_PUBLIC_PATH"
  SPEND_PRIVATE=$(awk '{printf "%s\\n",$0}' "$SPEND_PRIVATE_PATH")
  SPEND_PUBLIC=$(awk '{printf "%s\\n",$0}' "$SPEND_PUBLIC_PATH")
  SPEND_TRUST="{\"$QUALIFICATION_SPEND_SIGNING_KEY_ID\":\"$SPEND_PUBLIC\"}"
  rm -f "$SPEND_PRIVATE_PATH" "$SPEND_PUBLIC_PATH"
fi
write_env QUALIFICATION_SPEND_SIGNING_KEY_ID "$QUALIFICATION_SPEND_SIGNING_KEY_ID"
write_env QUALIFICATION_SPEND_SIGNING_PRIVATE_KEY "$SPEND_PRIVATE"
write_env QUALIFICATION_SPEND_RECEIPT_PUBLIC_KEYS_JSON "$SPEND_TRUST"

stage "Offline model-attestation key" 4
say "Create a separate key whose private half is never written to the runtime environment."
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"
if [[ ! -s "$MODEL_SIGNING_PRIVATE_PATH" ]]; then
  openssl genpkey -algorithm ED25519 -out "$MODEL_SIGNING_PRIVATE_PATH"
  chmod 600 "$MODEL_SIGNING_PRIVATE_PATH"
fi
MODEL_PUBLIC_PATH=$(mktemp)
openssl pkey -in "$MODEL_SIGNING_PRIVATE_PATH" -pubout -out "$MODEL_PUBLIC_PATH"
MODEL_PUBLIC=$(awk '{printf "%s\\n",$0}' "$MODEL_PUBLIC_PATH")
rm -f "$MODEL_PUBLIC_PATH"
write_env MODEL_QUALIFICATION_PUBLIC_KEYS_JSON "{\"$MODEL_SIGNING_KEY_ID\":\"$MODEL_PUBLIC\"}"
note "Private key retained locally at $MODEL_SIGNING_PRIVATE_PATH (mode 600, ignored by Git)."

stage "Provider processing-region evidence" 8
say "Replicate processing geography must come from a current provider disclosure, not from the model name or S3 region."
open_url "https://replicate.com/docs/topics/site-policy/subprocessors/"
ask PROVIDER_REGION_REPLICATE "Enter the exact conservative region label supported by the reviewed disclosure:"
[[ -n "$PROVIDER_REGION_REPLICATE" ]] || { warn "A reviewed provider region label is required."; exit 1; }
REGION_KEY_ID="region-key-local-v1"
REGION_TRUST=$(_existing GOVERNANCE_REGION_TRUST_KEYS || true)
if [[ -z "$REGION_TRUST" ]]; then
  REGION_KEY=$(openssl rand -base64 32 | tr -d '\n')
  REGION_TRUST="{\"$REGION_KEY_ID\":\"$REGION_KEY\"}"
fi
write_env PROVIDER_REGION_REPLICATE "$PROVIDER_REGION_REPLICATE"
write_env GOVERNANCE_REGION_TRUST_KEYS "$REGION_TRUST"
step "In another terminal run: pnpm governance:region-evidence -- --template > /tmp/node-banana-region-unsigned.json"
step "Replace every REVIEW_REQUIRED value and the placeholder source URL/digest using the disclosure you just reviewed."
step "Sign it with: pnpm governance:region-evidence -- /tmp/node-banana-region-unsigned.json > /tmp/node-banana-region-signed.json"
step "In Settings → Data and retention, complete step-up verification, paste the signed JSON, and activate it."
pause "Press Enter only after the signed region policy is active."

stage "Workspace BYOK credential" 5
say "Save the Workspace's normal Replicate token through the vault UI. It must not be the dedicated qualification token."
open_url "$APP_BASE_URL/settings?section=providers"
step "If the app is not running, start it in another terminal with: PORT=3002 pnpm dev"
step "Choose Replicate, request the step-up code, paste the Workspace/dev token, validate, and save."
pause "Press Enter after Settings confirms the Replicate credential is stored."

stage "Contract, reviewed plan, and explicit paid run" 10
say "Inspecting the contract is free. The final command can spend up to—but never including—USD 0.40 across the reviewed matrix."
ask QUALIFICATION_MODEL "Enter the curated Replicate owner/model to inspect:"
[[ "$QUALIFICATION_MODEL" =~ ^[^/]+/[^/]+$ ]] || { warn "Use exact owner/model syntax."; exit 1; }
CONTRACT_PATH="/tmp/node-banana-${QUALIFICATION_MODEL//\//-}-contract.json"
pnpm qualify:replicate:inspect "$QUALIFICATION_MODEL" > "$CONTRACT_PATH"
say "Contract report saved to $CONTRACT_PATH"
step "Using that report and docs/model-qualification-operations.md, prepare the bilingual Arabic/English, 9:16, cancellation, Brand-reference, license, pricing, and rights-reviewed plan. Set signingKeyId to '$MODEL_SIGNING_KEY_ID'."
ask QUALIFICATION_PLAN_PATH "Paste the reviewed plan JSON path:"
[[ -f "$QUALIFICATION_PLAN_PATH" ]] || { warn "Plan file not found."; exit 1; }
pnpm qualify:replicate:check "$QUALIFICATION_PLAN_PATH"
warn "The next run creates paid predictions. During it, use two other terminals for 'pnpm qualify:replicate:review -- --list' and 'pnpm qualify:replicate:spend -- --list'."
if ! confirm "Run this exact reviewed matrix now with the strict account-wide cap below USD 0.40?"; then
  SKIPPED+=("Paid model qualification; rerun this wizard when the exact plan is approved")
  finish
  exit 0
fi
QUALIFICATION_RESULT_PATH="/tmp/node-banana-qualification-result.json"
MODEL_QUALIFICATION_SIGNING_PRIVATE_KEY=$(awk '{printf "%s\\n",$0}' "$MODEL_SIGNING_PRIVATE_PATH") \
  pnpm qualify:replicate "$QUALIFICATION_PLAN_PATH" --execute-paid-smoke > "$QUALIFICATION_RESULT_PATH"
REPLICATE_MODEL_QUALIFICATIONS_JSON=$(node -e 'const fs=require("node:fs");const value=JSON.parse(fs.readFileSync(process.argv[1],"utf8"));process.stdout.write(JSON.stringify(value.envelope))' "$QUALIFICATION_RESULT_PATH")
write_env REPLICATE_MODEL_QUALIFICATIONS_JSON "$REPLICATE_MODEL_QUALIFICATIONS_JSON"
say "Signed runtime envelope stored; restart the app, then run pnpm doctor:local -- --workspace seed_ws_alice."

finish
note "No GitHub secrets were written: qualification is intentionally a local, operator-attended procedure."
note "Restart the app after environment changes. Re-run the readiness doctor before any customer generation."
