"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslations } from "next-intl";
import { RefreshCwIcon, ShieldCheckIcon, ShieldXIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { createFallbackAuthorization, getRoutingData, revokeFallbackAuthorization } from "@/lib/model-routing/client";
import type { FallbackAuthorization, ModelDescriptor } from "@/lib/model-routing/types";

export function ModelRoutingCockpit() {
  const t = useTranslations("modelRouting"); const [models, setModels] = useState<ModelDescriptor[]>([]); const [grants, setGrants] = useState<FallbackAuthorization[]>([]); const [source, setSource] = useState(""); const [target, setTarget] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(""); try { const data = await getRoutingData(); setModels(data.catalog.items); setGrants(data.grants); setSource((value) => value || data.catalog.items[0]?.model || ""); setTarget((value) => value || data.catalog.items[1]?.model || ""); } catch (value) { setError(value instanceof Error ? value.message : "UNAVAILABLE"); } }, []);
  useEffect(() => { void load(); }, [load]); const sourceModel = useMemo(() => models.find((m) => m.model === source), [models, source]); const targetModel = useMemo(() => models.find((m) => m.model === target), [models, target]);
  async function issue() { if (!sourceModel || !targetModel) return; setBusy(true); try { await createFallbackAuthorization({ source: sourceModel, targets: [targetModel], capability: targetModel.capabilities[0], minimumQuality: targetModel.quality, contentLanguage: "ar", arabicVariety: "msa", verifiedRegion: targetModel.verifiedRegions[0], executionMode: targetModel.executionModes[0], maxTotalCostUsd: Math.max(0.1, targetModel.priceUsd.amount * 10), expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString() }); await load(); } catch (value) { setError(value instanceof Error ? value.message : "UNAVAILABLE"); } finally { setBusy(false); } }
  return <main className="mx-auto w-full max-w-7xl space-y-8 p-4 lg:p-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">{t("title")}</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{t("description")}</p></div><Button variant="outline" onClick={() => void load()}><RefreshCwIcon className="size-4" />{t("refresh")}</Button></header>{error ? <p role="alert" className="rounded-lg border border-destructive/30 p-3 text-destructive">{t("error", { code: error })}</p> : null}
    <section aria-labelledby="catalog-title"><h2 id="catalog-title" className="text-lg font-semibold">{t("catalog")}</h2><p className="text-sm text-muted-foreground">{t("catalogNotice")}</p><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{models.map((model) => <article key={`${model.model}:${model.version}`} className="rounded-xl border bg-card p-4"><div className="flex justify-between gap-2"><strong>{model.label}</strong><span className="rounded-full bg-muted px-2 py-1 text-xs">{t(`lanes.${model.lane}`)}</span></div><p className="mt-1 break-all font-mono text-xs" dir="ltr">{model.model}</p><p className="mt-3 text-sm">{model.capabilities.map((capability) => t(`capabilities.${capability}`)).join(" · ")}</p><p className="mt-1 text-sm text-muted-foreground">9:16 · ${model.priceUsd.amount}/{t(`basis.${model.priceUsd.basis}`)}</p></article>)}</div></section>
    <section className="rounded-xl border p-4" aria-labelledby="grant-title"><h2 id="grant-title" className="flex items-center gap-2 text-lg font-semibold"><ShieldCheckIcon className="size-5" />{t("newGrant")}</h2><p className="mt-1 text-sm text-muted-foreground">{t("grantNotice")}</p><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">{t("source")}<select value={source} onChange={(e) => setSource(e.target.value)} className="mt-1 w-full rounded-md border bg-background p-2">{models.map((m) => <option key={m.model} value={m.model}>{m.label}</option>)}</select></label><label className="text-sm font-medium">{t("target")}<select value={target} onChange={(e) => setTarget(e.target.value)} className="mt-1 w-full rounded-md border bg-background p-2">{models.map((m) => <option key={m.model} value={m.model}>{m.label}</option>)}</select></label></div><Button className="mt-4" disabled={busy || !sourceModel || !targetModel || source === target} onClick={() => void issue()}>{t("authorize24h")}</Button></section>
    <section aria-labelledby="grants-title"><h2 id="grants-title" className="text-lg font-semibold">{t("grants")}</h2><div className="mt-3 grid gap-3">{grants.map((grant) => <article key={grant.id} className="rounded-xl border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{grant.source.model} → {grant.targets.map((item) => item.model).join(", ")}</strong><p className="mt-1 text-xs text-muted-foreground">{t("expires", { value: new Date(grant.expiresAt).toLocaleString() })}</p></div>{!grant.revokedAt ? <Button variant="destructive" size="sm" onClick={async () => { await revokeFallbackAuthorization(grant.id); await load(); }}><ShieldXIcon className="size-4" />{t("revoke")}</Button> : <span>{t("revoked")}</span>}</div><p className="mt-2 text-sm">{t("ceiling", { value: grant.maxTotalCostUsd })} · {grant.contentLanguage}/{grant.arabicVariety ?? "—"} · {grant.verifiedRegion}</p></article>)}</div>{!grants.length ? <p className="mt-3 rounded-xl border border-dashed p-6 text-center text-muted-foreground">{t("noGrants")}</p> : null}</section>
  </main>;
}
