import type { InterfaceLocale } from "@/lib/onboarding/contracts";

export const onboardingCopy = {
  ar: {
    eyebrow: "لنجهّز مساحة عملك",
    title: "أخبرنا عن علامتك",
    subtitle: "إجابات قصيرة تساعدنا على بناء ملف علامة يمكنك مراجعته قبل استخدامه.",
    continue: "متابعة",
    back: "رجوع",
    optional: "اختياري",
    saving: "جارٍ الحفظ…",
    loading: "نستعيد تقدمك…",
    retry: "إعادة المحاولة",
    identityTitle: "لنبدأ بالتعريف بك",
    fullName: "الاسم الكامل",
    companyName: "اسم الشركة أو العلامة",
    contentLanguage: "لغة المحتوى الافتراضية",
    arabic: "العربية",
    english: "English",
    sourceTitle: "كيف نتعرّف على علامتك؟",
    sourceSubtitle: "أدخل موقعك لنقرأ الصفحات العامة المهمة، أو اكتب وصفاً بنفسك.",
    website: "موقع إلكتروني",
    description: "وصف العلامة",
    websitePlaceholder: "https://example.com",
    descriptionPlaceholder: "ماذا تقدم علامتك؟ لمن؟ وما الذي يميزها؟",
    teamTitle: "أخبرنا عن مرحلتك الحالية",
    teamSize: "ما حجم فريقك الحالي؟",
    revenue: "ما الإيراد الشهري الحالي؟",
    roleTitle: "ما دورك الأساسي؟",
    businessTitle: "كيف تصف نشاطك؟",
    businessModel: "نموذج العمل",
    categories: "مجال النشاط",
    goalsTitle: "ماذا تريد أن تحقق؟",
    intent: "هل تريد التسويق الآن؟",
    outcomes: "اختر النتائج الأهم لك",
    attributionTitle: "كيف عرفت عنا؟",
    attributionSubtitle: "يمكنك تخطي هذه الخطوة.",
    preparing: "نجهّز مساحة عملك",
    preparingDetail: "نحلل المصدر ونبني ملف علامتك بشكل منظم.",
    profileTitle: "راجع ملف علامتك",
    profileSubtitle: "هذه مسودة مولّدة وليست حقيقة معتمدة حتى توافق عليها.",
    acceptProfile: "اعتماد الملف والمتابعة",
    sourceFailed: "تعذر تجهيز ملف العلامة",
    sourceFailedDetail: "يمكنك المحاولة مرة أخرى أو الرجوع واستخدام وصف يدوي.",
    educationTitle: "مساحة عملك جاهزة",
    educationSubtitle: "بُنيت اقتراحاتك الأولى من ملف العلامة الذي اعتمدته.",
    finish: "عرض الاقتراح الأول",
    error: "حدث خطأ. حاول مرة أخرى.",
    changeSource: "استخدام مصدر مختلف",
  },
  en: {
    eyebrow: "Let’s prepare your workspace",
    title: "Tell us about your brand",
    subtitle: "A few short answers help us build a Brand Profile you review before it is used.",
    continue: "Continue",
    back: "Back",
    optional: "Optional",
    saving: "Saving…",
    loading: "Restoring your progress…",
    retry: "Try again",
    identityTitle: "Let’s start with you",
    fullName: "Full name",
    companyName: "Company or brand name",
    contentLanguage: "Default content language",
    arabic: "العربية",
    english: "English",
    sourceTitle: "How should we learn about your brand?",
    sourceSubtitle: "Enter your website to read key public pages, or describe the brand yourself.",
    website: "Website",
    description: "Brand description",
    websitePlaceholder: "https://example.com",
    descriptionPlaceholder: "What do you offer, for whom, and what makes it different?",
    teamTitle: "Tell us about your current stage",
    teamSize: "How big is your current team?",
    revenue: "What is your current monthly revenue?",
    roleTitle: "What is your primary role?",
    businessTitle: "How would you describe the business?",
    businessModel: "Business model",
    categories: "Business category",
    goalsTitle: "What do you want to achieve?",
    intent: "Are you ready to market now?",
    outcomes: "Choose your most important outcomes",
    attributionTitle: "How did you hear about us?",
    attributionSubtitle: "You can skip this step.",
    preparing: "Preparing your workspace",
    preparingDetail: "We are analyzing the source and building a structured Brand Profile.",
    profileTitle: "Review your Brand Profile",
    profileSubtitle: "This is an AI-generated draft, not an accepted fact, until you approve it.",
    acceptProfile: "Accept profile and continue",
    sourceFailed: "We couldn’t prepare the Brand Profile",
    sourceFailedDetail: "Try again, or go back and provide a manual description.",
    educationTitle: "Your workspace is ready",
    educationSubtitle: "Your first suggestions use the Brand Profile you accepted.",
    finish: "See my first suggestion",
    error: "Something went wrong. Please try again.",
    changeSource: "Use a different source",
  },
} as const;

export function copyFor(locale: InterfaceLocale) {
  return onboardingCopy[locale];
}

export const optionLabels = {
  teamSize: {
    solo: { ar: "أنا فقط", en: "Just me" },
    "2_5": { ar: "2–5", en: "2–5" },
    "6_10": { ar: "6–10", en: "6–10" },
    "11_20": { ar: "11–20", en: "11–20" },
    "21_50": { ar: "21–50", en: "21–50" },
    "50_plus": { ar: "+50", en: "50+" },
  },
  revenue: {
    pre_revenue: { ar: "قبل الإيرادات", en: "Pre-revenue" },
    "1_1000_usd": { ar: "$1–$1,000", en: "$1–$1,000" },
    "1000_10000_usd": { ar: "$1,000–$10k", en: "$1,000–$10k" },
    "10000_50000_usd": { ar: "$10k–$50k", en: "$10k–$50k" },
    "50000_500000_usd": { ar: "$50k–$500k", en: "$50k–$500k" },
    "500000_plus_usd": { ar: "+$500k", en: "$500k+" },
  },
  roles: {
    founder: { ar: "مؤسس/ة", en: "Founder" },
    social_media_manager: { ar: "مدير/ة تواصل اجتماعي", en: "Social media manager" },
    marketing_manager: { ar: "مدير/ة تسويق", en: "Marketing manager" },
    agency_owner: { ar: "صاحب/ة وكالة", en: "Agency owner" },
    freelancer: { ar: "مستقل/ة", en: "Freelancer" },
    product_manager: { ar: "مدير/ة منتج", en: "Product manager" },
    content_creator: { ar: "صانع/ة محتوى", en: "Content creator" },
    growth_manager: { ar: "مدير/ة نمو", en: "Growth manager" },
    other: { ar: "أخرى", en: "Other" },
  },
  models: {
    b2b: { ar: "شركات إلى شركات", en: "B2B" },
    b2c: { ar: "شركات إلى أفراد", en: "B2C" },
    both: { ar: "كلاهما", en: "Both" },
  },
  categories: {
    ecommerce: { ar: "تجارة إلكترونية", en: "E-commerce" },
    saas: { ar: "برمجيات SaaS", en: "SaaS" },
    agency: { ar: "وكالة", en: "Agency" },
    services: { ar: "خدمات", en: "Services" },
    marketplace: { ar: "سوق إلكتروني", en: "Marketplace" },
    media_content: { ar: "إعلام ومحتوى", en: "Media & content" },
    mobile_app: { ar: "تطبيق جوال", en: "Mobile app" },
    other: { ar: "أخرى", en: "Other" },
  },
  intents: {
    marketing_now: { ar: "أريد التسويق الآن", en: "I want to market now" },
    marketing_later: { ar: "أخطط للمستقبل", en: "I’m planning for later" },
    curious: { ar: "أستكشف فقط", en: "I’m just curious" },
  },
  outcomes: {
    save_time: { ar: "توفير الوقت", en: "Save time" },
    more_social_views: { ar: "مشاهدات أكثر", en: "More social views" },
    drive_site_traffic: { ar: "زيارات للموقع", en: "Drive site traffic" },
    generate_revenue: { ar: "زيادة الإيرادات", en: "Generate revenue" },
    learn_content_marketing: { ar: "تعلم تسويق المحتوى", en: "Learn content marketing" },
    other: { ar: "نتيجة أخرى", en: "Another outcome" },
  },
  sources: {
    x: { ar: "X", en: "X" },
    linkedin: { ar: "LinkedIn", en: "LinkedIn" },
    youtube: { ar: "YouTube", en: "YouTube" },
    tiktok: { ar: "TikTok", en: "TikTok" },
    instagram: { ar: "Instagram", en: "Instagram" },
    facebook: { ar: "Facebook", en: "Facebook" },
    podcast: { ar: "بودكاست", en: "Podcast" },
    newsletter: { ar: "نشرة بريدية", en: "Newsletter" },
    google: { ar: "Google", en: "Google" },
    reddit: { ar: "Reddit", en: "Reddit" },
    referral: { ar: "ترشيح", en: "Referral" },
    other: { ar: "أخرى", en: "Other" },
  },
} as const;
