"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { Check, ChevronLeft, ChevronRight, LoaderCircle, Pause, Play, Save } from "lucide-react";
import { ARABIC_VARIETIES, AUTOMATION_STEPS } from "@/lib/product-surfaces/definitions";
import { productRequest } from "@/components/product-surfaces/ProductApi";

type Automation = { id: string; title: string; state: string; revision: number; payload: Record<string, unknown> };
const initialPayload = () => ({ currentStep: 1, name: "Campaign", formatMix: { slideshow: 25, wall_of_text: 25, green_screen_meme: 25, video_hook_demo: 25 }, remixRatio: 50, inspirationIds: [], contentLanguage: "ar", arabicVariety: "msa", personaIds: [], mediaSetIds: [], channelIds: [], variantsPerChannel: 1, cadence: { timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, startAt: null, endAt: null, postsPerWeek: 3 }, execution: { mode: "managed", modelPolicy: "workspace-default", creditCeiling: 20, budgetCents: 5000, workflow: null }, reviewMode: "request_human", autoPublishGrantId: null, validationErrors: [], runtime: null });
const list = (value: FormDataEntryValue | null) => String(value ?? "").split(",").map((item) => item.trim()).filter(Boolean);
const jsonInputs = (value: FormDataEntryValue | null) => { const raw = String(value ?? "{}").trim(); const parsed: unknown = JSON.parse(raw || "{}"); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed) || Object.values(parsed).some((item) => typeof item !== "string")) throw new Error("CAMPAIGN_WORKFLOW_INPUTS_INVALID"); return parsed as Record<string, string>; };

export function AutomationBuilder({ automations }: { automations: Automation[] }) {
  const t = useTranslations("product.automations") as (key: string, values?: Record<string, string | number>) => string;
  const router = useRouter(); const active = automations.find((item) => item.state === "draft") ?? automations[0] ?? null;
  const [step, setStep] = useState(Number(active?.payload.currentStep ?? 1)); const [payload, setPayload] = useState<Record<string, unknown>>(active?.payload ?? initialPayload()); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const next = structuredClone(payload); const set = (key: string, value: unknown) => { next[key] = value; };
    if (step === 1) set("name", String(data.get("name")));
    if (step === 2) set("formatMix", { slideshow: Number(data.get("slideshow")), wall_of_text: Number(data.get("wall")), green_screen_meme: Number(data.get("green")), video_hook_demo: Number(data.get("hook")) });
    if (step === 3) { set("remixRatio", Number(data.get("remixRatio"))); set("inspirationIds", list(data.get("inspirationIds"))); }
    if (step === 4) { set("contentLanguage", String(data.get("language"))); set("arabicVariety", data.get("language") === "ar" ? String(data.get("variety")) : null); }
    if (step === 5) { set("personaIds", list(data.get("personaIds"))); set("mediaSetIds", list(data.get("mediaSetIds"))); }
    if (step === 6) { set("channelIds", list(data.get("channelIds"))); set("variantsPerChannel", Number(data.get("variants"))); }
    if (step === 7) set("cadence", { ...(next.cadence as object), timezone: String(data.get("timezone")), postsPerWeek: Number(data.get("postsPerWeek")) });
    if (step === 8) { const workflowId = String(data.get("workflowId")); const workflowRevisionId = String(data.get("workflowRevisionId")); set("execution", { mode: String(data.get("mode")), modelPolicy: String(data.get("modelPolicy")), creditCeiling: Number(data.get("credits")), budgetCents: Number(data.get("budget")), workflow: workflowId && workflowRevisionId ? { workflowId, workflowRevisionId, inputs: jsonInputs(data.get("workflowInputs")), inputArtifactIds: list(data.get("workflowArtifacts")) } : null }); }
    if (step === 9) { set("reviewMode", String(data.get("reviewMode"))); set("autoPublishGrantId", String(data.get("grant")) || null); }
    set("currentStep", Math.min(step + 1, 10)); setBusy(true); setError("");
    try { await productRequest("/api/product-campaigns", { action: "save_draft", ...(active ? { id: active.id, expectedRevision: active.revision } : {}), title: String(next.name), payload: next, idempotencyKey: crypto.randomUUID() }); setPayload(next); if (step < 10) setStep(step + 1); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : t("error")); }
    finally { setBusy(false); }
  }
  async function control(action: "activate" | "pause") { if (!active) return; setBusy(true); setError(""); try { await productRequest("/api/product-campaigns", { action, id: active.id, expectedRevision: active.revision, idempotencyKey: crypto.randomUUID() }); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("error")); } finally { setBusy(false); } }
  const mix = payload.formatMix as Record<string, number>; const cadence = payload.cadence as Record<string, unknown>; const execution = payload.execution as Record<string, unknown>; const workflow = execution.workflow as Record<string, unknown> | null;
  return <div className="grid gap-6 xl:grid-cols-[260px_1fr_320px]">
    <aside className="rounded-3xl border bg-card p-4"><p className="px-2 text-sm font-semibold">{t("stepsTitle")}</p><ol className="mt-3 space-y-1">{AUTOMATION_STEPS.map((key, index) => <li key={key}><button onClick={() => setStep(index + 1)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-start text-sm ${step === index + 1 ? "bg-amber-100 font-semibold text-amber-950" : "hover:bg-muted"}`}><span className={`flex size-6 items-center justify-center rounded-full text-xs ${index + 1 < step ? "bg-emerald-600 text-white" : "bg-muted"}`}>{index + 1 < step ? <Check className="size-3" /> : index + 1}</span>{t(`steps.${key}`)}</button></li>)}</ol></aside>
    <form onSubmit={save} className="rounded-3xl border bg-card p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-amber-600">{t("step", { current: step, total: 10 })}</p><h2 className="mt-2 text-2xl font-semibold">{t(`steps.${AUTOMATION_STEPS[step - 1]}`)}</h2><div className="mt-6 space-y-5">
      {step === 1 && <Field name="name" label={t("fields.name")} value={String(payload.name)} />}
      {step === 2 && <div className="grid gap-4 sm:grid-cols-2"><NumberField name="slideshow" label={t("mix.slideshow")} value={mix.slideshow} /><NumberField name="wall" label={t("mix.wall")} value={mix.wall_of_text} /><NumberField name="green" label={t("mix.green")} value={mix.green_screen_meme} /><NumberField name="hook" label={t("mix.hook")} value={mix.video_hook_demo} /><p className="sm:col-span-2 text-sm text-muted-foreground">{t("mixTotal", { total: Object.values(mix).reduce((a, b) => a + b, 0) })}</p></div>}
      {step === 3 && <><NumberField name="remixRatio" label={t("fields.remix")} value={Number(payload.remixRatio)} /><Field name="inspirationIds" label={t("fields.inspiration")} value={(payload.inspirationIds as string[]).join(", ")} required={false} /></>}
      {step === 4 && <><Select name="language" label={t("fields.language")} value={String(payload.contentLanguage)} options={["ar", "en"]} t={t} prefix="languages" /><Select name="variety" label={t("fields.variety")} value={String(payload.arabicVariety ?? "msa")} options={[...ARABIC_VARIETIES]} t={t} prefix="varieties" /></>}
      {step === 5 && <><Field name="personaIds" label={t("fields.personas")} value={(payload.personaIds as string[]).join(", ")} required={false} /><Field name="mediaSetIds" label={t("fields.mediaSets")} value={(payload.mediaSetIds as string[]).join(", ")} required={false} /></>}
      {step === 6 && <><Field name="channelIds" label={t("fields.channels")} value={(payload.channelIds as string[]).join(", ")} required={false} /><NumberField name="variants" label={t("fields.variants")} value={Number(payload.variantsPerChannel)} min={1} max={10} /></>}
      {step === 7 && <><Field name="timezone" label={t("fields.timezone")} value={String(cadence.timezone)} /><NumberField name="postsPerWeek" label={t("fields.frequency")} value={Number(cadence.postsPerWeek)} min={1} max={100} /></>}
      {step === 8 && <><Select name="mode" label={t("fields.mode")} value={String(execution.mode)} options={["managed", "byok"]} t={t} prefix="modes" /><Field name="modelPolicy" label={t("fields.modelPolicy")} value={String(execution.modelPolicy)} /><Field name="workflowId" label={t("fields.workflowId")} value={String(workflow?.workflowId ?? "")} /><Field name="workflowRevisionId" label={t("fields.workflowRevisionId")} value={String(workflow?.workflowRevisionId ?? "")} /><Field name="workflowInputs" label={t("fields.workflowInputs")} value={JSON.stringify(workflow?.inputs ?? {})} /><Field name="workflowArtifacts" label={t("fields.workflowArtifacts")} value={((workflow?.inputArtifactIds as string[]) ?? []).join(", ")} required={false} /><NumberField name="credits" label={t("fields.credits")} value={Number(execution.creditCeiling)} min={0} /><NumberField name="budget" label={t("fields.budget")} value={Number(execution.budgetCents)} min={0} /></>}
      {step === 9 && <><Select name="reviewMode" label={t("fields.reviewMode")} value={String(payload.reviewMode)} options={["request_human", "evaluate_policy"]} t={t} prefix="reviewModes" /><Field name="grant" label={t("fields.grant")} value={String(payload.autoPublishGrantId ?? "")} required={false} /></>}
      {step === 10 && <div className="space-y-3">{AUTOMATION_STEPS.slice(0, 9).map((key) => <div key={key} className="flex items-center gap-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900"><Check className="size-4" />{t(`steps.${key}`)}</div>)}<p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-950">{t("activationBoundary")}</p></div>}
    </div><div className="mt-8 flex justify-between gap-3"><button type="button" disabled={step === 1} onClick={() => setStep(step - 1)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 disabled:opacity-40"><ChevronLeft className="size-4 rtl:rotate-180" />{t("back")}</button>{step < 10 ? <button disabled={busy} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-amber-300 px-5 font-semibold text-stone-950">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}{t("saveContinue")}<ChevronRight className="size-4 rtl:rotate-180" /></button> : <button type="button" disabled={busy || !active} onClick={() => control("activate")} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-600 px-5 font-semibold text-white"><Play className="size-4" />{t("activate")}</button>}</div>{error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}</form>
    <aside className="space-y-5">{automations.map((item) => <div key={item.id} className="rounded-2xl border bg-card p-4"><div className="flex justify-between"><span className="font-semibold">{item.title}</span><span className="text-xs text-muted-foreground">v{item.revision}</span></div><p className="mt-2 text-sm text-muted-foreground">{t(`states.${item.state}`)}</p>{item.state === "active" && <button onClick={() => control("pause")} className="mt-3 inline-flex items-center gap-2 text-sm"><Pause className="size-4" />{t("pause")}</button>}</div>)}</aside>
  </div>;
}

function Field({ name, label, value, required = true }: { name: string; label: string; value: string; required?: boolean }) { return <label className="grid gap-2 text-sm font-medium">{label}<input dir="auto" name={name} defaultValue={value} required={required} className="min-h-11 rounded-xl border bg-background px-3 font-normal" /></label>; }
function NumberField({ name, label, value, min = 0, max = 100 }: { name: string; label: string; value: number; min?: number; max?: number }) { return <label className="grid gap-2 text-sm font-medium">{label}<input name={name} type="number" defaultValue={value} min={min} max={max} className="min-h-11 rounded-xl border bg-background px-3" /></label>; }
function Select({ name, label, value, options, t, prefix }: { name: string; label: string; value: string; options: string[]; t: (key: never) => string; prefix: string }) { return <label className="grid gap-2 text-sm font-medium">{label}<select name={name} defaultValue={value} className="min-h-11 rounded-xl border bg-background px-3">{options.map((option) => <option key={option} value={option}>{t(`${prefix}.${option}` as never)}</option>)}</select></label>; }
